### ISSUE TITLE
produce a statically linked Go binary (does not require dynamic linking of libfilecoin_proofs.a and bls-signatures.a)

### ISSUE THREAD

**Issue by laser** [filecoin-project/venus#1379]
### Description

The existing go-filecoin build flow produces a binary with some dynamic (runtime) dependencies. CGO makes producing a statically-linked binary a challenge, [but not impossible](https://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/).

If we compile with musl (instead of glibc), we can produce a statically-linked go-filecoin binary. I've verified this (see comments in this issue, below) with Linux. I have not yet verified that the musl toolchain will work with OSX.

### Acceptance criteria

- OSX go-filecoin binary has no runtime dependencies (`otool -L go-filecoin`)
- Linux go-filecoin binary has no runtime dependencies (`ldd go-filecoin`)

### Risks + pitfalls

- libbls-signatures.a needs to be compiled with musl, which means modifying the bls-signatures release flow and CI configuration
- libfilecoin_proofs.a needs to be compiled with musl, which means modifying the rust-fil-proofs release flow and CI configuration

### Where to begin

- first, read [this](https://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/)
- then, read [this](https://github.com/filecoin-project/go-filecoin/issues/1379#issuecomment-496321897)

**Comment by ognots** [comment]
I did some testing today, and was unable to build statically linked binaries for go-filecoin.

Here's the diff of changes:
 https://github.com/filecoin-project/go-filecoin/compare/feat/static-build-test

Failed in Linux build with:
https://circleci.com/gh/filecoin-project/go-filecoin/12737

```
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /go/src/github.com/ipsn/go-secp256k1
```

I was able to reproduce in Mac OS X, as well, by setting `CGO_ENABLED=0` only during `go run ./build/*.go build`

The next step would be to investigate why github.com/ipsn/go-secp256k1 doesn't like being statically linked.

CC @phritz

**Comment by laser** [comment]
@ognots 

> by setting CGO_ENABLED=0 only during go run ./build/*.go build

Out of curiosity, why did you disable CGO during build? It does not surprise me that you see build problems trying to build go-filecoin with CGO disabled (as go-filecoin does use CGO).

**Comment by ognots** [comment]
unless I'm misreading the golang documentation, statically linking isn't possible without disabling CGO

**Comment by laser** [comment]
@ognots - I was able to produce a fully statically-linked go-filecoin binary using musl using the following Bash script on my Mac:

```
#!/usr/bin/env bash

set -x

RUST_FIL_PROOFS_SUBMODULE_SHA=d60a2465bb7ad1d7
BLS_SIGNATURES_SUBMODULE_SHA=c2f28819039ce50f
GO_FILECOIN_SUBMODULE_TAG=nightly-18136-daf715

# create temp directory into which we'll clone our project
#
cd $(mktemp -d $(mktemp -d /tmp/XXXXXX)/XXXXXX)

# clone Git repo and change working directory
#
git clone git@github.com:filecoin-project/go-filecoin.git \
  && cd go-filecoin

# update submodules to head of remote master
#
git submodule update --remote --init proofs/rust-fil-proofs/ \
  && git submodule update --remote --init bls-signatures/bls-signatures

# predictable builds by pinning to go-filecoin to a release tag
# and rust-fil-proofs to a Git SHA
#
git checkout ${GO_FILECOIN_SUBMODULE_TAG} \
  && pushd proofs/rust-fil-proofs \
  && git checkout ${RUST_FIL_PROOFS_SUBMODULE_SHA} \
  && popd \
  && pushd bls-signatures/bls-signatures \
  && git checkout ${BLS_SIGNATURES_SUBMODULE_SHA} \
  && popd

# remove all notion of pkg-config from cgo files (archive files are now
# self-contained)
#
grep --include=\*.go -l -r -e '^\/\/.*.pc$' . | xargs perl -i -pe 's/.*\.pc\n//g'

# build bls-signatures using musl
#
docker run --rm -it \
  -v "$(pwd)/bls-signatures/bls-signatures":/home/rust/src \
  ekidd/rust-musl-builder:latest \
  /bin/bash -c "cargo --version && rustup target add x86_64-unknown-linux-musl --toolchain=$(cat ./bls-signatures/bls-signatures/rust-toolchain) && sudo apt update && sudo apt install -y clang libclang-dev && cargo build --target=x86_64-unknown-linux-musl --release --all"

# copy compiled archive file and header to location where cgo can find it
#
mkdir -p ./bls-signatures/lib \
  && mkdir -p ./bls-signatures/include \
  && cp ./bls-signatures/bls-signatures/target/x86_64-unknown-linux-musl/release/libbls_signatures_ffi.a ./bls-signatures/lib/libbls_signatures.a \
  && cp ./bls-signatures/bls-signatures/target/x86_64-unknown-linux-musl/release/libbls_signatures.h ./bls-signatures/include/libbls_signatures.h

# build rust-fil-proofs
#
docker run --rm -it \
  -v "$(pwd)/proofs/rust-fil-proofs":/home/rust/src \
  ekidd/rust-musl-builder:latest \
  /bin/bash -c "cargo --version && rustup target add x86_64-unknown-linux-musl --toolchain=$(cat ./proofs/rust-fil-proofs/rust-toolchain) && sudo apt update && sudo apt install -y clang libclang-dev && cargo build --target=x86_64-unknown-linux-musl --release --all"

# copy assets to appropriate location for cgo
#
mkdir -p ./proofs/lib \
  && mkdir -p ./proofs/include \
  && cp ./proofs/rust-fil-proofs/target/x86_64-unknown-linux-musl/release/libfilecoin_proofs.a ./proofs/lib/libfilecoin_proofs.a \
  && cp ./proofs/rust-fil-proofs/target/x86_64-unknown-linux-musl/release/libfilecoin_proofs.h ./proofs/include/libfilecoin_proofs.h

# build go-filecoin
#
docker run --rm -it \
  -v "$(pwd)":/go/src/github.com/filecoin-project/go-filecoin \
  -w /go/src/github.com/filecoin-project/go-filecoin \
  golang:1.12.1-alpine \
  /bin/ash -c "apk update && apk upgrade && apk add git && apk add build-base && CGO_LDFLAGS=-no-pie CC=x86_64-alpine-linux-musl-gcc GO111MODULE=on go get . && GO111MODULE=on CGO_LDFLAGS=-no-pie CC=x86_64-alpine-linux-musl-gcc go build --ldflags '-extldflags \"-static\"' -o go-filecoin -v main.go"
```

The aforementioned script produces a fully statically linked binary suitable for use in a Linux environment. The produce something for OSX, we would need to reverse engineer a toolchain from the two Docker images (one for building Rust and one for building Go) which the script relies on.

```
$ file ./go-filecoin
./go-filecoin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

$ ldd ./go-filecoin
	not a dynamic executable

$ stat ./go-filecoin
  File: ./go-filecoin
  Size: 85916112  	Blocks: 167808     IO Block: 4096   regular file
Device: 50h/80d	Inode: 4321717223  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    rust)   Gid: ( 1000/    rust)
Access: 2019-05-27 23:46:20.000000000 +0000
Modify: 2019-05-27 23:01:50.000000000 +0000
Change: 2019-05-27 23:01:50.000000000 +0000
 Birth: -
```

**Comment by laser** [comment]
Assigning this issue to myself for triage purposes.
