### ISSUE TITLE
Enable Filecoin iptb plugins to stream output

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/venus#1701]
IPTB provides a simple implementation of the Output interface, which is used to
return information (mostly for RunCmd) such as stdout, stderr, and an exit code.

It does not support streaming data, as it is backed by byte slice. This is an
issue when dealing with commands which may return large amounts of data, such
as executing `client cat`.

We will need a better implementation of the Output interface that will allow us
to properly deal with a large amount of data coming back from stdout and stderr.

We currently have two plugins that need a new implementation of the Output
interface.

Here is updated documentation for the Output interface, needs a bit of polish,
but should provide a basic idea of the expectations for plugins and users.

_Note: This isn't really how iptb cli is currently implemented as it prints
the exit code and the error prior to even starting to read either stdout, or
stderr. The issue here is that we can't know the exit code, or if there is an
error until we have read all of the stdout and stderr which means buffering
or consuming it all so that the underlying command can properly exit to give
us the exit code, and that all output has been read and we know that there were
not errors._

```go
type Output interface {
  // Args returns the exact arguments used to generate the output.
  Args() []string

  // ExitCode returns an integer representing the exit status. This is
  // generally a zero (0) for success, or one (1) for an error, that is
  // the process exited with some none success. A value of -1 means that
  // no exit code was able to be retrieved. The user should check Error().
  // Note: ExitCode will block until an exit code from running the arguments
  // is available, this might require that all data is read from Stdout and
  // Stderr.
  ExitCode() int

  // Error returns any errors that occurred as part of the execution. This can
  // include io errors, timeouts, etc. Errors that occur prior to execution
  // should be returned by the error value along side a nil output.
  // See the Core Interface methods Init, Start, RunCmd.
  // Note: Error may block until both Stdout and Stderr are closed due to an
  // error, or EOF
  Error() error

  // It's the responsibility of the caller to the method that returns an Output
  // to call the Close method on both the returned values of Stderr() and
  // Stdout().
  // i.e) If you call RunCmd, and it returns a non nil Output, you should also
  // call Stdout().Close() and Stderr().Close()

  // Stderr is the stderr output from execution of Args.
  Stderr() io.ReadCloser

  // Stdout is the stdout output from execution of Args.
  Stdout() io.ReadCloser
}
```

### Local Filecoin Plugin

The local filecoin plugin implements the RunCmd by using `exec.CommandContext`.
It provides `Wait` which "waits for the command to exit and waits for any
copying to stdin or copying from stdout or stderr to complete". We currently
call `Wait` inside of `RunCmd`, an use `StderrPipe` and `StdoutPipe`.

The docs for `StdoutPipe` / `StderrPipe` says

> Wait will close the pipe after seeing the command exit, so most callers need
> not close the pipe themselves; however, an implication is that it is
> incorrect to call Wait before all reads from the pipe have completed.

Under the structure of `cmd` for Stderr and Stdout, it states:

_When Stderr and Stdout are not os.File_

> ... during the execution of the command a separate goroutine
> reads from the process over a pipe and delivers that data to the
> corresponding Writer. In this case, Wait does not complete until the
> goroutine reaches EOF or encounters an error.

So this means that all the data will have been read from the process, but also
that the `io.ReadCloser` will be closed when `Wait` returns. This may result in
trailing bytes being lost due to closing before all data has been read from the
pipe.

We should not call `StderrPipe` or `StdoutPipe`, but instead our own pipes
by setting the `exec.Cmd` `Stdout` and `Stderr` value ourselves with `os.Pipe`.
This will ensure that calling `Wait` does not close anything on us.

The Output implementation for use with exec.Cmd should be implemented as
follows:

```go
type Output interface {
  // Args should return the full list of arguments that are passed into RunCmd
  Args() []string

  // ExitCode return the exit code. This can be just a 0 or a 1, as getting the
  // actual exit code is platform dependent.
  // It does this by calling cmd.Wait, a returned value of nil is an exit code
  // of zero (0). If the error can be cast to an exec.ExitError, the exit code
  // should be 1 (or the real code if we choose to want it, though this is
  // platform dependent). Any other error should return a -1, and the error
  // should be available from Error()
  ExitCode() int

  // Error should return any error from cmd.Start or the error cmd.Wait if it's
  // not a cmd.ExitError
  Error() error

  // Stderr should return the reader pair to the writer of the os.Pipe assigned
  // to the cmd.Stderr
  Stderr() io.ReadCloser

  // Stdout should return the reader pair to the writer of the os.Pipe assigned
  // to the cmd.Stdout
  Stdout() io.ReadCloser
}
```

### Docker Filecoin Plugin

The docker filecoin plugin implements the RunCmd by using the golang docker api
client. This should be much simpler to fix as docker basically already does this
through its api.

```go
type Output interface {
  // Args should return the full list of arguments that are passed into RunCmd
  Args() []string

  // ExitCode return the exit code. This will be whatever the value of
  // types.ContainerExecInspect.ExitCode is, except when there is an error during
  // execution (any docker api error which can't be recovered from), in which case
  // it should return -1.
  // client.ContainerExecInspect does not block. So the output implementation will
  // require a goroutine that is create on first call to ExitCode, and waits on a
  // channel.
  ExitCode() int

  // Error should return any error from the docker api, or io errors when
  // (I guess these are still from the docker api) they occur.
  Error() error

  // The stderr / stdout implementations get a little complicated because docker
  // returns a combined reader of both stderr and stdout, this means if we want
  // to allow the user to read all the stdout, and then all the stderr we will
  // need to buffer.
  // We can use a NewNode attr (think of it like options) to allow the user to
  // define the max size of this buffer. If it outgrows the max size we set an
  // error that will be returned through Error(), and make sure that ExitCode()
  // returns -1.
  // The blocked output (one of stdout / stderr) would also probably return an
  // error from its Read method if it can't read due to being blocked.
  Stderr() io.ReadCloser
  Stdout() io.ReadCloser
}
```

**Comment by anorth** [comment]
@travisperson  is this done? If not let's move to backlog as I don't think it's needed for our immediate goals.
