### ISSUE TITLE
add a call to dump cbor-encoded data

### ISSUE THREAD

**Issue by phritz** [filecoin-project/venus#1757]
### Description

currently, we encode data to cbor in many places in the code. for example, here is a test that encodes golang objects and then decodes them. https://github.com/filecoin-project/go-filecoin/blob/aa936d6a9b216af56e129ad2691d30581d031ccd/types/block_height_test.go#L44. a lot of data on chain and on the wire is cbor encoded, as is data passed through the vm. 

frequently we want see how a golang struct gets encoded, or we have some bytes and we want to see what's in it without decoding to a golang struct. we don't currently have a way to do that. to peer into the cbor encoding i find myself writing printfs that hex encode the cbor bytes and print them, then i paste it into http://cbor.me and have it decode. this is super annoying. 

we'd like a call that pretty prints cbor encoded bytes. you can add it directly in https://github.com/ipfs/go-ipld-cbor or on the go filecoin side, which may be easier. you can put it in a new decode/ package if you want on the gfc side. we want a function that accepts a []byte and returns a string. dont worry about output format we can massage it. bonus points if you write a little command line tool in tools/ that accepts hex encoded bytes on stdin and spits out the pretty printign on stdout. 

a typical struct we encode is types/block.go

### Acceptance criteria

- function we can pass bytes and it pretty prints cbor output similar to cbor.me
- ideally a command line tool in tools/ 

### Where to begin
 
we use the refmt library to encode. feel free to use something else to decode, that might even be a feature not a bug

cc @ZenGround0 @mishmosh @warpfork

**Comment by aschmahmann** [comment]
I'll take a look at this, pretty sure refmt already has all the basic tools for this including the CLI. Is that right @warpfork?

**Comment by aschmahmann** [comment]
PR submitted with the utility function. It's really quite short and would be easy to put directly in go-filecoin if that's easier.

The binary CLI does exist in refmt already with the refmt cbor.hex=pretty command. @warpfork I'm having some trouble properly passing the streams into refmt CLI, do you have an example of how to use the CLI? Either I'm just having some being tired issues with forgetting how to pass streams or there are some bugs. If there are bugs (as opposed to quality user error on my part) let me know and I'll happily go fix them up.

**Comment by aschmahmann** [comment]
@phritz @ZenGround0 The refmt CLI currently handles this case. There's currently a small streaming bug so the syntax is `echo -n a16376616c1864 | refmt cbor.hex=pretty`. We can get the `-n` requirement patched out, but do you need a non-streaming syntax like refmt cbor.hex=pretty a16376616c1864 ?

**Comment by Kubuxu** [comment]
The reason seems to be it not liking trailing new line. That is why `-n` is necessary. `refmt` probably can be patched to fix it.

**Comment by mishmosh** [comment]
@ZenGround0 can you check if https://app.zenhub.com/workspace/o/ipfs/go-ipld-cbor/issues/58 provides what is needed and we can close?

**Comment by mishmosh** [comment]
ping @ZenGround0 - can you check if https://app.zenhub.com/workspace/o/ipfs/go-ipld-cbor/issues/58 provides what is needed and we can close?
