### ISSUE TITLE
Passing `price` and `limit` to series

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/venus#1811]
### Description

FAT series are standalone functions which which accept a context, one or more nodes, and additional arguments. Any action that occurs in a series that submits a message is going to have to provide a way to set a `price` and a `limit`. There might be more than one action as well that will need to use these options.

I want to start a discussion to determine the best way to manage these values.

**Comment by travisperson** [comment]
I think a solution to this is to follow a pattern I've started to use for managing sleeping in series (#2514) and allowing for synchronous mining (#2515).

We would set a price and limit value on the context which would be extracted from the context inside of the series and passed into the actions. This will make it easy to set a price / limit for all actions, and the value can be changed when needed.

For example, we may want to set a price of 0 during the setup, and then later update the price to another value for the rest of a test which can be done by replacing the ctx.

**Comment by travisperson** [comment]
Does this seem like an appropriate use for context @whyrusleeping?

**Comment by whyrusleeping** [comment]
Yeah, that seems appropriate to me. 
You could have a 'params' object stored in the context that has all these variables.

**Comment by travisperson** [comment]
@frrist would you want to work on this?

**Comment by frrist** [comment]
In light of the recent [comment](https://github.com/filecoin-project/go-filecoin/pull/2515#discussion_r273763967) from anorth I think you are best suited to address this.
