### ISSUE TITLE
Make it easy to attach a debugger to command line

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/venus#1834]

**Comment by mishmosh** [comment]
@mslipper is looking into this one. @travisperson or @frrist can you shed any more light on this, and if it is still relevant or anything has changed in the post-FAST world? the only note i can find from retro is "I wish daemon tests were easily debuggable (+4)".

**Comment by travisperson** [comment]
@mslipper can you add more details to this? `dlv $PID $BINARY` works, is there something else you need?

**Comment by mslipper** [comment]
@travisperson I'm not sure - my goal with this is to implement the debuggability note from the retro.

Perhaps I could take a look at the FAST debug environment and see if there's a workaround for the stdin inssue you mentioned?

**Comment by travisperson** [comment]
I found a way around this last week and have a PR (#2610) open for it. I'm going to move the documentation from the PR into a few files though before it's merged.

A few other things are also landing for FAST here in a bit. #2627 ensures we have proper output for investigating test failures, and I'm going to start working on #2497 to make it easier to discover panics during tests, and later be able to surface errors logged during execution.

**Comment by anorth** [comment]
@travisperson do we have a good method for this now? documented?
