### ISSUE TITLE
Solution for miners when commitSector or submitPoST fail

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/venus#1926]
### Description

When we send `commitSector` and `submitPoST` messages, we send them but do not wait for the response. This is bad because a failure means the miner is not going to get storage power or may even get slashed if they fail. We need a mechanism to deal with failure. The MessageSendWithRetry proved problematic. The solution may be notifying the miner and providing a manual process for resolution. An automated solution would be better so long as it doesn't adversely affect the network.

**Comment by anorth** [comment]
@acruikshank this responsibility likely lies with the storage miner module. Does it already handle this? Could we file an issue there and close this one?

**Comment by acruikshank** [comment]
The storage miner waits for a message receipt and logs an error if the seal commit message fails:
https://github.com/filecoin-project/go-storage-miner/blob/2d45f52aa002e8bff3b702b057411766ff2027eb/sealing/states.go#L184

The submit (fallback) PoSt is still go-filecoin's responsibility, and it does not wait. 

https://github.com/filecoin-project/go-filecoin/blob/593634357fd67221ee9a8f3d39a5b77b4b2a0a6d/internal/pkg/poster/poster.go#L205

I will assign this to myself.
