### ISSUE TITLE
Deps should check dependencies before running

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/venus#1963]
### Description

Running go deps will be very nearly the first impression of filecoin for many users. We list the required dependencies on in the wiki, but the failure mode for missing most of these dependencies will be frustrating. We should check for versions of all external dependencies and fail fast with good messaging if they are not met.

**Comment by anorth** [comment]
Missing `jq` is quite hard to spot. `deps` should fail immediately in that case.

**Comment by gargdeepak** [comment]
@anorth Can I please pick this up if its still an issue ?

**Comment by anorth** [comment]
Yes, that would be great
