### ISSUE TITLE
[bug] DHT providers use huge amount of bandwidth

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/venus#2064]
Not really sure why yet, but when i run a filecoin node, i get tons of incoming bandwidth. Tracing it down a bit i discovered a large portion of it is DHT provider records (it could be more things than this, but thats the first obvious one). We should be running our DHT without providers enabled. This currently isnt possible, so we need a patch from the libp2p crew (maybe i'll do it) before we can fix this.

**Comment by anorth** [comment]
Thanks for the tracing and analysis! Is there a libp2p issue we can monitor?

**Comment by vyzo** [comment]
If you turn off providers you will break autorelay...
