### ISSUE TITLE
Read from our blockchain in the past not from the head in certain contexts

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#2127]
### Description
I've been thinking a little about how we read state from our blockchain.  Most of the time we just grab the chain's head state and work with that.  This is ok and necessary in some instances, for example when updating state with message transitions during mining.  However there are a lot of instances where this is not ok.  Users in the network should really be reading state far enough back in the chain that there are strong guarantees that this state will not be erased by an alternate fork swapping out the network's history.  This kind of change probably needs to happen in a lot of places as the code frequently makes use of the assumption that the head of the blockchain is immutable.

An example of this is when storage miners check for the existence of a payment channel while negotiating with clients.  Miners should be checking that a payment channel is setup sufficiently far back in the chain to prevent reorgs from causing a situation where miner's use up a lot of bandwidth and temporary storage to get a client's file, only to have the payment channel guaranteeing payment no longer exist in the network's history.  

### Acceptance criteria
Design plan for how to do this seamlessly and without too much pain and in a way that makes it really hard to mess this up throughout the codebase.  Then implement this design.

### Risks + pitfalls
If we don't do this or do this wrong then even assuming we absolutely nail a secure blockchain protocol, the filecoin implementation will still lose people's funds and be generally unusable 👎 

### Where to begin
We need to identify all of the pieces of the protocol that require reading from an immutable state and distinguish from those pieces that should be reading from the head state.

**Comment by anorth** [comment]
FWIW I believe that all of the methods we have that directly or indirectly access chain state should be parameterised by the tipset key at which to access that state. There are many places currently that implicitly access head state, but no synchronization infrastructure to ensure that consecutive queries actually the the same state.

**Comment by anorth** [comment]
@ZenGround0 you're currently fixing a bunch of places that assume the head. After that, this issue won't be particularly actionable, though I don't disagree with your assertions. Could you maybe enumerate some places that specifically should work this way? Maybe ask @whyrusleeping or others for their thoughts?

**Comment by ZenGround0** [comment]
@anorth Thanks for checking in on this. I am suspicious that this is potentially a lot of work.  I'll write up a more specific list in this issue to test that hypothesis.

**Comment by ZenGround0** [comment]
@anorth The two biggest entrypoints that need to be addressed are calls to the blockchain from the miner and client storage protocol code and direct access through the CLI.

## Porcelain

### Message waiting
The highest leverage thing we can do to improve everything is improve the interface to message wait to allow for confirmation time safety.  The first thing we should do is fix some number of block heights (lets randomly say 10 for ~ 5 minutes but setting this needs major input from product and consensus research) and have message wait return only after this many blocks bury a message.  This should be the default.  Tests / users who know what they are doing can use a parameter / CLI flag `--unsafe` or `--fast` or `--no-wait` or something.

Since we launching with bitcoin/eth1 style probabilistic finality and not eth2/polkadot style strict finality (last I checked anyway) it will make sense to extend this interface to take in a number of block height confirmations (or units of time) that should be waited before considering the message to be accepted.  This will allow power users to explicitly tradeoff security and wait times.

### Message querying 
A very similar change to the message querying interface is also required to handle those blockchain accesses that don't actually manifest as a message sent to the chain.  Ideally waiting and querying will have an identical confirmation time interface and default behavior.

## Callers
### CLI
Lots of commands include calls to message wait or expect users to wait for an output message cid which is covered in the above discussion.  There is some design to do about how to pass in message wait params from commands that call message wait as subroutines like `miner create`.

Many other commands directly access chain state using `MessageQuery` similarly to waiting commands we need to do a bit of thinking to get an ergonomic flag/param structure on these commands. 

Less importantly `chain` commands directly accessing block and message data outside of using `MessageQuery` also could benefit from some touching up to improve UX.  For example `chain ls -l` could mark blocks as "confirmed" if they are buried deep enough.

### Storage protocol
The security guarantees miners and clients get from verifying that certain counterparty state is tracked on the blockchain are only as good as the number of rounds waited before considering those messages accepted.  Right now the main issue is that miner's don't confirm payments safely.  This will be solved by improving message wait and query porcelain interfaces, for example [here](https://github.com/filecoin-project/go-filecoin/blob/master/protocol/storage/miner.go#L288), and [here](https://github.com/filecoin-project/go-filecoin/blob/master/protocol/storage/miner.go#).

When more sophisticated client arbitration makes it into the client's storage protocol code my hunch is that this will require similar upgrades to the state confirmation endpoints to implement something secure against expected churn in the chain's head.  I know less about that protocol flow so I don't have any detailed speculation.

In order to keep miners from making very costly mistakes we are going to need to design the miner's proof entrypoints to be robust against head churn.  For example we need to query [get proving set commitments](https://github.com/filecoin-project/go-filecoin/blob/master/protocol/storage/miner.go#L614) in such a way that the proving set won't shift out from under the miner due to a slight reorg after the PoSt process has been started.  This might require some protocol breaking changes to the miner actor to do right (i.e. *NO* proving set changes propagate in the last fourth of a proving period or something of that nature).  This will likely also need the upgraded message query interface.

Giving miners and clients the "right" defaults and also allowing configuration from miner/client operators is probably a complex task also requiring input from product and research/spec people.

## Other places
Documenting slower and more secure default behavior will be important.

The message pool might benefit from ignoring the choppy head of the chain to save out on lots of work handling reorgs.  This is not necessary as the current design works with reorgs.

There are several places where the core filecoin blockchain needs to rely on past state (challenge seeds for PoSt, enforce waiting for new miner actors).  These are usually associated with the term lookback parameter and should all be tracked elsewhere.

cc @acruikshank FYI and please add in anything you see that I'm missing.  @mosh FYI

## Big takeaway
Fairly straightforward changes need to be made to porcelain and its callers.  Product needs and research / protocol knowledge, goals are going to both feed into this.  Coordinating that communication could get complicated.
