### ISSUE TITLE
How does a Filecoin node know what network prefix to use when encoding addresses?

### ISSUE THREAD

**Issue by frrist** [filecoin-project/venus#2220]
### Description
Currently, as defined in the [address spec](https://github.com/filecoin-project/specs/blob/master/address.md), there are 2 network prefixes a Filecoin node can encode an address with -- Mainnet `f` and Testnet `t`. We need to determine how a filecoin node chooses the appropriate network prefix to use when encoding an address.

**Comment by whyrusleeping** [comment]
option 1:
- kill mainnet testnet distinction

option 2:
- store the prefix in the address struct on decode
- require the prefix be specified when calling 'new from bytes' (or any other such address)
- require all callers of address creation methods have access to the chainstore/chainmanager/whatever
- give the chain* the context to know which genesis block corresponds to which network (mainnet == X, everything else == testnet)

Really, I prefer option 1.
