### ISSUE TITLE
DHT unexpectedly provides filecoin blocks

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#2357]
**Describe the bug**
The filecoin dht is providing data other than auto relay service records.

**To Reproduce**
Start a node and run `go-filecoin dht findprovs <block-cid>` for the cid of any block in the chain.  See your own peer id returned.  In [some instances](https://circleci.com/gh/filecoin-project/go-filecoin/12883?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) other node peerids also show up.

**Expected behavior**
This command should time out, no node's dht instance should provide block data.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
From @whyrusleeping: "Something isn't set up right there. The main problem is that the dht will announce everything in the datastore it's given".  Looks like we're not setting up our libp2p instance with a properly isolated datastore.

**Comment by phritz** [comment]
we should fix this for sure. nice catch. added to high priority fixes.

**Comment by anorth** [comment]
cc @anacrolix can you shed any light here?

**Comment by ZenGround0** [comment]
Pretty sure the root cause is simply that we use the same datastore [when initializing the DHT](https://github.com/filecoin-project/go-filecoin/blob/master/node/node.go#L348) as we use for lots of other stuff (cborstore, bitswap, blockstore).

We should either use another datastore or properly namespace this one into isolation depending on how we move forward with separating out datastores.

**Comment by anorth** [comment]
Can we use an in-memory store for this? Does any of the data actually need to be persisted?

**Comment by ZenGround0** [comment]
I am not sure about this but I think we don't get any benefit out of persisting right now.  There has been some discussion about persisting routing tables in between daemon startups which could have good impacts on secure bootstrapping after restarts.  Not sure if that exists in libp2p or is slated to exist soon.  That is the only reason I can think of to persist.
