### ISSUE TITLE
`testing` package included by packages

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/venus#2363]
**Describe the bug**

The `testing` package injects `flag` options when it's included which makes the flags show up in help text when using the standard `flag` singleton. We currently include the `testing` package in a few packages.

-  actor/builtin/testing.go
-  core/testing.go
-  net/testing.go
-  node/testing.go
-  types/testing_messages.go

This makes it hard to use the standard `flag` package when building binaries and consuming `go-filecoin` packages.

The `testing` package should only be included into packages explicitly used for testing (`testhelpers`) or files which have the `_test` suffix.

I put together a PR (#2362) to move files (basically call `testing.go` files) to use the proper suffix. However, these packages are consumed by `testhelpers`, and result in build errors.

There is a bit of cleanup that needs to occur to properly handle this and something we need to do so that `go-filecoin` packages can be consumed by others without polluting the standard `flag` package.

The work around at the moment is to create a new flag set and not use the global for any binary that consumes go-filecoin packages.
```go
import (
    flg "flag"
    "os"
)

var flag = flg.NewFlagSet(os.Args[0], flg.ExitOnError)
....
flag.Parse(os.Args[1:])
```

**Comment by phritz** [comment]
possibly related: https://github.com/filecoin-project/go-filecoin/issues/329

**Comment by anorth** [comment]
Just to clarify, I think @travisperson is referring to the Go SDK package named `testing`, not something of ours.

I have also experimented with moving the contents of `testing.go` files into `*_test` packages but have determined that it's probably not the right approach. Test support code from one module often needs to be used by test support code in a dependent module. Instead, I propose we form `package/testing/foo.go` subpackages provide test-support code for `package`. These packages can depend on other `anotherpackage/testing` subpackages. We could probably enforce the desired constraints with `grep`, though I don't think it's particularly high value if we have clear precedents.

This could happen as part of #2148 (but need not wait for it, either).
