### ISSUE TITLE
Move filecoin initialization logic out of init command

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/venus#2381]
### Description

#2341 Moved repo initialization out of the old API. This is a step in the right direction. It also moved genesis loading and the sequence of commands to the Init command. This is too much core logic for a command. It also left most of initialization in node. We would like to remove this type of logic from node as well.

The `init` command should take responsibility for parsing options into config and then hand off to code that lives in `repo`. Also the node `init` function should be refactored into `repo`.

### Acceptance Critieria

1. The `init` command contains no core logic. It simply populates a config option and hands off to repo code.
2. `Node`'s '`Init` function is moved into the `repo` package.
3. The `repo` initialization is well tested.

**Comment by rosalinekarr** [comment]
I'm not sure the `loadGenesis` logic should live in `repo` since repo is almost entirely concerned with the actual filesystem persistence of the application. Maybe some of the `loadGenesis` logic should be handled in `actor` or the hello protocol? Or alternatively, maybe we need a top-level `genesis` package?

**Comment by acruikshank** [comment]
@rosalinekarr `loadGenesis` doesn't concern itself with what what genesis is. I only needs to know how to retrieve one and use it to initialize the chain store. This is something we only do for initialization for the purposes of populating the repo. In that sense it is appropriate for `loadGenesis` to live in repo. The important thing is that it does not live in commands.

It's probably more appropriate to consider initialization a protocol. It makes its own network calls and makes storage calls that should not be available through the plumbing porcelain API. It is also outiside the core services. It would be better to sub `repo` package in this issue with `protocol/init`.
