### ISSUE TITLE
[bug] Bad error message when attempting to invoke miner commands on non-miner actor

### ISSUE THREAD

**Issue by mslipper** [filecoin-project/venus#2434]
**Describe the bug**
Running `go-filecoin miner pledge t1ebxo3dgpkawkreayhhnq3umue6g6sbcmlnji3si` returns the following error:

```
Error: unable to determine return type: missing export: getPledge
```

Ditto for `go-filecoin miner power t1ebxo3dgpkawkreayhhnq3umue6g6sbcmlnji3si`:

```
Error: unable to determine return type: missing export: getPower
```

**Expected behavior**
Power/pledge data should be returned.

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: OS X and Ubuntu
 - Version: User devnet binary release 0.1.4

**Comment by mslipper** [comment]
Ah, never mind - the queried actor wasn't a miner. Closing.

**Comment by shannonwells** [comment]
I reopened this b/c I think the error message ought to be better.

**Comment by frrist** [comment]
Something worth noting here, you can quickly tell if an address is a miner address by looking at the [protocol indicator](https://github.com/filecoin-project/specs/blob/master/address.md#protocol-indicator). Currently, only addresses using [protocol 2](https://github.com/filecoin-project/specs/blob/master/address.md#protocol-2-actor) can represent a miner.
