### ISSUE TITLE
Flaky test of repo/fsrepo_test.go for root user [bug]

### ISSUE THREAD

**Issue by contrun** [filecoin-project/venus#2495]
**Describe the bug**
[This line](https://github.com/filecoin-project/go-filecoin/blob/a45c0f1a70c2e8a61d6d5b4e01e641bedb344a06/repo/fsrepo_test.go#L394) change the the permission of directory, within which a new repo is to be created, to 444. Root user will ignore permission 444 and successfully create a new repo anyway. This baffled me a lot as I was running the tests in a docker container. As noted [here](https://superuser.com/questions/104015/removing-write-permission-does-not-prevent-root-from-writing-to-the-file), we may have to use `chattr` to prevent root from writing anything. This may be platform dependent. Should we remove this test or just check the user before running it?

**To Reproduce**
```
sudo su
cd repo
go test -v ./...
```
Then I got
 ```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa3e9c9]

goroutine 31 [running]:
testing.tRunner.func1(0xc000122d00)
	/usr/lib/go/src/testing/testing.go:830 +0x392
panic(0x1034880, 0x18e7fb0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/filecoin-project/go-filecoin/repo.TestCreateRepo.func3(0xc000122d00)
	/home/e/Local/go-filecoin/repo/fsrepo_test.go:399 +0x239
testing.tRunner(0xc000122d00, 0xc00009fd60)
	/usr/lib/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:916 +0x35a
FAIL	github.com/filecoin-project/go-filecoin/repo	0.049s
```

**Expected behavior**
No failed tests.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux and Ubuntu docker image
 - Version git revision a45c0f1a70c2e8a61d6d5b4e01e641bedb344a06

**Comment by travisperson** [comment]
I would say running tests as root is not something we are going to support. Were you running into issues trying to run the tests inside of docker? I think we should make sure that is possible though.

**Comment by contrun** [comment]
@travisperson I was running the test in a docker container. It also failed. I can create a PR which checks if the user is root before running this test.

**Comment by travisperson** [comment]
Is there any way you can have the test run as a different user?

**Comment by contrun** [comment]
Yes, I can. In some rare case, the current test result may surprise people. This is my point.

**Comment by anorth** [comment]
I think we could do without this particular test and its environmental assumption. This test is really just checking that failure fails.

Maybe slightly better than removing the test, could we construct a test where creating the directory will fail for some other reason? Maybe use a parent directory that does not exist:
```
		dir := filepath.Join(parentDir, "nosuchdir", "readonly")
```
Or put a file there first with which the directory name will collide.

@contrun would you be willing to make a PR doing something like that?

**Comment by contrun** [comment]
@anorth Sorry for the delay. There are two other tests in the same testing function. One check test will fail if the config file already exists. Another will check test will still succeed even if the repo directory does not exists, as the `checkWritable` function will mkdir if path does not exist. So I think it is best to check running user.
