### ISSUE TITLE
[bug] Panics in FAST tests do not surface to the CLI

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/venus#2497]
**Describe the bug**

Panics in commands do not surface to the CLI when running `TestRetrieval`.

**To Reproduce**

1. Add `panic("Explosion")` to [the first line of the `MessageWait` command](https://github.com/filecoin-project/go-filecoin/blob/master/commands/message.go#L157).
2. Run `go run ./build best --run TestRetrieval`

**Expected behavior**

The output of `go run ./build best --run TestRetrieval` should contain the string "Explosion" somewhere.

**Screenshots**

```
10:25:18.376  INFO /var/folde: RunCmd: /var/folders/nb/lm6bvxzx69b7x9rhbvrlgrz80000gn/T/TestRetrieval721140197/0 [go-filecoin message wait zDPWYqFD5XLxpFmEBMUwxbJRcxuAHDjGBsG5CX9V7H2ZVAEKAFve --enc=json] process.go:190
10:25:18.425  INFO environmen: Teardown environment environment_memory_genesis.go:144
--- FAIL: TestRetrieval (4.81s)
    require.go:794: 
                Error Trace:    retrieval_test.go:111
                Error:          Received unexpected error:
                                EOF
                Test:           TestRetrieval
FAIL
```

**Desktop (please complete the following information):**
 - macOS 10.14.3
 - current master

**Comment by travisperson** [comment]
*Implementation Notes*

**Comment by travisperson** [comment]
In FAST we have an [open stream of stderr output](https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/process_stderr_recorder.go#L10-L36) for all the processes. This might take a bit of rework, but something we could do is grab an `io.TeeReader` off of the stderr stream and do something similar to the [LinePuller](https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/fastutil/line_puller.go#L44-L63) and search through for the start of a panic, and then consume the first stack trace storing it on the process.

We'll need to expose it somehow, that might be having [RunWithStdin](https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/process.go#L185-L198) (entry point to all commands running against the daemon) monitor for the presence of the panic, and returning an error when it finds one.

**Comment by rosalinekarr** [comment]
Closing this issue in favor of #2586 instead, since this isn't an urgent issue and I have other priorities.

**Comment by frrist** [comment]
Instead of attempting to parse the entire panic and display it on failure would we be alright with identifying that a panicked has occurred, and directing the user to the log file where they may view it?

Any test/code using the FAST library would return an error like:
`16:13:08.924 ERROR /tmp/local: The daemon panicked, captured in: /tmp/localnet255779492/0/daemon.stderr process.go:145`

Thoughts?
