### ISSUE TITLE
Limit length of incoming messages

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/venus#2525]
### Description

Allowing arbitrarily sized messages into the message pool is a DoS vector. libp2p already limits messages to 1Mb, but we would like to have the option to limit further. We would like to do this as close to the network layer as possible so we don't waste resources while processing messages doomed to fail our size check. Ideally we could reconfigure libp2p to do this. At the very least we should check before marshaling the message.

### Acceptance criteria

1. Determine if the spec sets an upper bound on message size
2. Otherwise determine an appropriate limit for messages
3. Document how close the network we can validate the message size
4. Ensure that messages that exceed the limit don't make it to the message pool

**Comment by anorth** [comment]
Thanks. We shouldn't rely on libp2p's limits, we should have our own that would still work if libp2p changed underneath us.

**Comment by frrist** [comment]
In response to acceptance criteria 1. -- The spec does have a maximum size defined for objects: https://github.com/filecoin-project/specs/blob/master/data-structures.md#encoding-considerations
