### ISSUE TITLE
Some "messages" are in the wrong json format, lose "params" 

### ISSUE THREAD

**Issue by zhangkuicheng** [filecoin-project/venus#2526]
some messeages just like that :
```json
      {
        "message": {
          "to": "t2rtuxdlqyv32ew3rncwhn2lhpo7m32u3idlrvqey",
          "from": "t1e222w6twx5cnhmq4ej67i7z77wvg7umwe75cuti",
          "nonce": "6943",
          "value": null,
          "method": "commitSector",
jTuG0KiwymWNhXB6/hws5Dna+2EqdmqwIm3z7AfF/qMwQEvXV/qMSPwFPtMoexR4SksBCE2C7gvxbqzncOE0V1RTs9Xcv/O3vI46DCpHlQ=="
        },
        "gasPrice": "0",
        "gasLimit": "300"
      },
```

I'm not sure if it's an output problem, Please help confirm it.

This messeages is not correct：
`jTuG0KiwymWNhXB6/hws5Dna+2EqdmqwIm3z7AfF/qMwQEvXV/qMSPwFPtMoexR4SksBCE2C7gvxbqzncOE0V1RTs9Xcv/O3vI46DCpHlQ=="`

**Comment by anorth** [comment]
Our output formats are not well managed at the moment, see #287.

This one does seem more like an actual bug though - the commitSector method call must have params, right? Though they will be binary encoded.

@zhangkuicheng can you provide steps to reproduce that output?

**Comment by zhangkuicheng** [comment]
> Our output formats are not well managed at the moment, see #287.
> 
> This one does seem more like an actual bug though - the commitSector method call must have params, right? Though they will be binary encoded.
> 
> @zhangkuicheng can you provide steps to reproduce that output?

ok,  Run a node and turn debugging mode on,  <env  GO_FILECOIN_LOG_LEVEL=5>,  captures the messages output .

**Comment by zhangkuicheng** [comment]
> Can you tell us where you got that output? If you have a message cid, that would also be helpful.

Run a node and turn debugging mode on, GO_FILECOIN_LOG_LEVEL=5, captures the messages output, thanks

**Comment by rosalinekarr** [comment]
I suspect this has something to do with logging in the docker environment. @travisperson @frrist, would one of you mind taking this one?

**Comment by anorth** [comment]
This issue is old. Unless someone can reproduce or suggest a concrete action, I'll close it soon.

We are intending to replace use of the cmdkit API with a new HTTP API, which should definitely resolve things like this.
