### ISSUE TITLE
[bug] Cannot create miners for other peers

### ISSUE THREAD

**Issue by steven004** [filecoin-project/venus#2596]
**Describe the bug**
The go-filecoin command: 
`go-filecoin miner create [--from=<from>] [--peerid=<peerid>] [--gas-price=<gas-price>] [--gas-limit=<gas-limit>] [--preview] [--] <pledge> <collateral>`

in which there is a peerid option. It makes me think we could create a miner for another peer, but when creating it when my node has a miner already, it will say it is only allowed to create one miner for one node. 

**To Reproduce**
Just run this command use another peer's id. 

**Version information**
- Version: go-filecoin 0.1.4

**Additional context**
See more in [this discussion thread in slack](https://filecoinproject.slack.com/threads/convo/CEGB67XJ8-1555373994.008400/)

**Comment by rosalinekarr** [comment]
@anorth @whyrusleeping, should `go-filecoin miner create` even have a `--peerid` flag? It seems like we should just remove this option and always use the user's own peerID.

**Comment by whyrusleeping** [comment]
Yes. it should always be configurable. You should be able to create a miner for another node.

**Comment by rosalinekarr** [comment]
Ok, updating title then.
