### ISSUE TITLE
Don't store state of every tipset on disk forever

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#2634]
### Description
Right now we store the full state tree object (address to actor struct map) of every tipset ever processed by a daemon on disk.  This is currently the most significant part of the filecoin node's disk footprint.  Depending on the chain being processed it has been observed to take up to 20x more space than other disk writes combined.

This is much more than we need to store considering that (1) the messages in chain data can be used to reconstruct this data, and (2) the node rarely needs to read the state of the chain further back than a few tipsets.

Here is a sketch of a good first proposal from @anorth for reducing the state tree footprint:

> I gather there's a complete absence of any garbage collection? It sounds like we need to implement some GC scheme. Spitballing, we need to retain some state trees prior to the head so that we can handle re-orgs without recomputing from scratch. But those could get pretty sparse farther back in the chain. We could probably do something like keep the past few hours worth (or until some formal finality), and maybe an exponentially sparse set of snapshots back to some second threshold (if we find a use case for that).

### Acceptance criteria
(1) We store full state on disk only up to some simple notion of finality (a few hundred blocks)
(2) The code does not crash in places where it needs to read past this point.  (state can be reconstructed from persisted chain data).  We will need this until there are actual theoretical finality guarantees baked into our software (i.e. the node WILL NEVER reorg back X blocks)
~(3) NON-requirement: reconstruction in (2) is efficient.  It should be a rare edge case and we shouldn't spend too much time handling it.

### Risks + pitfalls
Creating a garbage collection routine that is aware of notions of chain finality is going to touch a lot of pieces of the system and has the potential to get complicated.

This risks ballooning into the complicated related work of garbage collecting chain data, i.e. trimming the chain data kept on disk.

This could (should?) also balloon into handling GC for actor storage state (i.e. vm/storage.go).

Idk how this impacts the HAMT's behavior. If the underlying datastore does not have every node inserted into the HAMT how does it react to a no-longer-valid Get function call?  panics? unacceptable timeouts? We will need to investigate and at the very least modify our use to handle certain errors gracefully.

We can certainly start without a good theoretical definition of finality (which we do not have) but there are risks associated with using multiple finality heuristics in the code such as introducing very unintuitive bugs.  Whoever works on this should be aware or involved in other uses of finality in the system.

### Where to begin

Start with some dirt simple notion of finality as a number of blocks (say 120 ~ 1 hour).

Come up with a design and get review.

Before implementing predict the measurable impact on disk usage.

**Comment by anorth** [comment]
Added to MFC: protocol upgrades epic, since the growing datastore will be a huge problem when we stop wiping it out every release.

**Comment by anorth** [comment]
Removing old states is equivalent to Ethereum's "prune" mode, which is the default. We may wish to leave the full historical state option available for things that want to inspect chain state history.
