### ISSUE TITLE
Prometheus Metric for Storage Power

### ISSUE THREAD

**Issue by ognots** [filecoin-project/venus#2757]
### Description
Add a prometheus gauge metric for a node's storage power.

It would be helpful to monitor bootstrap node held power as their power affects maximum/worst-case mined block time (in the case where they are the only nodes connected to network with power)

### Acceptance criteria
- [ ] a bootstrap node's storage power can be displayed in grafana

### Risks + pitfalls
none

### Where to begin
Storage power is already sent via heart beat and displayed in stats dashboard

**Comment by gargdeepak** [comment]
@anorth I can pick this up if you can give me more context about what needs to be done
