### ISSUE TITLE
Fragile and wasteful fetch/validation of blocks received by pubsub

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#2962]
### Description
The messages received on the block pubsub are full blocks (later: headers), not CIDs. The pubsub listener `node.processBlock` decodes the block but then drops it on the floor, passing only the CID to `Syncer.HandleNewTipSet`. The syncer then fetches the block again from another peer.

This is obviously wasteful, but less obviously is critical to block syntax validation (incl timestamp). Blocks are only validated by the fetcher, so if we adjusted HandleNewTipSet to accept the decoded blocks, they would skip validation. We could validate them there too, of course, but such a pattern of requiring validation before each caller of `HandleNewTipSet` is fragile.

### Acceptance criteria
- Blocks (headers) received via pubsub are not re-fetched from another peer
- There is a clear single entry point to chain sync where new blocks are validated

This is closely related to #2128. FYI @frrist

**Comment by anorth** [comment]
Implementing a pubsub topic validator would probably address this #2783. We should be very clear about whether a block header passed to the syncer is expected to be already validated, though.

**Comment by anorth** [comment]
@frrist with messages separated from block headers, and pubsub validators, we might be able to fix this now.

**Comment by frrist** [comment]
Agreed, landing this will require re-working part of how the syncer processes potential new heads. Currently, it only works with TipSets and has some tangled (https://github.com/filecoin-project/go-filecoin/issues/2128) assumptions of what's in the store. I'll need to sketch something out before providing a more concrete proposal on the changes required.

**Comment by anorth** [comment]
@ZenGround0  did more recent chain sync work resolve this?

**Comment by ZenGround0** [comment]
No.  This is one of the first performance improvements we need to make once interop is working.
