### ISSUE TITLE
Non-deterministic coverage in tests

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#2978]
### Description
The coverage report from sequential test runs shows different results. The differences are usually minor, but it's hard to tell the difference between such changes and real coverage regressions. This also hints that the tests are non-deterministic which means they're not necessarily testing what we think.

Change test or implementation code such that coverage is consistent between runs.

### Acceptance criteria
- Sequential test runs of the same code show the same coverage
- [hopefully] a no-op change shows no coverage change from codecov PR comment

**Comment by ognots** [comment]
See https://github.com/filecoin-project/go-filecoin/issues/2785#issuecomment-516522443

**Comment by anorth** [comment]
We don't need codecov integration (returning soon) to demonstrate and/or fix this. Use local coverage reports.
