### ISSUE TITLE
[bug] `go-filecoin daemon` breaks my wifi connection when first starting

### ISSUE THREAD

**Issue by pooja** [filecoin-project/venus#3006]
**Describe the bug**
After upgrading to the 0.2.4 version of go-filecoin, I tried running `go-filecoin daemon` in my terminal. I allowed connections.

For some reason, go-filecoin then proceeded to kill my internet connection. All the devices in my house that were connected to our wifi (around 20 devices or so) were no longer able to access the internet.

When I killed the node, I was able to access the internet again. 

I ran this a few times to make sure that what I was seeing was correct, and indeed: whenever I started my daemon, no one could access the internet through our wifi connection. Whenever I killed the daemon, internet access was restored.

Looking at the messages in the CLI, it seemed that during one of these attempts, the node was able to connect to a bootstrap node (I started seeing more green INFO messages rather than WARNINGs and ERRORs). Once that happened, I killed the node. Thereafter, the wifi outage only occurred in the first couple minutes after me starting up the daemon, and then the wifi outage would end (i.e. the connection would only go out for a few minutes before coming back).

Could be a go-filecoin or libp2p issue.

I captured the logs and have attached them here.
[new_log.txt](https://github.com/filecoin-project/go-filecoin/files/3346086/new_log.txt)

**To Reproduce**
1. Download and install go-filecoin 0.2.4
2. Run `go-filecoin daemon`
3. Try to access a website from your main device or any other device connected to the same network. You can also just try `ping google.com` or some other URL in another terminal window and see if you receive a response.

**Comment by travisperson** [comment]
I believe this has something to do with how aggressive libp2p is by default around the number of connection it tries to make. I've faced this issue before when running many IPFS nodes. Just turning them off didn't completely fix the issue immediately though. Power cycling your router should help, and will probably allow you to run a node and use your internet. This of course isn't a long term fix.
