### ISSUE TITLE
Remove implicit head state access in favour of explicit key

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#3022]
### Description
A bunch of places in our code access parts of actor state without identifying which state snapshot is being accessed; the head state is implicit. This pattern is enabled and made widespread by plumbing and porcelain methods which implicitly access "latest" state: e.g. all the message query and preview stuff.

This pattern is unsafe if more than one piece of the state is to be expected and the bits expected to be consistent. The head tipset and state may change at any time, concurrent with state access, leading to inconsistent results. This is a broad undefined concurrency issue across the high-level protocol code.

This should be resolved by requiring an explicit tipset key (or possibly state root CID) be passed around and required by any code attempting to read state. Since the state identified by a tipset is effectively immutable, any concurrent change to the state store should not be visible to readers. An alternate pattern might be a "state view" which has the tipset/root CID curried in.

### Acceptance criteria
- All accessors of chain state must explicitly identify the tipset at which state is to be accessed
- Code patterns should make it difficult to do the wrong thing by accident

### Risks + pitfalls
There's lots of code that needs to change.

### Where to begin
Previewer and queryer in message plumbing.

**Comment by ZenGround0** [comment]
A very related add on to this is to remove `GetHeight` from the chain store interface and instead get the height from the head tipset.  Block height is not technically state but the same inconsistency issues exist for this access.
