### ISSUE TITLE
UX: Simple message searching tools

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3031]
### Description
I should be able to run one CLI command and see a list of all the message CIDs sent to a certain actor.

Same thing goes for "from a certain actor"

All messages of a certain method i.e. "commitSector", `tokenTransfer` would also be useful.

Lots of potential followons: include receipt, search over certain heights, search w.r.t a chain head in order to search forks, more expressive searches over parameters.  We should start simple

### Acceptance criteria
We have a CLI command that can do this.  Perhaps `go-filecoin message search --[from|to|method]`.  It shouldn't be terribly slow.

### Risks + pitfalls
This will take some design.  Likely we will want to extract out functionality the waiter uses.  Perhaps the waiter can even call the searcher.  We may want to go ahead and speed up the waiter's code (#1518) as part of/ before starting this effort.

### Where to begin
Look at message waiter and how it searches for the message it waits for.

**Comment by anorth** [comment]
I'm not sure that we should implement higher level functionality like this, although am open to the idea. For reference, does Ethereum have something like this?

While I understand the motivation, this is really something for a block explorer tool to answer by maintaining extensive indexes.

**Comment by steven004** [comment]
This may not be necessary to build in this kind of functions into the filecoin package to make it bigger and bigger, and maybe slow down normal chain operations. Considerring the chain is synced in most nodes, a filscan tool can be developed to provide the same functions for everybody to access. It could be a website, or actually multiple websites if anyone wants to run.
