### ISSUE TITLE
UX: CLI inspection of proving system jobs

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3032]
### Description
Node operators would greatly benefit from having a clear way to inspect the behavior of their proving system.  Specifically it would be nice to run a CLI command and quickly see which sectors are being sealed, and if PoSt jobs are running.  

### Acceptance criteria
Something like `go-filecoin proofs porep` that outputs the sectorIDs of all sectors currently being sealed and `go-filecoin proofs post` maybe output the sectorIDs being proved over + the seed.  Maybe the porep inspection should happen through a `sectorbuilder` command instead?  Needs design.

There are a lot of cool possible additions for inspecting sectors and PoSts (and maybe even triggering PoSts, sector packing and PoReps direction from the commands line) but that is out of scope of this issue.

### Risks + pitfalls
- I know very little about the sector builder or PoSt generator designs so maybe this is challenging work.
- Anything with the FFI involved seems more challenging.
- This might be duplicate work with potential work moving the proof system interface to another proof CLI tool so don't do any of this unless @laser says it is ok
- This could bleed into "miner architecture" work and so you should consult with at least @laser and @anorth before doing this.

### Where to begin
Talk to @laser

**Comment by laser** [comment]
I think that exposing this information through the CLI will require:

1. That the command code can get at the Node’s SectorBuilder
1. That we lay down some new FFI functions to expose more of the Rust SectorBuilder state. 

I believe that @anorth  was working on a PR which exposed the SectorBuilder (or some portion thereof) via PorcelainAPI, and all commands have access to PorcelainAPI. If what I said is true, then we are pretty close. Exact details TBD, of course, given that I don’t know precisely what bits of information CLI consumers will want to see.
