### ISSUE TITLE
expose sealed sector information to mining rig operator through API

### ISSUE THREAD

**Issue by laser** [filecoin-project/venus#3074]
### Description

Storage miners add storage clients' files (pieces) to staged sectors and then seal those staged sectors. This sealing process produces a replica commitment (CommR), data commitment (CommD), and a proof of replication.

A mining rig operator will want some tools which allow them to inspect the state of the sealed sectors which they are managing. They will wish to see, for example, a list of the sectors which they have sealed - along with the commitments associated with that sector. (_@mishmosh add: Conversely, storage clients will also want to inspect the state of the data they have stored with miners. See #3085._ )

We should expose this information to miners through the CLI. An operator of a go-filecoin node should be able to type `$GETSEALEDSECTORSCMD` to see an NDJSON representation of their sealed sectors:

```json
{ "sectorId": 1000, "commD": "AAA-some-encoding-of-comm-d", "commR": "AAA-some-encoding-of-comm-r", "commRStar": "AAA-some-encoding-of-comm-r-star", "sectorPath": "/some/path/zLTHWn9s5StDP", "sectorAccess": "zLTHWn9s5StDP", "proof": "AAA-some-encoding-of-proof", "pieces": [ { "pieceKey": "XXX-some-key", "numBytes": 512, "commP": "YYY-some-encoding-of-comm-p", "pieceInclusionProof": "ZZZ-some-encoding-of-PIP" } ] }
{ "sectorId": 1001, "commD": "BBB-some-encoding-of-comm-d", "commR": "BBB-some-encoding-of-comm-r", "commRStar": "BBB-some-encoding-of-comm-r-star", "sectorPath": "/some/path/zLTHWn99asddd", "sectorAccess": "zLTHWn99asddd", "proof": "BBB-some-encoding-of-proof", "pieces": [ { "pieceKey": "QQQ-some-key", "numBytes": 321, "commP": "RRR-some-encoding-of-comm-p", "pieceInclusionProof": "SSS-some-encoding-of-PIP" } ] }
```

### Acceptance Criteria

- a miner should be able to use the CLI to obtain JSON representing each of their sealed sectors

### Where to start

- libsectorbuilder_ffi.h already defines a `sector_builder_ffi_get_sealed_sectors` function; we'll need to add a `GetAllSealedSectors` function to cgo_bindings.go
- you'll probably want to add `GetAllSealedSectors` methods to the Go `SectorBuilder` interface

### Risk + pitfalls

- Determine what to do when the operator enters this command but there exists no sector builder yet-instantiated.
- Ye who implements this will need to determine if NDJSON is an appropriate default response format.
- Ye who implements this feature must work with @mishmosh to define `$GETSEALEDSECTORSCMD`.
- Ye who implements this feature must work with @mishmosh to determine the correct string encoding for the commitments and proofs (hex?).
- The number of bytes which fit into a sector (e.g. 1024) will be different than the sum of the `numBytes` for all pieces in that staged sector. This is due to bit-padding and piece alignment. This may confuse miners and I'm not sure how to work around this.

**Comment by mishmosh** [comment]
Thanks @laser, super thorough writeup. A couple questions: 
- Is the invoker of this command responsible for tracking whether the sector is staged or sealed? Or could we possibly search in both `GetAllSealedSectors` and `GetAllStagedSectors`?
- Where can the invokers get `sectorId`? Is it part of the `dealmessage` returned here?
https://github.com/filecoin-project/go-filecoin/blob/8b71d650b65c8dabd60bf0874ea23fa65d509ca8/commands/client.go#L166

**Comment by laser** [comment]
@mishmosh 

> Where can the invokers get sectorId? Is it part of the dealmessage returned here?

Yep! The sector id will be visible in the query storage deal response IIF the sector into which the piece referenced in the deal has been sealed.

> Is the invoker of this command responsible for tracking whether the sector is staged or sealed? Or could we possibly search in both GetAllSealedSectors and GetAllStagedSectors?

We could do that. Is that a better experience than splitting those two things? I dunno! I defer to you on this one :)

**Comment by mishmosh** [comment]
Recapping from a sync with @sidke and @laser: 

- Let's use `list-sectors*` for naming
- This family of commands will have 3 variations:
  - `list-sectors` which lists all staged and sealed sectors
  - `list-sectors --staged` which lists only all staged sectors
  - `list-sectors --sealed` which lists only all sealed sectors
- Let's use hex encoding
- Instead of a single `numBytes` let's include both `numPaddedBytes` and `numUnpaddedBytes`.

**Comment by laser** [comment]
The way that we stage pieces into staged sectors will change in the coming weeks. Because of this, I humbly request that we start by exposing only _sealed_ sector information to miners through the CLI. I will follow up with @sidke about this.

**Comment by mishmosh** [comment]
> I humbly request that we start by exposing only sealed sector information to miners 
Works for me!
