### ISSUE TITLE
Support HTTP REST API

### ISSUE THREAD

**Issue by eingenito** [filecoin-project/venus#3098]
### Description
Related spec issue: https://github.com/filecoin-project/specs/issues/400

The current HTTP RPC API from go-ipfs-cmds was never designed as a general purpose API framework and is awkward for developer-users:

* doesn’t support standard web patterns, e.g. for pagination
* doesn’t support client authentication
* not a widely-used or understood standard
* lacks rich tooling and support c.f. REST, gRPC or other common frameworks
* difficult to document as a wire format
* somewhat difficult to replicate outside of Go

A standard HTTP api could address these issues and offer the possibility of cross-implementation compatibility for tools that communicate with a node. 

### Scope
The goals of this effort would be:

* Design a v1 (or v0?) REST API for interacting with a filecoin node suitable for use across implementations
* Implement the API in go-filecoin
* Migrate the existing CLI commands to use the new API possibly eliminating the use of go-ipfs-cmds

### Risks + pitfalls
A lot of work to replace a working but somewhat awkward existing API. Helpful for longer term adoption and support of 3rd parties building on Filecoin

### Where to begin
@eingenito working on a draft of such an API for review by the team and any other interested parties.

**Comment by ridewindx** [comment]
Any progress or plan on this?

**Comment by eingenito** [comment]
Hey @ridewindx there is some progress - a WIP design document: https://docs.google.com/document/d/1ANnTHOU-8612ayvvS7Ru4B1L4voojLE0R0TQ8zF1x5s/edit#

**Comment by shannonwells** [comment]
Status: See [filecoin-project/go-http-api](https://github.com/filecoin-project/go-http-api) -- further development is on hold for now.  There's a [go-filecoin branch](https://github.com/filecoin-project/go-filecoin/tree/feat/rest-api-part1) that needs to be updated to use the latest master, but it isn't far behind.

**Comment by gargdeepak** [comment]
@shannonwells @anorth I can pick this up if you can share what's remaining to be done

**Comment by anorth** [comment]
The time isn't right for this yet.
