### ISSUE TITLE
Genesis block should pass block validation

### ISSUE THREAD

**Issue by frrist** [filecoin-project/venus#3121]
### Description
Should the genesis block pass block validation or should special handling be added for genesis blocks passed to the validator

// TODO @frrist fill in details

**Comment by anorth** [comment]
See also https://github.com/filecoin-project/specs/issues/446

**Comment by frrist** [comment]
Also see
https://github.com/filecoin-project/go-filecoin/issues/3652
https://github.com/filecoin-project/go-filecoin/issues/3653
