### ISSUE TITLE
Deconstructing a filecoin miner

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/venus#3179]
This relates closely to #2968

----------------------------------------

Currently when we talk about mining we are referring to three things.

1) Gaining block rewards (`block miner`)
2) Create `commitSector` and `submitPoSt` messages (`power miner`)
3) Accepting storage deals (`storage miner`)

While these three things are related, not all of them depend on each other. Being a `block
miner` requires one to be a `power miner`, but there is no actual requirement in the other
direction. A `power miner` is not required to be a `block miner` (it's just rational to do so).

There is also no requirement that a `power miner` accept storage deals and become a `storage
miner`. Accepting deals and sealing pieces of data into sectors is just a utility of the PoSt
proofs.

Currently we require a miner to be all three. This causes a few issues in test, and adds some
additional overhead that is not required.

1) The only way to gain power on the network at the moment is through storage deals.
   This adds unneed overhead for a `power miner`. A Piece-Inclusion-Proof must be generated
   in this process, though I believe it's not required at all for power generation. Piece-Inclusion-Proof
   are primarly so a `storage client` can have proof that a `storage miner` has included a piece of data
   is in a particular sector.
   
2) To accept storage deals, a `storage miner` must also be a `block miner`.
   This imposes a challenge in testing primarly at the moment, as pointed out in #2968.
   This is purely due to that fact that the only way to register our storage deal protocols
   is through starting the `block miner` scheduler (the _mining start_ command).
   
3) A `power miner` currently must be a `block miner`, or they cannot do PoSt proofs.
   This is due to the fact that the `storage miner` (as in the miner side of the storage protocol)
   is  responsible for the scheduling of PoSt proof generation. So this ties everything together.

**Comment by anorth** [comment]
Thanks @travisperson !

This is an area of code that is not in good shape, and also a pain for miner operator customization #3140.

**Comment by taoshengshi** [comment]
fantastic! thanks @travisperson ,and I can participate the design and implementation.

**Comment by taylorshuang** [comment]
The PoST module has a big problem. I don't know if the next version will improve. No matter how much data I upload to the miners, dashboard will not change anything.

**Comment by taylorshuang** [comment]
![image](https://user-images.githubusercontent.com/1488931/62508992-22a07380-b83c-11e9-9f54-94ce148c57d0.png)
It's been two weeks.

**Comment by travisperson** [comment]
@taylorshuang you are probably running into one of two bug

https://github.com/filecoin-project/rust-fil-proofs/issues/738
https://github.com/filecoin-project/go-filecoin/issues/3019

You will need to file another issue with a miner address for us to look into the issue any further.

**Comment by anorth** [comment]
FYI @icorderi
