### ISSUE TITLE
Generalize node shutdown hooks

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#3329]
### Description
The Node object holds on to a bunch of specific callbacks and objects so that they can be shut down cleanly. These litter the node object, but also make an ordered first-in-first-out wind down fiddly to achieve. The shutdown code also has to check whether each of them is non-nil, since some may not have been started.

Replace this with a stack of callables onto which startup code can push functions that shut down the things that are started (only if they are in fact started), in reverse order. Remove the references that the Node no longer needs to hold.

### Acceptance criteria
- Node shutdown simply pops functions off a stack and executes them
- The Node doesn't hold references to things purely for the purpose of shutting them down

### Where to begin
The pubsub cancellation functions are an easy starting point.

**Comment by gargdeepak** [comment]
if this is still an issue and no one else is working on it, I can pick this up.

**Comment by anorth** [comment]
A lot of code has changed since this issue was filed, but the basic problem is still evident in `Node.Stop()`. We'd welcome your help @gargdeepak.

Please start with a small PR that solves just part of the problem so we can validate the approach you choose.

**Comment by gargdeepak** [comment]
`Node.Stop()` has roughly 20 lines of code with only 3 `Stop() `calls. I'm not sure putting them on a stack will make the code any better. Am I missing something @anorth ?
