### ISSUE TITLE
Switch network bootstrap peer initialization to string argument

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/venus#3403]
### Description

Currently we have three boolean flags that users can specify to configure the bootstrap peers their node will use when connecting to the network (`--devnet-nightly` / `--devnet-staging` / `--devnet-user`).

We are working towards making network setup a dynamic process on our ends to help support adhoc networks for testing.

Currently to add support for an additional network, with regard to bootstrapping, there are a few places we need to update the code to support adding these flags across go-filecoin itself and our tests in FAST.

Instead of using these boolean flags I would like to have the go-filecoin binary maintain a table of peer for each network, and use a string flag to grab the peers from the table and place them into the nodes configuration during initialization. Adding additional networks that can be configured through the CLI would then turn into a single table update.

I'm unsure what the flag should actually be for this sort of configuration. First guess would be `--network`. However, with the recent protocol upgrade work a network is actually defined by the genesis which is provided during initialization, so maybe the flag should be associated with the idea of configuration bootstrap peers.

### Acceptance criteria

- multiaddrs for bootstrap peers are stored in a single table by key
- multiaddrs for bootstrap configuration can be selected with a string key during init

**Comment by ognots** [comment]
:+1: on proposed design

**Comment by anorth** [comment]
SGTM. The network name is written into the genesis, so using it would be consistent. Decoupling this from the configuration of bootstrap peers could be useful, or could be a pain in practice - I think you're best placed to judge.

**Comment by travisperson** [comment]
We can decouple it but we need to provide the list some where. One suggestion was to change the behavior of the flag to take a url / file that contained the list of peers.

If we want to keep the peers in the binary (`go-filecoin`), we have to be able to reference them. Instead of passing the network name as and argument during init, we could use the network name in the genesis to select from the peer table, completely dropping the flag. If a peer list does not exist in the binary no peers would be populated, a message would be provided to the user after init that no peers were set.

Old context for reference: https://filecoinproject.slack.com/archives/CEHHJNJS3/p1567612657044100
