### ISSUE TITLE
Improve state management in election and ticket machines

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3418]
### Description
The election and ticket machines have gotten rid of some of the technical debt around dependency injection, however their interfaces are still messy taking in a lot of stateful objects.  As @frrist points out [here](https://github.com/filecoin-project/go-filecoin/pull/3287#discussion_r323541428) we would likely be better served by tying this state directly to these objects.

**Comment by anorth** [comment]
@ZenGround0 is this still relevant?

**Comment by ZenGround0** [comment]
@anorth your work adding the stateful randomness sampler is an example of what this issue describes. There is more fuzzy design/technical debt work around what if any other stateful objects should be wrapped in the ticket and election machines.  Still outstanding but low priority.
