### ISSUE TITLE
Get miner state API

### ISSUE THREAD

**Issue by ridewindx** [filecoin-project/venus#3426]
**Description**

For miner actor, the `State` struct contains so much useful information of each miner. So the actor needs to implement the `getState` method. And then those individual methods, such as `getOwner`, `getWorker`, `getPeerID`, etc., can all be deprecated.

**Acceptance criteria**

- `getState` method returns a miner's `State` instance.
- Individual query methods are deprecated, and refactor those APIs which depend on them.

**Comment by ZenGround0** [comment]
@ridewindx I'm sympathetic to this view.  But please don't label this and things like this as a bug.  Non-optimal architecture choices and imperfect design are not bugs.

**Comment by ridewindx** [comment]
@ZenGround0 Mistaking the label is my fault.
I can finish this state API. But I have a small question about the `State` struct in miner actor.
To export `State` in actor api, I must move `State` struct to package `types`, otherwise `circular import` will happen. So is it appropriate to place miner `State` struct into package `types`?

**Comment by ZenGround0** [comment]
@ridewindx no worries it is a common mistake.  While I've also had the thought that there must be a better way to get the state I am less informed on the tradeoffs in the state machine code.  This is a pretty significant change so we should wait until you get feedback from @acruikshank and @anorth on whether this is something we want to do.

**Comment by anorth** [comment]
It is not appropriate to put anything in `types`. We wish instead to remove everything from that package.

I think this may overlap with work @acruikshank is performing right now in #3482 and related PRs. The way code is organised at the moment, an actor doesn't really own its state. State is owned by the state tree, and an actor's state is provided to it at message invocation. Getting an actor's state is a method for the chain/state modules, not for the vm or actor code.
