### ISSUE TITLE
Chain import/export

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#3443]
### Description
We desire a means to export and import a Filecoin blockchain for a bunch of reasons:
- archiving and replaying for inspection and debugging
- testing and benchmarking chain validation
- transferring chain data between implementations

The exported state should include:
- all the block headers reachable from some head (optionally more blocks for uncles, etc)
- message and receipt lists referenced from headers
- the genesis block and any required initial state tree (i.e. contents of genesis.car)

Except for any necessary genesis state, the state tree is out of scope for this export, though could be considered in the future.

When importing such a state, a node might put all of the blocks etc in the local blockstore, then `HandleNewTipset` with the head key (transmitted out of band). Or it might create a `Fetcher` backed by the export file rather than network peers, thus importing only the blocks actually reached from the head.

Note that the export file should not indicate *how* the data are to be used; it's just a dumb bunch of blocks. I could maybe be convinced to add a key indicating the head tipset, but that can as easily be transmitted out of band for commands like #3442 to manipulate.

A [CAR](https://github.com/ipfs/archive-format) file could be a fine format (I don't know enough about it). So could JSONL or a sequence of CBOR objects.

### Acceptance criteria
- A mechanism supports export and import of a blockchain such that the chain can be validated without network access
- The export format can be shared by multiple implementations

### Risks + pitfalls
- It's unclear whether import/export should be done by the daemon, or a stand-alone binary, opinions welcome

### Where to begin
Start with the genesis.car file, which might be a good starting point.

FYI @frrist @whyrusleeping

**Comment by frrist** [comment]
The immediate obstacle I observe with the car file approach revolves around how go-filecoin keys data in its chains datastore. 
https://github.com/filecoin-project/go-filecoin/blob/408760c4fbb4a0274a31f2ff0c343f9318e3c5c2/chain/store.go#L357-L362
Keying values on a stringified TipSet (i.e. `{ cid1 cid2 cid2 }`) is at odds with how the `carWriter` and underlying DAG service expect to [traverse and enumerate data](
https://github.com/ipfs/go-car/blob/0c4f3fcea33d34eb1883669ee3ac6f0676ea015c/car.go#L77-L81).

**Comment by whyrusleeping** [comment]
@frrist but the individual blocks should be stored in the blockstore just fine. You should just be able to construct a dagservice, and pass it and the head of the chain to the writeCar method.

On the way in, you import all the blocks, and then you should just be able to pass the chain head to the syncer, and the syncer should be able to validate the whole chain.

**Comment by anorth** [comment]
Thanks @whyrusleeping. There's a complication in that we need to *not* traverse the state root cid, but I'm hoping there's some filter mechanism (or we can just do our own traversal).

**Comment by frrist** [comment]
One way we can avoid traversing the StateRoot is by passing something like an `ignoreSet` to a method similar to `WriteCar`. I have filed a PR that does this here: https://github.com/ipfs/go-car/pull/13
