### ISSUE TITLE
Persist more accessory data in TipSetAndState

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3537]
### Description
We are going to need a receipts cid and a weight field at least.  `TipSetAndState`'s name should probably change at this point.

### Acceptance criteria
- Parent weight field validation does not require an additional weight computation
- We have enough state to do validation of receipts in the new model where receipts belong in the child without rerunning state transitions

### Risks + pitfalls
This is a repo-breaking change.  
We may want to seriously reconsider the "put it on the tipset" refactor.
We may want to separate out / restructure block validation before making these changes.
We may want to consider giving consensus access to chain store read rather than having the syncer act as an intermediary.

### Where to begin
Consider some of the options above, modify tipsetandstate and puttipsetandstate.

**Comment by anorth** [comment]
@ZenGround0 how much of this is still relevant?

**Comment by ZenGround0** [comment]
@acruikshank took care of receipts months ago.  Some details are outdated but persisting weight is an outstanding performance optimization we should address down the road.
