### ISSUE TITLE
Pre validation: epochs and timestamps

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3707]
### Description
Some validation rules should be run immediately on a block to prevent choking up the dispatcher queue with obviously invalid blocks.  This issue covers running timing and epoch checks which prevent the syncer's internal state from transitioning from follow to catchup from trivial incorrect blocks.

### Acceptance criteria
Blocks from bad epochs or with mismatched timestamps are never enqueued in the dispatcher priority queue.

### Risks + pitfalls
Inside or outside the dispatcher main loop?

**Comment by anorth** [comment]
@ZenGround0 still outstanding?

**Comment by ZenGround0** [comment]
Looking at the dispatcher this is still outstanding.  This falls under the DOS resistance/hardening category and should be handled during painnet.
