### ISSUE TITLE
Rework StorageMiner, StorageProtocol, and RetrievalProtocol to be constructed in build phase

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/venus#3738]
### Description
Currently the StorageMiner, StorageProtocol and RetrievalProtocol submodules require subcomponents that can only be constructed when mining starts. Rework these modules so that they can be constructed during the build phase and then enabled on mining start.

**Comment by anorth** [comment]
@acruikshank did the use of shared modules resolve this?

**Comment by acruikshank** [comment]
@anorth I added this issue to note the fact that we were not easily able to integrate the shared components at node construction, so they are still constructed at the start of mining.
