### ISSUE TITLE
"Error: no actor at address" when setup with gengen tool

### ISSUE THREAD

**Issue by satoshi999** [filecoin-project/venus#3793]
I tried setup using gengen tool for create private network.
it says error when setup step of below.
```
$./go-filecoin miner update-peerid --from $walletaddr --gas-price 0.001 --gas-limit=300 $mineraddr $peerid
$Error: no actor at address t3w2swmn2fj27pzmbn4bkeguwimphn55757fhgydz7agnjq7n2ln2mig2w3w6gf75nifax76utetjs5dzs4t4a: no actor at address $t3w2swmn2fj27pzmbn4bkeguwimphn55757fhgydz7agnjq7n2ln2mig2w3w6gf75nifax76utetjs5dzs4t4a: actor not found
```

**Version information:**
os: ubuntu 18.04.2 LTS:
go version: go1.13.8 linux/amd64

**Filecoin Version:**
go-filecoin version 
returns commit: db01e3c8d82d397268d4c334d3f8d8d0e8f74441

**Comment by anorth** [comment]
The genesis state is undergoing some radical renovation right now. We'll have that working again soon.
