### ISSUE TITLE
Update chain export to handle new state machine

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3896]
### Description
Because of the commR/commD cid decision and the fact that chain export packages genesis state up in the exported car file we end up failing on writing the commX cids when exporting the up to date actor state.

### Acceptance criteria
Fix this so export just works.  Reduce complexity by leveraging go-car's filtering functionality.  I think we can totally delete chain/export function and all of its manual traversal code by instead grabbing all of the non-gen state roots and adding them to the car writer's filtering function (see `feat/export-update` branch)

### Risks + pitfalls
Go through the callers to export, including the chain-util tool and fix them to not rely on the chain package dep anymore.  This might involve some reshuffling and dependency juggling

### Where to begin
I've got a working but dirty branch doing this `feat/export-update`.  The next step is finding all callers of chain export, moving them to use the chain state thing (if possible, rearranging dependencies or duplicating chain state car walker call otherwise).  Figuring out where to put tests (might move them all to plumbing) is probably the most complex bit.  We might just want to delete non end to end tests since we're moving from implementing functionality to relying on go-car packages functionality

**Comment by anorth** [comment]
Rather than computing an exclusion list, we should be able to give a selector that specifies the inclusion, if the description of https://github.com/ipld/go-car/pull/18 is not a lie.
