### ISSUE TITLE
Track payment channel creation state before it's finished

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/venus#4045]
### Description
It's technically possible for a client/miner to enter into two separate retrieval deals before a first payment channel has been created.  There needs to be some way to keep track of whether a payment channel creation has been initiated and respond appropriately in such case as a second deal is requested before the payment channel creation is on chain and has been put into the store with the new channel info.

### Risks + pitfalls
The current key for the store is the payment channel robust address. This was chosen because once the channel has been created, the calls to the retrieval market APIs provide only the payment channel address.  Rather than querying the actor state every time to get client and miner addresses, it's easier to get it out of the store.

Possible solutions:
Either way it may be desirable to store error state in the ChannelInfo if the channel is never created (or the wait times out/does not reach desired confirmation) but that is for another discussion.

1. Always use combined client and miner as key for the store.  This means whenever an API function is called with the payment channel address,  you'll have to get these addresses from actor state.  These calls will be made much more often than GetOrCreatePaymentChannel, which is the only one that uses client and miner address.  I'm not sure how expensive this is.

1. Use combined client and miner address as key for the store until the payment channel actor has been  constructed and its new addresses posted on chain. This is basically the same as adding an index to a database. It is more complex up front, but once a payment channel has been constructed, I believe it might be easier and faster to do the lookup.  Only GetOrCreatePaymentChannel and WaitForPaymentChannelCreation need ever to use the index key. The risk here is that there are two entries for the same payment channel and some coding error could end up updating different ones. There could easily be some guards implemented to protect against this. Here is how this could work:

For payment channel address = `0xdeadbeef`, messageCID=`0x1234`
**ChannelInfo if key= clientminer,** 
before paych is created but after the message appears on chain:
```channelInfo = {  robustAddress = address.Undef messageCID = 0x1234... }```
after message is on chain:
```channelInfo = {  robustAddress = 0xdeadbeef messageCID = 0x1234... }```

**ChannelInfo if key=0xdeadbeef**
```channelInfo = { robustAddress: 0xdeadbeef, messageCID:  cid.Undef ... }```

Pseudocode in GetOrCreatePaymentChannel
```
   build the key w/ client+miner address
   if the clientminer key exists, get the channelInfo
        if robustAddress == address.Undef
            return address.Undef, messageCID, nil
        else 
            addFundsMcid, err = AddFunds
            return robustAddress, addFundsMcid, err
  else
      carry on initiating payment channel creation
```

**Comment by anorth** [comment]
I can't quite grok the assumptions that the module is making, but if a client and provider happen to already have a channel open, that should not break anything. There's a policy question about whether the module should create a new channel or attempt to re-use an existing one. There may be reasons why re-use is not desirable or possible, such as the upper limit on lane count.

**Comment by shannonwells** [comment]
This module assumes deals between a single client/provider pair should be on the same payment channel. If we change this to expect a single payment channel per deal, then both code and API must be changed to reflect this; GetOrCreatePaymentChannel parameters provide only a client, miner and a value, and if a channel exists, we're supposed to add funds to the channel. So there's currently no way of determining which channel to add funds to if >1 is active. 

The provider stores its first voucher based on payment channel, so for a retrieval provider there would be no collisions.

There is currently no mechanism to reset/keep track of lanes, nor to retire a payment channel once Settle/Collect have completed.  This seems like a spec issue since I would think all implementations need to treat payment channels the same way.

**Comment by hannahhoward** [comment]
to provide some additional context:

this module is largely based on the one in lotus, which makes the assumption that there will only ever be a single channel between a given sender / receiver pair. I was not aware of lane limits, and I do not believe they account for it.

It strikes me that I think there are a number design questions with managing payment channels outside of actors, and very few eyes on it. Now that i know a little bit more about how they are supposed to work from an actor standpoint (@shannonwells explained to me this morning), I think probably neither the existing go-filecoin nor the Lotus design are fully functional.

**Comment by hannahhoward** [comment]
The shared components team has written the GFC version of this module entirely, and maintained the Lotus one quite a bit, but it was never in our original mandate of responsibilities, so I think we've often just done what we needed to to get it to work.

**Comment by anorth** [comment]
Great, thank you both. @hannahhoward could you arrange for a write-up of these issues and perhaps the beginning of a technical design doc to resolve them? Not urgent, but seems important. cc @mishmosh @icorderi
