### ISSUE TITLE
Payment channels should keep track of funds allocated per lane

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/venus#4046]
### Description
Subsequent calls to AllocateLane should keep track of how much is dedicated to each lane and behavior appropriately when vouchers exceed lane amounts, not just total amount in channel

### Acceptance criteria
Needs design

### Where to begin
[paymentchannel/manager](https://github.com/filecoin-project/go-filecoin/blob/master/internal/app/go-filecoin/paymentchannel/manager.go)

**Comment by anorth** [comment]
Discussion in https://github.com/filecoin-project/go-filecoin/issues/4067#issuecomment-623804012

There is some debate about whether this functionality should be in go-filecoin at all.
