### ISSUE TITLE
Find deal ID on chain efficiently

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/venus#4066]
### Description

go-fil-market's `ValidatePublishedDeal` method currently requires go-filecoin to locate a deal ID by providing the message CID of the message that put the deal on chain. This method looks up that message and retrieves the deal id from it's receipt. In the best of cases, this is inefficient because we have no message index, so it requires the node to retrieve all the messages from all the tipsets back until the message is found. If the message was not processed for any reason, the node will continue checking until it reaches the genesis tipset.

There are a few possible approaches to fix this:

1. Fix storage protocol so that deals can be uniquely identified without resorting to message identification.
2. Locate the deal in chain state. Deals cannot be uniquely identified without deal ID, because the same client can store the same piece with the same miner for the same time period resulting in a deal that looks identical aside form deal id. In practice, this is highly unlikely, so locating the deal id by examining the client's deal proposals should be possible. In the case of multiple identical proposals, the code could fall back to message find.

### Acceptance criteria

1. Message Find is not required to locate deal id in most cases.

**Comment by anorth** [comment]
FYI @hannahhoward. This is no doubt related to our discussions today and is a good motivating example.

**Comment by anorth** [comment]
see #4081
