### ISSUE TITLE
Slow iteration of all deal states in storage market connector

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#4081]
The unreasonably-expensive on chain index of deals by party in the market actor has gone. To satisfy the storage market module interface for listing deals we now iterate _all_ deal states and check them against a predicate of client or provider ID. This will be really slow. We need to index deals by party locally, somewhere.

This issue needs to be resolved in collaboration with the markets team by finding a solid agreement on where the module interface boundary should lie, and hence where indexes should be held. This is primarily a tracking issue for go-filecoin.

Some related discussion is in https://github.com/filecoin-project/go-fil-markets/issues/224, https://github.com/filecoin-project/specs/issues/919

cc @hannahhoward @acruikshank

**Comment by yancaitech** [comment]
mark
