### ISSUE TITLE
Add block semantic validation

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/venus#4098]
Lotus is implementing the proposal [here](https://github.com/filecoin-project/specs/issues/934) in painnet. I'm not sure how much (if any) of this validation gfc already does, but there's scope for a malicious actor to split the network with a bad block.

Detailed description of exactly what validation Lotus does: https://github.com/filecoin-project/specs/issues/934#issuecomment-627057458

**Comment by anorth** [comment]
Block semantic validation is much bigger than the call seq nums, and I think we're missing much of it. A bunch of related stuff happens in `ValidateMining`, but that's not the right place.

**Comment by anorth** [comment]
Block syntax/semantic validation must also run on blocks that the node itself produces.
