### ISSUE TITLE
**/genesis.car: dial tcp: lookup genesis.user.kittyhawk.wtf: no such host

### ISSUE THREAD

**Issue by chenzhijun45** [filecoin-project/venus#4181]
**version**  :  filecoin-0.5.8-Linux.tar.gz
I just got in touch with filecoin，Encountered a lot of problems.
I replaced multiple links, but, When I execute the init command, He always gives this error: `Error: Get https://genesis.user.kittyhawk.wtf/genesis.car: dial tcp: lookup genesis.user.kittyhawk.wtf: no such host`.
Who can tell me how to run filecoin testnet node, Thanks!
In addition, I can't get test coins by [Faucet](https://spacerace.faucet.glif.io/), It is always "Request failed with status code 500"...

**Comment by RobQuistNL** [comment]
You probably really want to use the Lotus project at this point: https://github.com/filecoin-project/lotus

**Comment by hsanjuan** [comment]
https://docs.filecoin.io

**Comment by xwh123** [comment]
Hello, have you solved this problem?
