### ISSUE TITLE
can not find opencl

### ISSUE THREAD

**Issue by dawnFromDark** [filecoin-project/venus#4259]
dear developers , when i compiled the venus, it can not find opencl deps, the problem as following:
![image](https://user-images.githubusercontent.com/44474000/102073919-fab51d00-3e3e-11eb-8934-6a1ae4ef8419.png)

may you tell me how install opencl for venus to compile it,thank in advance.

**Comment by dawnFromDark** [comment]
i tried many way to install it , included the cuda or the opencl from intel, it can not be successful.

**Comment by hunjixin** [comment]
reference:  https://unix.stackexchange.com/questions/292630/how-to-install-opencl-in-centos-7-using-yum

**Comment by dawnFromDark** [comment]
> reference: https://unix.stackexchange.com/questions/292630/how-to-install-opencl-in-centos-7-using-yum

thank you for your help.
