### ISSUE TITLE
Venus make bug

### ISSUE THREAD

**Issue by hesen2006cn** [filecoin-project/venus#4354]
**Describe the bug**:
go run ./build/*.go build
Building venus...
git log -n 1 --format=%H
git rev-list --tags --max-count=1
git describe --tags cb8a4427312b237f2343926a726455883067098c
bash -c go build -ldflags=github.com/filecoin-project/venus="-X github.com/filecoin-project/venus/build/flags.GitRoot=/Users/hesen/Documents/go-workspace-git/filecoin-project/venus -X github.com/filecoin-project/venus/build/flags.GitCommit=cb8a4427312b237f2343926a726455883067098c -X github.com/filecoin-project/venus/build/flags.GitTag=v0.9.1-rc" -v -o venus .
github.com/filecoin-project/filecoin-ffi/generated
# github.com/filecoin-project/filecoin-ffi/generated
ld: library not found for -lhwloc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Command 'bash -c go build -ldflags=github.com/filecoin-project/venus="-X github.com/filecoin-project/venus/build/flags.GitRoot=/Users/hesen/Documents/go-workspace-git/filecoin-project/venus -X github.com/filecoin-project/venus/build/flags.GitCommit=cb8a4427312b237f2343926a726455883067098c -X github.com/filecoin-project/venus/build/flags.GitTag=v0.9.1-rc" -v -o venus .' failed: exit status 2
exit status 1
make: *** [Makefile:2: all] Error 1
**Expected behavior**:
Don't install lhwloc
**Diagnostic information:**

To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
This command may take a few minutes to run due to the large size of the repository.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "lhwloc".
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get its complete history, run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
- Filecoin Version: 
- Filecoin Inspect Output: 
- Initialization Command:

**Comment by Fatman13** [comment]
Did you install `lhwloc`?

**Comment by hunjixin** [comment]
> Did you install `lhwloc`?
brew install lhwloc

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus-docs/blob/master/docs/Getting-Started.md
