### ISSUE TITLE
go-filecoin init 

### ISSUE THREAD

**Issue by xwh123** [filecoin-project/venus#4361]
execute      ./go-filecoin init –devnet-user –genesisfile=http://user.kittyhawk.wtf:8020/genesis.car  

Error:  Get http://user.kittyhawk.wtf:8020/genesis.car: dial tcp: lookup user.kittyhawk.wtf: no such host

- Filecoin Version: 
- Filecoin Inspect Output: 
- Initialization Command:

**Comment by hunjixin** [comment]
https://venus.filecoin.io/Getting-Started.html#table-of-contents
