### ISSUE TITLE
failed sync of

### ISSUE THREAD

**Issue by fuyundian** [filecoin-project/venus#4371]
**Describe the bug**:
021-03-24T12:58:12.554+0800	[34mINFO[0m	chainsync.dispatcher	dispatcher/dispatcher.go:189	failed sync of { bafy2bzaceayfmfp7w3e7fogmmfwsqkkitdlye2elqjcur7ns4txgktbnjwxr6 bafy2bzacebj43kfyhqnn26jkrsp7bzf53l4gfy4b3ilfulxvire2hfjg4tekg } at 92856  process message failed failed to sync tipset { bafy2bzacebeudsbqx7ex3zhrlgzt7uifphgianr5kg556uswpu6qbutbz3ap4 }, number 0 of 32 in chain: validate mining failed 1 error occurred:
	* invalid election post:
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).validateBlock.func7
        /root/venus.bak/pkg/consensus/block_validator.go:255
  - failed to verify election post:
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).VerifyWinningPoStProof
        /root/venus.bak/pkg/consensus/block_validator.go:699
  - No cached parameters found for proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e [failure finding /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.params]
    github.com/filecoin-project/filecoin-ffi.VerifyWinningPoSt
    	/root/venus.bak/extern/filecoin-ffi/proofs.go:92
    github.com/filecoin-project/venus/pkg/util/ffiwrapper.proofVerifier.VerifyWinningPoSt
    	/root/venus.bak/pkg/util/ffiwrapper/verifier_cgo.go:122
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).VerifyWinningPoStProof
    	/root/venus.bak/pkg/consensus/block_validator.go:691
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).validateBlock.func7
    	/root/venus.bak/pkg/consensus/block_validator.go:254
    github.com/Gurpartap/async.Err.func1
    	/root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1371

: 1 error occurred:
	* invalid election post:
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).validateBlock.func7
        /root/venus.bak/pkg/consensus/block_validator.go:255
  - failed to verify election post:
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).VerifyWinningPoStProof
        /root/venus.bak/pkg/consensus/block_validator.go:699
  - No cached parameters found for proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e [failure finding /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.params]
    github.com/filecoin-project/filecoin-ffi.VerifyWinningPoSt
    	/root/venus.bak/extern/filecoin-ffi/proofs.go:92
    github.com/filecoin-project/venus/pkg/util/ffiwrapper.proofVerifier.VerifyWinningPoSt
    	/root/venus.bak/pkg/util/ffiwrapper/verifier_cgo.go:122
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).VerifyWinningPoStProof
    	/root/venus.bak/pkg/consensus/block_validator.go:691
    github.com/filecoin-project/venus/pkg/consensus.(*BlockValidator).validateBlock.func7
    	/root/venus.bak/pkg/consensus/block_validator.go:254
    github.com/Gurpartap/async.Err.func1
    	/root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1371
**Expected behavior**:

**Diagnostic information:**

- Filecoin Version: 
- Filecoin Inspect Output: 
- Initialization Command:

**Comment by hunjixin** [comment]
./venus fetch --size=0

**Comment by fuyundian** [comment]
> fetch

我是少了什么操作吗？

**Comment by hunjixin** [comment]
@fuyundian  ./venus fetch --size=0

**Comment by fuyundian** [comment]
谢谢你，可以同步了

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/pull/4372
