### ISSUE TITLE
How to Start Miners

### ISSUE THREAD

**Issue by fuyundian** [filecoin-project/venus#4375]
### Description
Please first see README for how to get help before filing a new issue.

### Acceptance criteria
I want to mine first, but I don't know how to set up

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus-docs/blob/master/docs/How-to-setup_2knet.md @fuyundian

**Comment by hunjixin** [comment]
@fuyundian Recently, we started a cluster test environment on Nerpa network. Do you want to participate in the test
