### ISSUE TITLE
Peers are removed from the routing table on disconnect (go-libp2p-kad-dht)

### ISSUE THREAD

**Issue by laser** [filecoin-project/venus#439]
### Description

Address potential DoS vector, explained [here](https://github.com/libp2p/go-libp2p-kad-dht/issues/45).

### Acceptance criteria

TBD

### Risks + pitfalls

TBD

### Where to begin

TBD

**Comment by anacrolix** [comment]
@hunjixin what was the resolution here?

**Comment by hunjixin** [comment]
@anacrolix Since the code changes a lot and we're not going to check the problem one by one, we've closed these issue now, and if the problem persists, please reopen the issue and we'll track it down.
