### ISSUE TITLE
Build fails on `extern/filecoin-ffi`

### ISSUE THREAD

**Issue by ojab** [filecoin-project/venus#4486]
**Describe the bug**:
```
$ make
go run ./build/*.go build
go: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20200910194244-f640612a1a1f (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /tmp/venus/extern/filecoin-ffi/go.mod: no such file or directory
make: *** [Makefile:5: all] Error 1
```

**Expected behavior**:
it builds

**Diagnostic information:**
above? Linux x86_64, `go version go1.16.2 linux/amd64`

- Filecoin Version: 1.0 or git master 
- Filecoin Inspect Output: ????
- Initialization Command: ????

**Comment by simlecode** [comment]
1. make deps
2. make

**Comment by ojab** [comment]
Thanks, that works.
