### ISSUE TITLE
同步优化

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#4551]
- [x] Graceful shutdown the system.
We catches 'interrupt' and 'sigterm' signals at 
https://github.com/filecoin-project/venus/blob/698bae1b6b2272faaed70e9d3c996f8999cf62ac/app/node/node.go#L239-L244
the 'quit' signals  would also been catch by 'memguard.CatchInterrupt()' for data security reason, it finally terminals the process with 'os.exit(0)':
https://github.com/filecoin-project/venus/blob/698bae1b6b2272faaed70e9d3c996f8999cf62ac/pkg/crypto/keyinfo.go#L22-L25
they are conflicting, only one place can be executed while 'venus' exiting. this may cause 'venus' shutdown  'ungraceful'.
it solves accidental chain data 'broken' problems when 'kill' or 'control+c' to stop and restart venus. 

- [x] because the  changing of architecture, unit test, integration test, functional test all CAN'T passed.
- [x] fix close an uninitialized datastore.
the 'staging' haven't initialized or used anywhere, when 'repo' close, this would cause a panic.
https://github.com/filecoin-project/venus/blob/8e60ecffe522e433f3b40628dd20c4a96899b774/pkg/repo/fsrepo.go#L358-L361

- [x] optimize 'handleincomingmessage' in mpool_submodule.
these 2 following validation is duplicated.
https://github.com/filecoin-project/venus/blob/8e60ecffe522e433f3b40628dd20c4a96899b774/app/submodule/mpool/mpool_submodule.go#L94-L99
checking if the incoming byte could be 'unmarshall' to a 'message' struct and 'verify signature' are both do when adding it to message pool.
especially 'verify signature', it would cause very bad performance.
each time a 'message' coming,  we have to load 'Account view' from 'state tree',  for getting its public key. loading 'state tree' is a very slow operation.
https://github.com/filecoin-project/venus/blob/8e60ecffe522e433f3b40628dd20c4a96899b774/pkg/consensus/message_validator.go#L154-L168 
and as following shows, handling incoming message is serial.
https://github.com/filecoin-project/venus/blob/8e60ecffe522e433f3b40628dd20c4a96899b774/app/submodule/mpool/mpool_submodule.go#L192-L206
this is why this 'validation' cause incoming message so slow. 
and if handling the incoming message is slow, when 'receive a new block ' form network, we have to fetch block messages from p2p network. 
this cause chain head forwarding slow down for several even more than 10 seconds.

- [x] chain syncing optimization:
In current version of chain syncing, when a block comes in, 
it was added to current chain head(tipset), 
chain syncing module compute the new tipset(contains a new comes in block and older blocks[which venus had compute state root for them])).
this is a O(n^2) complexity for just one tipset. here is the top of call stack:
https://github.com/filecoin-project/venus/blob/62e83f10d3660224bd5aaae9f4f31a59914090ab/pkg/chainsync/dispatcher/dispatcher.go#L179-L197

to optimize this, the main idea is:
try best to execute 'tipset' only one time for each epoch.  
there are 2 situations venus syncing module computes state root for a tipset:
1. the chain head is stable(chain head haven't change for a few(6) seconds)
2. in the next epoch, if the previous tipset state root doesn't exists, block validator computes it and check if it equals current tipset's parent state root.
in most situations, the 2nd situation doesn't needs to compute previous state root, 
it just get previous state root from a cache.

- [x]  cut the times of the loop to half in fetchBlockMessages.

**Comment by Fatman13** [comment]
Closing old issues to have a fresh start.

**Comment by Fatman13** [comment]
Closing old issues to have a fresh start.

**Comment by Fatman13** [comment]
继续探索，重新开新的ticket。
