### ISSUE TITLE
gaslimit of block reward implicit message un-consensus

### ISSUE THREAD

**Issue by zl03jsj** [filecoin-project/venus#4592]
venus block reward gaslimit is blockgaslimit * 1000 here:
https://github.com/filecoin-project/venus/blob/c47a6109d0fd4f6faf4eb9d51a12c6f55fd0c948/pkg/vm/vmcontext/vmcontext.go#L354-L356

but lotus block reward gaslimit is 1<<30 here:

https://github.com/filecoin-project/lotus/blob/e196a81e99459cb368830c2490f51b186a4cec89/chain/consensus/filcns/compute_state.go#L215-L224

this may be an hidden trouble that causes chain syncing problems.

**Comment by Fatman13** [comment]
Closing old issues to have a fresh start.
