### ISSUE TITLE
venus-worker的store配置功能测试

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4606]
以`lotus-miner`/`lotus-worker`的行为为参照，对比`venus-sealer`/`venus-worker`是不是一致或者有bug?

`venus-worker`设置和`venus-sealer`不同的store目录，测试在做时空证明时能不能找到`sector`。

**Comment by diwufeiwen** [comment]
venus-sealer设置多个store，一般采用挂载方式保证每个store都能被sealer访问即可. 关于storage介绍可参考: https://github.com/filecoin-project/venus-docs/blob/4f9dd3c54a20d2a4332aed835bd13f62e7558bf0/docs/zh/guide/Introduction-to-storage.md
