### ISSUE TITLE
建议在Venus中增加API访问调用接口

### ISSUE THREAD

**Issue by ly82505129** [filecoin-project/venus#4608]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [x] I **have** a specific, actionable, and well motivated improvement to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [X] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### Improvement Suggestion

1、目前venus还是通过./venus-sealer sectors list 来查看当前sealer的扇区状态，是否可以支持api接口来调用每个sector的状态，在页面端进行展示和实时查看
2、建议增加./venus-sealing jobs的接口，来查看当前任务状态接口；
3、建议增加./venus-market data-transfers list 和storage-deals list等命令对应的信息内容的查询接口

**Comment by Fatman13** [comment]
@ly82505129 理论上任何cli命令有的，都有API。只要使用venus-sealer给的token，就可以访问这些jsonrpc。现在开发团队看看能不能整理一个api文档出来。

**Comment by ly82505129** [comment]
> 

好的，非常感谢，希望能尽快输出jsonrpc 的api文档

**Comment by zl03jsj** [comment]
venus-sealer生成api文档:
https://github.com/filecoin-project/venus-sealer/pull/161
sealer api 文档:
https://github.com/filecoin-project/venus-sealer/blob/opt/for_market_v2/docs/api-documents.md

venus生成api文档:#4640 
venus api 文档:https://github.com/filecoin-project/venus/blob/feat/venus-v2/venus-shared/api/api-document.md
