### ISSUE TITLE
venus-sealer封装ticket过期判断优化

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4613]
P1-P2任务积压，导致PreCommitSector消息没有在24小时内上链，Ticket生命周期判断。例，一些PC2任务过期的判断。如果有大量的P2任务积压，P1到P2必须一天内上链，超过这个时间Ticket就会过期，重新获取从P1开始做任务，但是这个过期是从PC2完成后准备上链时判断的，能不能在领取P2任务时直接判断这个任务是否过期了,如果过期就直接把状态改为SealPreCommit2Failed；同样大量的P1任务可以在领取前判断是否过期，最好是不领取就可以判断

**Comment by diwufeiwen** [comment]
在handlePreCommit2里最先判断ticket,一旦过期时状态机变化:
->PreCommit2->GetTicket->PreCommit1->PreCommit2->...

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus-sealer/pull/152
