### ISSUE TITLE
venus-market配置gateway作为signer

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4615]
配置的token权限为'sign'
./venus-market storage-deals set-ask --miner=t01006 --price=0.02fil --verified-price=0.01fil --min-piece-size=512b --max-piece-size=8M --miner=t01006
/Users/zl/.venusmarket
2021/12/10 18:46:12 miner t01006 sign data failed: missing permission to invoke 'WalletSign' (need 'admin')

需测试，签名需要admin权限? 配置sign权限报需要admin。

**Comment by zl03jsj** [comment]
检查了一下,是gateway特意改成的admin, 后面为venus-market都配置admin的权限就可以了.
