### ISSUE TITLE
venus节点链同步问题

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4617]
unexpected error processing batch proof verifies: batch verify seals syscall implemented incorrectly, result not found for miner: %!s(PANIC=String method: unknown address protocol). Skipping all verification for epoch 1335420

**Comment by zl03jsj** [comment]
#4555 可以先使用这个版本.

**Comment by Fatman13** [comment]
@zl03jsj 这个讨论结果怎么样？

**Comment by zl03jsj** [comment]
> @zl03jsj 这个讨论结果怎么样？
目前是一个临时方案, 已经合并到master, 有这个问题的, 可以用最新的master版本.
