### ISSUE TITLE
venusmarket Config参数配置项不起作用

### ISSUE THREAD

**Issue by ly82505129** [filecoin-project/venus#4627]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to venus.

### Venus component

- [ ] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [X] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
在.venusmarket/ 目录下的config.toml配置文件中的SimultaneousTransfers参数修改后不起作用。

在之前ops同时传输文件超过20个时，data-transfers同时传输数是20个，我去config配置文件中看到该SimultaneousTransfers参数项值为20，我想通过修改该参数来达到提升单个文件的传输效率，每完成一个即可去提交一次封装。

但是在修改SimultaneousTransfers=1 之后，重启venus-market之后，依然没有达到想要的效果，依然同时传输20个
```

### Describe the Bug

修改SimultaneousTransfers=1 之后该参数控制项未起作用

### Logging Information

```text
重启venus-market之后，依然没有达到想要的效果，依然同时传输20个
```

### Repo Steps

1. vi config.toml
2. i 
3. 修改SimultaneousTransfers=1
4. esc
5. :wq
6. kill -9 <venus-makret进程id>
7. ./venus-market run

**Comment by zl03jsj** [comment]
@Fatman13 @ly82505129 

我们经过对代码进行详细的分析, 并且通过测试和验证,结论是SimultaneousTransfers这个参数在 venus-market [upgrate/nv15](https://github.com/filecoin-project/venus-market/tree/upgrade/nv15) 分支是有效果的.

## 分析如下:
这个参数在venus-market 创建graghsync 实例时, 作为graphsync的一个option传入, 代码位置:
https://github.com/filecoin-project/venus-market/blob/1af26297b00bebc47337f78cf6e8d930c7beb6dd/network/graphsync.go#L27-L60

graphsync会在创建实例对象时, 启动一个taskQueue,来处理request的任务.(market请求数据的任务), 代码位置:
https://github.com/ipfs/go-graphsync/blob/4f4414d6badd10e187bdd0517c63f40e34c14d01/impl/graphsync.go#L295-L297

最后这个requestQueue启动时, 会根据指定的SimultaneousTransfers数量来创建并发worker, 代码位置:
https://github.com/ipfs/go-graphsync/blob/4f4414d6badd10e187bdd0517c63f40e34c14d01/taskqueue/taskqueue.go#L95-L99

每个worker会定时查询是否有任务, 每次找出一个传输任务, 然后执行:executor.ExecuteTask, 执行完成以后再执行下一个, 代码位置:
https://github.com/ipfs/go-graphsync/blob/4f4414d6badd10e187bdd0517c63f40e34c14d01/taskqueue/taskqueue.go#L114-L151
从代码层面看, 这样的处理逻辑是没有问题的. 

到这里, 唯一需要验证的问题是, ExecuteTask是一个异步的任务, 由于内部代码非常复杂, 通过查看代码不太容易分析,
我们为了验证, 我们在work执行任务时打出了一些日志, 通过分析日志来做出验证, 从market-client端发起一个存储任务后, 
在venus-market端查看日志:
![image](https://user-images.githubusercontent.com/10127848/149131971-ea2cd523-bb41-4f07-a772-374b12f6c667.png)
可以证明, taskQueue是数据传输完成之后, 再执行的下一个任务.

这边的分析得出的结论就是这样, 
你可以考虑使用upgrate/nv15这个分支再观察一下.

**Comment by ly82505129** [comment]
> 

我想通过该参数控制同时data-transfers的数量，但是未生效，我不确定是否由这个参数来控制同时传输任务的数量

**Comment by zl03jsj** [comment]
> > 
> 
> 我想通过该参数控制同时data-transfers的数量，但是未生效，我不确定是否由这个参数来控制同时传输任务的数量

是这个参数.

**Comment by Fatman13** [comment]
还有问题的话，可以reopen。
