### ISSUE TITLE
market v2 部署到`Calibration`网络

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4650]

**Comment by linjun826668** [comment]
help

**Comment by Joss-Hua** [comment]
> help

How can we help you?

**Comment by Fatman13** [comment]
@renran 部署进度还行？

**Comment by cloudxin** [comment]
可以先参考这个文档，细节功能还在更新过程中
[docs/zh/guide/Using-venus-market.md](https://github.com/filecoin-project/venus-docs/blob/master/docs/zh/guide/using-venus-market-for-miner.md)

**Comment by Fatman13** [comment]
完成calib网络部署。@cloudxin
