### ISSUE TITLE
社区众测`calibration`网络上的market v2

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4651]
@cloudxin已在`Calibration`网络上的链服务中部署完成market v2版本，对venus-market v2感兴趣的社区朋友们都能来测试market v2版本。

~~market v2 文档：https://github.com/filecoin-project/venus-docs/blob/f9246a8f0c56c1e85b11bf95aec50b9ef7565f21/docs/zh/guide/Using-venus-market.md~~

venus market v2 测试文档：https://github.com/filecoin-project/venus/discussions/4735

需要calib网络链服务的测试token和url的朋友可以咨询@cloudxin获取。Slack上他是@venus-ops。

**Comment by Joss-Hua** [comment]
Coolman 期待尽快把它同步到 https://venus.filecoin.io/modules

**Comment by Fatman13** [comment]
欢迎社区朋友持续测试。
