### ISSUE TITLE
market v1最新master和sealer兼容问题？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4760]
原文: @seantw

market最新master

venus-sealer --version
venus-sealer version 1.3.4-rc1+git.ac46dfb.dirty

venus-wallet --version
venus remote-wallet version 1.3.0'+gitbfa623c'

出現了 stat異常

error getting ~/.venusmarket info: stat ~/.venusmarket: no such file or directory

stat ~/.venusmarket
  File: /root/.venusmarket -> /raid03/.venusmarket/
  Size: 21        	Blocks: 0          IO Block: 4096   symbolic link
Device: 802h/2050d	Inode: 16150322    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-02-10 22:43:03.731640987 +0800
Modify: 2021-12-29 14:07:21.252236958 +0800
Change: 2022-02-10 22:42:56.891650734

**Comment by cloudxin** [comment]
在calibnet的V15网络上，用**venus-sealer version 1.4.0-rc5+git.1ddbde5**和**venus-market v2.0.0-rc3 5ea3e7f**版本是没有问题的

**Comment by cloudxin** [comment]
venus-sealer的配置文件中，确保有以下配置：
```bash
[MarketNode]
  Url = "/ip4/127.0.0.1/tcp/41235"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJu"

[PieceStorage]
  [PieceStorage.Fs]
    Enable = true
    Path = "/filestore"    //对应venus-market上的PieceStorage路径
  [PieceStorage.S3]
    Enable = false
    EndPoint = ""
    AccessKey = ""
    SecretKey = ""
    Token = ""
```

**Comment by Fatman13** [comment]
@cloudxin 这个问题解决了？

**Comment by cloudxin** [comment]
本来就问题，主要是因为版本在升级过程中一些配置的变更导致启动market报错
