### ISSUE TITLE
建议：文档添加daemon自定义链存放路径？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4763]
原文：https://filecoinproject.slack.com/archives/C028PCH8L31/p1644565115401619

**Comment by Imccccc** [comment]
venus模块操作命令过少，也缺少
1. 镜像导出
2. 清理badger
3. 优雅退出/重启venus进程
4. set-head的操作说明

**Comment by Fatman13** [comment]
@zl03jsj 亮兄，snapshot导出/制作是不是一直没有？

**Comment by Fatman13** [comment]
@Imccccc 感谢反馈！

镜像导出命令有占用内存过大的一个问题，目前还在解决中。

清理badger具体是指？

优雅退出现在支持 kill，不用 kill -9，但是命令行还没有，是指需要命令行吗？

set-head的操作说明是指 -help 里面需要文字说明吗？

**Comment by Imccccc** [comment]
1. 目前venus模块导出镜像没有标准命令哈。然后我自己使用venus 1.2.2+git.82860af11，发现导出的镜像无法导入，我已经在社区反馈了
2. 现在清理.venus/badger，不都是使用mv模块么，我在想如果是带import-snapshot命令，是不是就暗指清理模块？
3. 现在退出venus模块只需要 kill <pid>可以实现了么？我还没有尝试过
4. set-head 当前我没有找到什么文档，目前都是我自己在文档记录的（slack频道的聊天记录）

**Comment by Fatman13** [comment]
@Imccccc 兄弟你slack上是 @Lehoom 还是 @ovy ？

**Comment by Imccccc** [comment]
@Fatman13 我是tyler呀

**Comment by Fatman13** [comment]
@Imccccc 哦哦哦，哈哈哈。👍
