### ISSUE TITLE
建議:增加查詢(監控)扇區健康狀況功能

### ISSUE THREAD

**Issue by seantw1974** [filecoin-project/venus#4764]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is, please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [X] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

由於venus(lotus)的 terminate/remove機制,常讓人混亂,或是發生有上鏈但無terminate成功狀況, 造成存儲提供者誤以為己成功刪除,但在某個時間點卻被罰款的問題

### Describe the solution you'd like

讓存儲提供者能明白確認某些扇區是否成功刪除,或終止,以避免被罰款

### Describe alternatives you've considered

建議在查詢扇區功能新增,查詢扇區失效的功能,扇區在N小時內,無成功上鏈的SectorID 查詢
即將被罰款的SectorID查詢

### Additional context

none

**Comment by Fatman13** [comment]
在 https://github.com/filecoin-project/venus/discussions/4791 进行日常运维需求的统一追踪。后期可能考虑使用类似lotus-shed一样的命令集。
