### ISSUE TITLE
建議: venus-messager鏈上同步修正

### ISSUE THREAD

**Issue by seantw1974** [filecoin-project/venus#4771]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [X] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### Improvement Suggestion

venus-sealer在切換不同,venus服務鏈(連到不同服務商/服務鏈), 之前的做的sectors狀態無法同步到新的服務鏈上(指的是即便主鏈上已更新後,仍無法修改本地sectors狀態)
目前發現Sectors處於CommitWait或PreCommitWait時, 切換過新的服務鏈後, 狀態無法Sync
venus-sealer只會與venus-messager對話, 無法更新為鏈上最新狀態
建議venus-messager在發現"不存在"的id時, 能進一步在鏈上確認狀態, 這樣venus-sealer才能正確的同步成"鏈上"最新狀態

**Comment by Fatman13** [comment]
在 https://github.com/filecoin-project/venus/discussions/4791 进行日常运维需求的统一追踪。
