### ISSUE TITLE
cc扇区可跳过AP阶段，默认的unsealed文件生成

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#4827]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is, please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

1. cc扇区的ap阶段生成的文件是相同的，故可以预生成；
2. cc扇区跳过ap阶段，用预生成的unsealed文件

### Describe the solution you'd like

使用预生成的unsealed文件及pieces info

**Comment by diwufeiwen** [comment]
https://github.com/ipfs-force-community/venus-cluster/pull/66

**Comment by Fatman13** [comment]
66666
