### ISSUE TITLE
【venus-market]在检索传输中某些状态无法cancel掉，必须重启才行。

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#4851]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to venus.

### Venus component

- [ ] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [X] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
latest
```

### Describe the Bug

检索中间某些状态（SendFunds）中如果出错或者停止之后，无法cancel掉这个检索

### Logging Information

```text
no
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by YiRuiLiher** [comment]
1. 当检索一个订单失败的情况下，再次检索其他订单会遇到报错
2. 因为前一个卡在那失败了
3. 此时只能cancel掉前一个检索的任务，但是似乎没有反应

**Comment by zl03jsj** [comment]
根据issue的描述, 进行操作, 可以`cancel`掉任何状态的检索订单.

操作步骤如下:
1. 命令行开始检索数据:
```shell
./market-client retrieval retrieve --provider=f01237 --maxPrice=20fil bafykbzacea6rn5yn566ajxmwyrrwrljoddzkabvf7ohe677rfiync4qitsqny ./bafykbzacea6rn5yn566ajxmwyrrwrljoddzkabvf7ohe677rfiync4qitsqny
Recv 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew), 1ms
....
Recv 0 B, Paid 0 FIL, ClientEventPaymentChannelAddingFunds (DealStatusPaymentChannelAddingInitialFunds), 199ms
.....
Recv 25.01 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds), 1m32.272s
```

2. 观察命令行输出, 待检索订单状态进入:`DealStatusSendFunds`是, 按下`Ctl+c`终止订单.此时命令行退出,并打印提示:
```shell
Recv 25.01 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds), 1m32.272s
^C2022-05-31T14:45:10.539+0800  FATAL   main    market-client/main.go:128       retrieval timed out
```
3. 此时订单状态应该在`DealStatusSendFunds`, 通过命令行查看状态:
```shell
 ./market-client retrieval list-retrievals 
PayloadCID   DealId               Provider     Status               PricePerByte              Received  TotalPaid                 
...4qitsqny  1653978406042704025  ...bb4HMWsY  DealStatusSendFunds  0.000000000000009313 FIL  25.01MiB  0 FIL      
```
4. 再次执行检索, 提示有一个正在进行中的订单, 请先`cancel`掉.   
```shell
./market-client retrieval retrieve --provider=f01237 --maxPrice=20fil bafykbzacea6rn5yn566ajxmwyrrwrljoddzkabvf7ohe677rfiync4qitsqny ./bafykbzacea6rn5yn566ajxmwyrrwrljoddzkabvf7ohe677rfiync4qitsqny
2022-05-31T14:45:47.591+0800    FATAL   main    market-client/main.go:128       error setting up retrieval: retrieve failed: there is an active retrieval deal with peer 12D3KooWAK8pXmRzbbRjFpknnUyFie4TkjEB4CHUwUKAbb4HMWsY for payload CID bafykbzacea6rn5yn566ajxmwyrrwrljoddzkabvf7ohe677rfiync4qitsqny (retrieval deal ID 1653978406042704025, state DealStatusSendFunds) - existing deal must be cancelled before starting a new retrieval deal
```
5. 执行`cancel`命令:
```shell
./market-client retrieval cancel-retrieval --deal-id 1653978406042704025            
```
6. 等待一段时间后, 执行再次查看订单状态
```shell
./market-client retrieval list-retrievals
PayloadCID   DealId               Provider     Status               PricePerByte              Received  TotalPaid                 
...4qitsqny  1653978406042704025  ...bb4HMWsY  DealStatusCancelled  0.000000000000009313 FIL  25.01MiB  0 FIL                     
  Message: Client cancelled retrieval
  ```
7. 再次执行检索命令, 可以正常执行.

关于 @YiRuiLiher  提出的:
> 当检索一个订单失败的情况下，再次检索其他订单会遇到报错.
可以理解为, **设计如此**

至于 @hunjixin  提出的无法`cancel`的情况, 
经过**多种**中间状态验证, 均可以通过`cancel-retrieval`命令正常退出.  中间的某些状态退出时, 可能需要等待**1分钟**左右时间.

**如再有关于此issue的问题, 请补充完整的重现步骤.**

**Comment by zl03jsj** [comment]
这里对 @YiRuiLiher  提到的:
> 当检索一个订单失败的情况下，再次检索其他订单会遇到报错.

再次解释,  market-client设计为, 同时只能进行一个订单的检索, 当一个订单还未`退出`时, 无法开启其它的检索订单.

**Comment by zl03jsj** [comment]
这个issue, 是一个不存在的issue, 先关掉了.
