### ISSUE TITLE
venus-auth token和user 软删除

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4867]
支持 token 和 user 的软删除

- token 表和 user 表新增字段 is_deleted (0 表示未删除，1 表示已删除)
- 在删除用户时，需要删除用户下面的所有miner
- 命令行调整
  - 增加查询token信息命令：./venus-auth token get --name or --token，可以token名和token本身来查询
  - 增加删除用户命令：./venus-auth user delete <user-name>，根据用户名来删除
  - 增加恢复用户和token命令：./venus-auth user recover <user-name>  ./venus-auth token recover <token> 

分支：feat/cmds_and_soft_deleteion

**Comment by simlecode** [comment]
https://github.com/filecoin-project/venus-auth/pull/64
