### ISSUE TITLE
[venus-gateway] 把客户端实现的核心逻辑移动到gateway项目中，通过一些抽象接口注入到统一的实现里面。

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#4894]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [X] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [ ] venus sealer/worker - sealing
- [X] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### Improvement Suggestion

 现在客户端实现独立实现在wallet和sealer中，这样其中有一些约定的地方，要求双方都知道。这样存在一些风险。这里考虑把gateway client中核心的约定的部分统一实现在gateway里面。

### Sub tasks
[草稿]
#### 前置准备工作, 整理gateway:
- [x] 去掉`gateway`中, 与`venus-shared`中的重复的定义的部分.直接引用`venu-shared`.
https://github.com/ipfs-force-community/venus-gateway/blob/822654511cf3eba45031648a811506df7e13ed5e/walletevent/api.go#L12-L26
使用`venus-shared`中的定义和实现来代替:
https://github.com/filecoin-project/venus/blob/15088ed7ba1169b1284ecb5e67bc49770bd9f75c/venus-shared/api/gateway/v1/market_event.go#L14-L28
- [x] #5195
- [x] 整理`venus-wallet`, 使用venus-gateway中的相关实现.(filecoin-project/venus-wallet/pull/98)
- [x] #5210

**Comment by zl03jsj** [comment]
[草稿]计划先对gateway进行整理.
- [ ] 先检查一些重复的定义, 统一使用venus-shared中的定义, 例如, 在gateway中应该去掉:
https://github.com/ipfs-force-community/venus-gateway/blob/822654511cf3eba45031648a811506df7e13ed5e/walletevent/api.go#L12-L26
使用`venus-shared`中的定义和实现来代替:
https://github.com/filecoin-project/venus/blob/15088ed7ba1169b1284ecb5e67bc49770bd9f75c/venus-shared/api/gateway/v1/market_event.go#L14-L28
