### ISSUE TITLE
[venus-miner] Create block write database information is incomplete

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#4919]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is, please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [X] venus miner - [chain service] mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Currently, miner is inserting into the database, and the display information is incomplete
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/43364105/173287383-5d6e52f5-b1eb-4406-91e9-41543de1d89f.png">

### Describe the solution you'd like

When writing miner data to the database, you need to add a **user name**, record **winnerCount time**, and **response time** after post calculation. If post does not return results, the response time is blank.  Record the height of all winner count, including the information that no post result is received.

**Comment by diwufeiwen** [comment]
新增 winning_at(程序中获得出块权时的时间), proof_consuming（计算获胜证明耗时)，mine_state（0-计算证明中，1-成功出块，2- 出错，包括timeout）  逻辑改动： 1.获得区块权时插入一条记录，cid和proof_consuming为空； 2. 成功出块更新cid和proof_consuming，mine_satte； 3. 超时或出错仅更新mine_state
