### ISSUE TITLE
[venus] use too much memory when export snapshot

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#4922]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to venus.

### Venus component

- [X] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
venus version
{
	"Version": "1.2.4+git.135232873.dirty"
}
```

### Describe the Bug

./venus chain export --recent-stateroots=920 --skip-old-msgs snapshot.car

### Logging Information

```text
Exporting snapshot files takes too long and takes up a lot of memory. 128G systems have memory overflow problems.
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by hunjixin** [comment]
@cloudxin  导出内存还是比lotus多？

**Comment by hunjixin** [comment]
目前方案lotus和venus都很多。继续追踪这个issue意义不大。先重启解决吧，或者以后看看能不能通过https://github.com/filecoin-project/venus/issues/5182解决
