### ISSUE TITLE
venus-market订单状态异常

### ISSUE THREAD

**Issue by caijian76** [filecoin-project/venus#4943]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to venus.

### Venus component

- [ ] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [X] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
venus-market version venus-market v2.0.0
```

### Describe the Bug

封装完订单过了1天后（snapup方法），storage-deals list查看订单状态，依旧是Proving ，而不是Assigned ，用market-client查看订单状态，是StorageDealAwaitingPreCommit，而不是StorageDealActive 。我确认订单已经上链了。

### Logging Information

```text
venus-market storage-deals list
...2stxykae  7242221  StorageDealActive     Proving     t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  64GiB  0 FIL  866397
...i64g5rou  7253020  StorageDealActive     Proving     t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  64GiB  0 FIL  1027197


root@work10:~# market-client  storage deals list
DealCid      DealId   Provider   State                         On Chain?          Slashed?  PieceCID     Size       Price  Duration  Verified  
...cliw5ohm  4732745  t01212159  StorageDealActive             Y (epoch 1654059)  N         ...jgqgn6fa  63.5 GiB   0 FIL  1527581   true      
...4kgh5yxy  5094019  t01212159  StorageDealActive             Y (epoch 1682093)  N         ...6brmwmhy  31.75 GiB  0 FIL  1442838   true      
...2stxykae  7242221  t01212159  StorageDealAwaitingPreCommit  Y (epoch 1902527)  N         ...5ri7c2da  63.5 GiB   0 FIL  866397    true      
...i64g5rou  7253020  t01212159  StorageDealAwaitingPreCommit  Y (epoch 1902774)  N         ...zxvxh6oy  63.5 GiB   0 FIL  1027197   true
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by zl03jsj** [comment]
先简单回复一下: @caijian76 
关于`PieceState`部分:
>  封装完订单过了1天后（snapup方法），storage-deals list查看订单状态，依旧是Proving ，而不是Assigned

`Proving` 是订单的piecestate的一种状态, `piecestate`的顺序依次为:
1. `Undefine`: 还未关联到任何`Sector` 
2. `Assigned`: 已经被选中到某个`Sector`
3. `Packing`: `Sector`正在add package中.
4. `Proving`: 已经封装完成.

所以, 看到的这个状态`Proving`状态是正确的. 

至于后面`market-client`查看订单状态, 的确不应该为`StorageDealAwaitingPreCommit`, 后续我们会对此进行确认.

**Comment by caijian76** [comment]
我是基于原来采用venus-sealer在线订单封装（非snapup模式），和现在使用snapup模式封装的扇区比较，以为完成的正常状态是Assigned。

root@work10:/mnt/data/tmpdir/64G# venus-market  storage-deals list
/root/.venusmarket
ProposalCid  DealId   State                 PieceState  Client                                                                                  Provider   Size   Price  Duration
...mwodo72e  0        StorageDealRejecting              t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  64GiB  0 FIL  1556394
...cliw5ohm  4732745  StorageDealActive     Assigned    t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  64GiB  0 FIL  1527581
...ektskskm  0        StorageDealRejecting              t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  32GiB  0 FIL  1558042
...4kgh5yxy  5094019  StorageDealActive     Assigned    t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  32GiB  0 FIL  1442838
...2stxykae  7242221  StorageDealActive     Proving     t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  64GiB  0 FIL  866397
...i64g5rou  7253020  StorageDealActive     Proving     t3wzid6h2dv5osdmvvvcyxezgupytsiqgdwxcmucr7yclylogw36xrma23qc57ogi65udaylimt7bmbpdr2daa  t01212159  64GiB  0 FIL  1027197

root@work10:/mnt/data/tmpdir/64G# market-client storage deals list
DealCid      DealId   Provider   State                         On Chain?          Slashed?  PieceCID     Size       Price  Duration  Verified  
...cliw5ohm  4732745  t01212159  StorageDealActive             Y (epoch 1654059)  N         ...jgqgn6fa  63.5 GiB   0 FIL  1527581   true      
...4kgh5yxy  5094019  t01212159  StorageDealActive             Y (epoch 1682093)  N         ...6brmwmhy  31.75 GiB  0 FIL  1442838   true      
...2stxykae  7242221  t01212159  StorageDealAwaitingPreCommit  Y (epoch 1902527)  N         ...5ri7c2da  63.5 GiB   0 FIL  866397    true      
...i64g5rou  7253020  t01212159  StorageDealAwaitingPreCommit  Y (epoch 1902774)  N         ...zxvxh6oy  63.5 GiB   0 FIL  1027197   true

**Comment by Fatman13** [comment]
proving意思应该是这些扇区需要每天做windowPost去证明他的意思。所以是proving。

**Comment by LinZexiao** [comment]
market client 在订单 snapup 的过程中 确实会出现不能正确识别订单状态的情况，原因是在client状态机中，尚需增加对snapup 的支持（此前是通过识别 precommit 的信息来进行状态跳转。

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/go-fil-markets/issues/737

**Comment by zl03jsj** [comment]
Since this issue was blocked for a long time. I prefer to close it now.

**Comment by Fatman13** [comment]
没有实现的话，用“close as not planned”。[doge]

**Comment by zl03jsj** [comment]
> 没有实现的话，用“close as not planned”。[doge]
噢啦.
