### ISSUE TITLE
Write a short flow for 1 behavior

### ISSUE THREAD

**Issue by KatarinaKeti** [filecoin-project/venus#4955]
_YAML catalog, annotations in the test file, running crawler and so on_

**Comment by hunjixin** [comment]
is this a ci or something else?

**Comment by Fatman13** [comment]
YAML catalog 类似BDD中，用语言描述的一个场景。
Annotation 到时候代码里面需要注释，yaml中描述场景对应的代码
crawler，最终跑所有的测试。

不过这个好像是目标，就是先跑通一个case的目标？好像是。
