### ISSUE TITLE
[建议] REPO dir 环境变量名称和 CLI 参数名称保持一致

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4964]
需求：[来源](https://filecoinproject.slack.com/archives/C028PCH8L31/p1655955645249479?thread_ts=1655950008.165519&cid=C028PCH8L31)

目前状态：https://github.com/filecoin-project/venus/pull/4863

- 当前VENIS_PATH环境变量保留，保持兼容性。
- 定义新的环境变量参数的名称和CLI命令行中的参数名称相同。
- 另外，针对@cloudxin提出的这个[问题](https://filecoinproject.slack.com/archives/C028PCH8L31/p1655956903766039?thread_ts=1655950008.165519&cid=C028PCH8L31)，建议用户没有给出`.venus`的路径时，自动生成这个路径。
- 下个sprint可以考虑。

**Comment by LinZexiao** [comment]
各个repo 默认的名称是不是事实也可以统一一下？

**Comment by Fatman13** [comment]
有道理。👍

**Comment by simlecode** [comment]
各组件统一 repo path 的flag为 `--repo`
