### ISSUE TITLE
[venus-market] 调研https://github.com/filecoin-project/go-fil-commp-hashhash库

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#4968]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [X] venus market - storage deal
- [X] venus market - retrieval deal
- [X] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### Improvement Suggestion

调研https://github.com/filecoin-project/go-fil-commp-hashhash库，这个库提供了纯go代码实现的计算commp的方法，使用该库可能可以移除filecoin-ffi库，简化代码编译，加快ci速度。

**Comment by zl03jsj** [comment]
暂时无法移除, `venus-market`**必须**依赖`go-fil-market`, `go-fil-market`中包含多ffi的引用.
