### ISSUE TITLE
[venus-market] 支持SP主动取消检索

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4969]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Venus component

- [ ] venus daemon - [chain service] chain sync
- [ ] venus auth - [chain service] authentication
- [ ] venus messager - [chain service] message management (mpool)
- [ ] venus gateway - [chain service] gateway
- [ ] venus miner - [chain service] mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving (WindowPoSt)
- [ ] venus market - storage deal
- [X] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] Other

### Improvement Suggestion

是否可以考虑支持SP主动取消检索？参考：https://github.com/filecoin-project/lotus/pull/8912

或者放在vsm？https://github.com/ipfs-force-community/venus-cluster/issues/283

**Comment by zl03jsj** [comment]
https://github.com/filecoin-project/venus-market/pull/135
已经此这个pr中修复过了.

**Comment by Fatman13** [comment]
fixed by https://github.com/filecoin-project/venus-market/pull/135
