### ISSUE TITLE
[venus] 统一命令行中所有网络名

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5001]

**Comment by hunjixin** [comment]
网络名：
主网：mainnet
cali: cali/calib/calibnet/calibration
2k:

**Comment by LinZexiao** [comment]
统一网络名称参考：
mainnet
cali
force
butterfly
2k
interop
integrationnet

**Comment by LinZexiao** [comment]
目前需要网络名称作为参数的组件有：venus，cluster和wallet，（sealer和woker没有考察）
其中venus和cluster 是一致的，只需要适配wallet的即可
