### ISSUE TITLE
[venus] 收到区块慢相对于louts普遍慢一秒左右

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5008]
* [增加peer评分机制](https://github.com/filecoin-project/venus/pull/5099)

经排查，venus 在 pubsub 层收到区块就比 lotus 慢，可以排除 pubsub 层以上代码的影响，后续可以对考虑连接的 peer 和 libp2p 进行研究

代码层面对比：

1. 都有 ConnectionManager，参数也相差不大
2. lotus 有 peer score管理，venus 加上也并没有明显改善收到区块慢的情况

**Comment by simlecode** [comment]
![image](https://user-images.githubusercontent.com/69969590/190337522-22b81532-9073-48a1-97da-95de25d50414.png)
上图是用 chain-co 来连接venus和lotus，再通过比较head的变化来对比收到区块的时间，相同高度等head稳定所花时间相差不大

**Comment by YiRuiLiher** [comment]
1
