### ISSUE TITLE
Venus Market文档过期

### ISSUE THREAD

**Issue by Imccccc** [filecoin-project/venus#5018]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to venus.

### Venus component

- [ ] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [X] venus market - storage deal
- [X] venus market - retrieval deal
- [X] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
./venus-market --version
venus-market version venus-market v2.2.0-rc1
```

### Describe the Bug

venus market当前配置文档看起来已经过时，目前配置fs的配置样例是错误的
参考文档[venus-订单服务](https://venus.filecoin.io/zh/market/using-venus-market-for-miner.html#venus-market-v2-miner%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97)

### 配置文件
在.venusmarket/config.toml配置 pieceStorage如下
`[PieceStorage]
  [PieceStorage.Fs]
    Enable = true
    Path = "/storage/market-store"`

日志信息
```bash
./venus-market solo-run
2022/07/03 21:46:20 toml: cannot load TOML value of type map[string]interface {} into a Go slice
```

### 启动命令
```bash
./venus-market solo-run --node-url /ip4/127.0.0.1/tcp/3453 --node-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY2FsaWIiLCJwZXJtIjoic2lnbiIsImV4dCI6IiJ9.7ZKqQniulXFzIo1AQ0WETq64Ifey54HDh1UQGjy37oM --wallet-url /ip4/127.0.0.1/tcp/5678/http --wallet-token 65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a42624778766479493657794a795a57466b4969776964334a70644755694c434a7a615764754969776959575274615734695858302e51656b6453593233794f6451725365464870316138546e5379306262717a4d4d7958736269374f42767551  --payment-addr t1akdud3jmg7356aenzngmafxcnvq2ge3lejap5ia --piecestorage=fs:/storage/market-store --miner=t037496:calib
```
报错信息
``` bash
Incorrect Usage: flag provided but not defined: -piecestorage

NAME:
   venus-market solo-run - Run the market daemon in solo mode

USAGE:
   venus-market solo-run [command options] [minerAddress]

OPTIONS:
   --node-url value                            url to connect to daemon service
   --node-token value                          node token
   --wallet-url value, --signer-url value      used to connect signer wallet for sign
   --wallet-token value, --signer-token value  auth token for connect wallet service
   --mysql-dsn value                           mysql connection string
   --miner value                               support miner(f01000:jimmy) (default: "t037496")
   --payment-addr value                        payment address for receive retrieval address
   --help, -h                                  show help (default: false)

2022/07/03 21:58:45 flag provided but not defined: -piecestorage
```

### Logging Information

```text
参考以上
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Imccccc** [comment]
正确的配置方式应该是
```
[PieceStorage]
  [[PieceStorage.Fs]]
    Enable = true
    Path = "/filestore"
  [[PieceStorage.S3]]
    Enable = false
    EndPoint = ""
    AccessKey = ""
    SecretKey = ""
    Token = ""
```

**Comment by Imccccc** [comment]
同时确实Venus Cluster接入Market的文档说明

**Comment by LinZexiao** [comment]
新增了name 属性：

[PieceStorage]
  [[PieceStorage.Fs]]
    Name = "UniqueName"
    Enable = true
    Path = "/filestore"
  [[PieceStorage.S3]]
    Name = "UniqueName"
    Enable = false
    EndPoint = ""
    AccessKey = ""
    SecretKey = ""
    Token = ""

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/issues/5055
