### ISSUE TITLE
[venus-market] 初始化未完成时重新初始化，[[StorageMiners]]配置项重复

### ISSUE THREAD

**Issue by alisazhang777** [filecoin-project/venus#5022]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to venus.

### Venus component

- [ ] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [X] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
venus-market：version：v2.2.0 CommitId: 27ca416
```

### Describe the Bug

首次初始化时 node-url机器IP配置错误：./venus-market pool-run --node-url /ip4/192.168.200.15/tcp/3453/ --node-token XXX --auth-url http://XXX:8989 --auth-token XXX --messager-url /ip4/XXX/tcp/39812 --gateway-url /ip4/192.168.200.132/tcp/45132 --gateway-token XXX --miner f037158
生成.venusmarket repo文件；然后更改node-url为正确的IP，再次重启。发现[[StorageMiners]]配置项重复
[[StorageMiners]]
  Addr = "t037158"
  Account = ""

[[StorageMiners]]
  Addr = "t037158"
  Account = ""

### Logging Information

```text
[[StorageMiners]]
  Addr = "t037158"
  Account = ""

[[StorageMiners]]
  Addr = "t037158"
  Account = ""
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by diwufeiwen** [comment]
这个的解决思路在终止初始化命令失败时，删除掉创建的repo，执行init前先检查repo是否存在，存在则命令执行报错
