### ISSUE TITLE
venus-market 初始化时, 将piecestore(或者其它)比较复杂的配置以注释方式输出到配置文件中.

### ISSUE THREAD

**Issue by zl03jsj** [filecoin-project/venus#5036]
### Venus component
- [x] venus market

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

对于这些比较复杂的类型, 如果没有样例, 的确很难编写其配置.

### Describe the solution you'd like

初始化时, 将这一部分复杂的配置写入到配置文件的注释中, 后续就可以参考注释来提供对应的配置方式.

### Describe alternatives you've considered

none

### Additional context

none

**Comment by LinZexiao** [comment]
另见 https://github.com/filecoin-project/venus/issues/4906

**Comment by LinZexiao** [comment]
目前，我们当前使用的toml编码库 https://github.com/BurntSushi/toml 暂时还不支持插入注释这一的特性
另外 配置文档也从另一个维度解决了这个问题。
