### ISSUE TITLE
Same comment in dispatcher.go

### ISSUE THREAD

**Issue by StefanGajic** [filecoin-project/venus#5037]
I have found the same comment in pkg> chainsync> dispatcher> dispatcher.go
Method `SyncTracker` and method `SendOwnBlock` have same comment which is `// SendOwnBlock handles chain info from a node's own mining system`

**Comment by Fatman13** [comment]
Thanks for the catch! Will take this to the team!

@zl03jsj 亮兄，这个STM团队发现的这个2个函数好像使用了相同的注释。
