### ISSUE TITLE
[venus-messager] 发布 v1.6.1 版本

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5038]
## 背景

需求[原文](https://filecoinproject.slack.com/archives/C028PCH8L31/p1657156996040919)

## 需求

缓解nv16 ， gas高，消息堵塞问题。预计nv17，gas还会有调整。

- 这个env的名称是不是可以优化一下？VENUS_MESSENGER_GAS_PREMIUM_OVER_RAGE ？
- msg replace 添加 `--auto` 选项？
- 其他待讨论？

## 关联issue

- [ ] https://github.com/filecoin-project/venus/issues/5039

**Comment by hunjixin** [comment]
发布新版本，更新lotus/venus/messager/cluster. 支持premium设置

**Comment by Fatman13** [comment]
venus和cluster也要对应一起升级？
