### ISSUE TITLE
Create the rough division for the other repos (wallet, auth, etc.)

### ISSUE THREAD

**Issue by KatarinaKeti** [filecoin-project/venus#5067]

**Comment by Fatman13** [comment]
@hunjixin Mike Li 大神，看看有空venus-auth和venus-wallet有空也整一个像上次venus一样的系统分类？

**Comment by Fatman13** [comment]
@ShuaoZhang 大神，这个也可以看看。

**Comment by Fatman13** [comment]
Sorry for the late reply! @KatarinaKeti 

For venus-auth, the only relevant system the team think is...

https://github.com/filecoin-project/venus-auth/tree/master/storage -> **Storage system**

It may be further divided into, user, storage and token subsystem.

**Comment by Fatman13** [comment]
@zl03jsj wallet的系统划分，也麻烦帮忙 @hunjixin 和 @ShuaoZhang 一起看看？

**Comment by Fatman13** [comment]
@ShuaoZhang 句芒大神，看看如果wallet系统分好了可以直接回答在这里。🤝

**Comment by ShuaoZhang** [comment]
Hi, here is a draft division of the wallet repo:

## venus-wallet subsystems

### api subsystem
 - ./venus-wallet/api/
 - ./venus-wallet/common/
### config subsystem
 - ./venus-wallet/config/
### data persistency subsystem
 - ./venus-wallet/storage/sqlite/
 - ./venus-wallet/filemgr
### private key management subsystem
 - ./venus-wallet/storage/wallet
### signature management subsystem
  - ./venus-wallet/storage/wallet/strategy
### encryption/decryption subsystem
 - ./venus-wallet/crypto/
 - ./venus-wallet/storage/keymix.go
### blockchain connection
 - ./venus-wallet/wallet_event

**Comment by Fatman13** [comment]
Remaining components:
- [ ] https://github.com/filecoin-project/venus/issues/5158

**Comment by Fatman13** [comment]
Systems of venus-gateway:

1. wallet_event
2. proof_event
3. market_event
4. validator
5. types
6. api

**Comment by Fatman13** [comment]
Systems of [venus-miner](https://github.com/filecoin-project/venus/issues/5158#issuecomment-1223569999)

#### API system
- ./api/client/client.go // for external rpc calls
- ./api/ // api services venus-miner exposes 
- ./node/impl // actual implementation of API services 
#### CLI system
- ./cli // cli utilities
- ./cmd // for daily  dev-ops
#### Monitor system
- ./lib/metrics  // Metrics related
- ./lib/tracing  
- ./lib/journal  // for collecting detail information on the status of block producing per SP
#### miner core logic
- ./miner
#### venus-miner configuration related implementation
- ./node/config
#### logics for interacting with `venus-auth`
- ./modules/miner-manager
#### Persistent system
- ./node/slashfilter  // status of each block during block producing 
#### Instance system
- ./node/repo

**Comment by Fatman13** [comment]
Hello, @KatarinaKeti @Kale98

I think Venus team has finished creating system for different Venus components. The list are...

[Venus](https://github.com/filecoin-project/venus/issues/5007#issuecomment-1171958431)
[venus-auth](https://github.com/filecoin-project/venus/issues/5067#issuecomment-1190966536)
[venus-miner](https://github.com/filecoin-project/venus/issues/5067#issuecomment-1223587040)
[venus-messager](https://github.com/filecoin-project/venus/issues/5068#issuecomment-1207944103)
[venus-gateway](https://github.com/filecoin-project/venus/issues/5067#issuecomment-1214757548)

[venus-wallet](https://github.com/filecoin-project/venus/issues/5067#issuecomment-1201893105)

Please feel free to let us know if there is anything else that you guys need from us. Thank you!
