### ISSUE TITLE
Design the catalogs of other repos (wallet, auth, etc.)

### ISSUE THREAD

**Issue by KatarinaKeti** [filecoin-project/venus#5068]

**Comment by KatarinaKeti** [comment]
auth is done.

**Comment by Kale98** [comment]
Venus-messenger is done.  @Fatman13

**Comment by Fatman13** [comment]
@hunjixin 大神，STM venus-messager 也做好了。

**Comment by Fatman13** [comment]
duplicated? 
- [ ] https://github.com/filecoin-project/venus/issues/5066

related:
- [ ] https://github.com/filecoin-project/venus/issues/5067#issuecomment-1223591992

**Comment by KatarinaKeti** [comment]
Currently working on _miner_.
