### ISSUE TITLE
[venus] 引入splitstore，自动prune链功能？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5073]
需求：[原文](https://filecoinproject.slack.com/archives/CR98WERRN/p1657675019268789?thread_ts=1657630397.094079&cid=CR98WERRN)

是否考虑引入lotus中splitstore相关功能，优化链管理的工作？现在好像看社区说lotus splitstore可以自动清理老的链，不用每次人工导入。

@simlecode 大神，现在venus是有相同类似的功能吗？

**Comment by diwufeiwen** [comment]
与https://github.com/filecoin-project/venus/issues/5182 重复，关闭

**Comment by Fatman13** [comment]
一些确定不做的，可以学习之前`cluster`用的，“close as not planned”，和直接close做一个区分。
![image](https://user-images.githubusercontent.com/1591330/187109380-c59b466b-0d4c-4206-8f36-ed09072fa3db.png)
