### ISSUE TITLE
各组件`--version` `version`命令统一？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5075]
是否可以考虑统 `一version` 命令为 `一version`？当前已知的是 `venus` 用的是 `venus version` 和其他组件不太一样。

**Comment by diwufeiwen** [comment]
# ./venus-miner version
Daemon:  1.6.0'+gitc21fc0c'+api1.2.0
Local: venus-miner version 1.6.0'+gitc21fc0c'
