### ISSUE TITLE
[venus-messager] RPC Error: wrong param count (method 'Filecoin.StateSearchMsg'): 4 != 1 日志修复？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5097]
需求：[原文](https://filecoinproject.slack.com/archives/C028PCH8L31/p1658114197212069?thread_ts=1658108976.394929&cid=C028PCH8L31)

> 2022-07-18T11:16:02.733+0800    ERROR   rpc     go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/server.go:107   RPC Error: wrong param count (method 'Filecoin.StateSearchMsg'): 4 != 1

> 这个是因为venus-messager连接过来使用默认v0版本导致的，修改.venus-messager/config.toml配置文件中连接节点信息就可以了
  url = "/ip4/192.168.xx.xx/tcp/3453/version/v1"

> 并不影响消息发送上链，只是日志中多出一个报错

如果确认不影响上链，建议修复日志？或者做一些处理？

**Comment by simlecode** [comment]
#5056
