### ISSUE TITLE
[STM] Evaluate venus system catalog

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5116]
https://github.com/filecoin-project/system-test-matrix 
branch: venus

**Comment by Fatman13** [comment]
@ShuaoZhang 可以尝试review看看bloxico的朋友怎么分venus的system和catalog的。

**Comment by Fatman13** [comment]
@hunjixin @ShuaoZhang 2位大神记得有空评估一下。

**Comment by hunjixin** [comment]
discovery包现在和network包合并了
