### ISSUE TITLE
[venus-market] track change of go-fil-market go-datatransfer v2

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5126]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [x] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

该版本在venus-market中产生大量变更，改变原来的状态机结构. 可能会产生兼容性问题

https://github.com/filecoin-project/go-fil-markets/pull/718

**Comment by Fatman13** [comment]
好像在之前 market 改造计划中没有包含。可能不重要？先关掉了。
