### ISSUE TITLE
[Venus] 各组件增加 Version 接口

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5132]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [X] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

各组件增加 `Version` 接口，方便查询正在使用的版本，参考 venus [Version](https://github.com/filecoin-project/venus/blob/master/venus-shared/api/chain/v1/network.go#L29) 接口

### TODO

* 在 `venus-shared` 中为需要的组件增加 `Version` 接口
* 各组件实现 `Version` 接口
  - [ ] venus-auth
    ```
    $ curl http://127.0.0.1:8989/version
    # res
    {"Version":"1.6.0+git.ebc4df8"}
    ```
  - [ ] venus-gateway
    ```
    $ curl http://127.0.0.1:45132/rpc/v0 -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <token>" -d '{"method": "Gateway.Version","params":[], "id": 0}'
    # res
    {"jsonrpc":"2.0","result":{"Version":"v1.6.1+git.3a51dc9","APIVersion":0},"id":0}
    ```
  - [ ] venus-market
  - [ ] venus-messager

**Comment by diwufeiwen** [comment]
curl http://127.0.0.1:12308/rpc/v0 -X POST -H "Content-Type: application/json"  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.JYefq1U7OoA5OrLGAxxQEo4y74wB_GIdL2rj6GK9SRQ"  -d '{"method": "Filecoin.Version","params":[], "id": 0}'
{"jsonrpc":"2.0","result":{"Version":"1.6.0'+gitc21fc0c'","APIVersion":66048},"id":0}
