### ISSUE TITLE
[集成] metrics可视化使用farcaster的可能性？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5137]
## 背景

- [ ] https://github.com/s0nik42/lotus-farcaster/issues/46

## 动机

[farcaster](https://github.com/s0nik42/lotus-farcaster)借助`storage`和`retrieval deals`的filtering hook抓取数据。如果venus有类似的，他们可能可以直接做一个支持。

[julien](https://filecoinproject.slack.com/archives/D0304KMMBJ9)说：

> Lotus description of the feature :

> https://lotus.filecoin.io/storage-providers/advanced-configurations/market/#using-filters-for-fine-grained-storage-and-retrieval-deal-acceptance

> SPs use this hook to enable CIDgravity and start managing their deal flow, example:

```  
Filter = "/opt/CIDgravity-X/CIDgravity-X/cidgravity_storage_connector.py --reject"
RetrievalFilter = "/opt/CIDgravity-X/CIDgravity-X/cidgravity_storage_connector.py --reject"
```

可以评估下看看？farcaster[文档](http://twinquasar.io/farcaster.html)

**Comment by diwufeiwen** [comment]
这个和metrics应该不是一回事，lotus那边的metrics在目录 metrics/metrics.go（不是通过filtering hook管理），RetrievalFilter 是针对交易市场的订单数据，并非传统意义的指标数据

**Comment by Fatman13** [comment]
julien说：

> Farcaster pulls the data through lotus api, not only  metrics.go

**Comment by diwufeiwen** [comment]
> julien说：
> 
> > Farcaster pulls the data through lotus api, not only  metrics.go

It seems that everything has been said, and it seems that nothing has been said. hh

**Comment by diwufeiwen** [comment]
lotus-exporter-farcaster 大概看下来是通过api接口数据，然后自己制定了了一些metrics，这种貌似和我们的初衷不符，如果想要接入，我们的组件不需要实现指标，只需把每个链服务组件的服务监听地址和共享token给到他们，就能实现目前的lotus-exporter-farcaster的效果。个人认为这和我们实现metrics是不同的路子，可以并行。
