### ISSUE TITLE
[Venus] venus 和 venus-market 合并 blockstore 相关实现

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5138]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

venus 和 venus-market 都各自实现了一套 blockstore 相关的实现，可以考虑合并到一起

venus 代码在：https://github.com/filecoin-project/venus/tree/master/pkg/util/blockstoreutil
venus-market 代码在：https://github.com/filecoin-project/venus-market/tree/master/blockstore

**Comment by hunjixin** [comment]
@simlecode 已解决？

**Comment by simlecode** [comment]
待做

**Comment by hunjixin** [comment]
@LinZexiao 可以合并了？
