### ISSUE TITLE
[venus-market] 移除对 venus-messager 不合适的依赖 

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5140]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

venus-market 引用了[venus-messager的一个结构体](https://github.com/filecoin-project/venus-market/blob/master/api/clients/gateway_client.go#L24)，考虑移除

**Comment by hunjixin** [comment]
@simlecode 补充信息

**Comment by simlecode** [comment]
已移除
