### ISSUE TITLE
[STM] 为STM分一下`venus-miner`的系统和子系统

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5158]
STM教程：
- [ ] https://github.com/filecoin-project/venus/discussions/4948

之前venus系统且分案例：
- [ ] https://github.com/filecoin-project/venus/issues/5007#issuecomment-1171958431

venus-auth案例：
- [ ] https://github.com/filecoin-project/venus/issues/5067#issuecomment-1190966536

STM团队最终通过分好的系统整理的catalog：
- [ ] https://github.com/filecoin-project/venus/issues/5116

**Comment by Fatman13** [comment]
这个可能要麻烦 @diwufeiwen 大神看看？😄

**Comment by zl03jsj** [comment]
### venus-miner 子系统分类

#### API 子系统
- ./api/client/client.go 用于外部系统需要通过rpc调用miner时直接引用方便直接构造client.
- ./api/ 对外提供RPC服务的API相关的接口定义
- ./node/impl 对外提供的PRC接口的实现
#### 命令行工具子系统
- ./cli 调试相关
- ./cmd 日常运维相关
#### 监控子系统
- ./lib/metrics 指标监控相关子系统
- ./lib/tracing 请求链路追踪子系统
- ./lib/journal 出块详情子系统, 用于收集矿工的出块信息
#### miner挖块相关的核心逻辑
- ./miner
#### venus-miner配置相关的类型以及加载的实现
- ./node/config
#### 与`venus-auth`的交互相关的定义即业务逻辑
- ./modules/miner-manager
#### 持久化子系统
- ./node/slashfilter 在miner挖矿的过程中的block状态及结果
#### 应用程序目录子系统
- ./node/repo

@Fatman13
