### ISSUE TITLE
[API] 增加WithdrawBalance API?

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5161]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [x] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

是否可以考虑增加miner提现API？

相关PR：
- [ ] https://github.com/filecoin-project/lotus/pull/9098

**Comment by hunjixin** [comment]
miner上不支持提取操作，提取需要owner地址，而这个地址用户一般不会放出来。无法也不应该在miner上支持提取。 
这个在另外的管理工具中更加合理。

**Comment by Fatman13** [comment]
在cluster的工具里面比较好，还是venus的工具里面？

**Comment by diwufeiwen** [comment]
实际上venus-cluster已经有此接口： venus-sector-manager util sealer actor --miner=<f0***> withdraw,还有其他一些actor相关命令，请去试用
