### ISSUE TITLE
[venus-messager] venus-message去掉默认的messager.log日志文件

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5172]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

部署venus-message的时候默认会在程序运行目录生成一个messager.log文件，但是一般部署的时候都会指定venus-messager日志目录以及日志压缩归档方式，故该默认日志文件意义不大，建议去掉

**Comment by hunjixin** [comment]
@simlecode  已解决？

**Comment by simlecode** [comment]
没，待做
