### ISSUE TITLE
[venus-wallet]: 重构调研，加强用户控制手段，剔除目前没有使用的功能（安全规则）

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#5177]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

[venus-wallet]: 重构调研，加强用户控制手段，剔除目前没有使用的功能（安全规则）

**Comment by Fatman13** [comment]
相关讨论：
- [ ] https://github.com/filecoin-project/venus/discussions/5178
- [ ] [Slack](https://filecoinproject.slack.com/archives/C028PCH8L31/p1660099495363529)

**Comment by litai686** [comment]
1、转账功能应该加上去，没有这个功能真的很麻烦，转账的时候可以做个密码验证
2、显示钱包余额、nonce、有利于运维 
强烈建议加上去上面2个功能

**Comment by hunjixin** [comment]
现实balance/nonce， 转账 这些功能都是要连接节点的， 钱包尽量还是不要连外界。 我还是觉得缺乏统一的管理工具

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/issues/5177

**Comment by litai686** [comment]
我能理解你对钱包安全的定义，只是希望尽可能的与外网隔离，但目前市面上所有的去中心化钱包，通讯都是需要链接全节点， 全节点提供服务，钱包有需求的时候去链接获取链上信息，不存在所谓的不安全。

**Comment by litai686** [comment]
按照您的思路，我们正常部署，有些全节点也是在内网，只是单纯的提供相关服务，钱包请求全节点属于正常业务

**Comment by Fatman13** [comment]
@hunjixin 要不留个配置项，默认不允许，但是用户在认知风险的情况下，可以自己打开？

**Comment by hunjixin** [comment]
很多去中心化钱包不是个单纯的钱包，附带了一些管理功能，发消息功能。是不一样的。

**Comment by hunjixin** [comment]
真的需要这个，不如直接部署一个全节点当钱包用，想要什么都有。

**Comment by litai686** [comment]
如果拿全节点当钱包用，不够灵活呀，钱包组件独立出来的意义就在这里，比如我让客户自己管理钱包，难道还让客户自己跑个全节点，不太现实 .  @Fatman13  留个配置的方法不错，针对不同的需求更灵活调整

**Comment by diwufeiwen** [comment]
这个可以自由讨论，并且希望更多使用过的人提建议，要“大鸣大放”

**Comment by Fatman13** [comment]
我们现在owner用的是fivetoken，一个手机离线钱包，不联网，保存私钥，专门签名。一个手机构建消息，提b，转账消息否可以发。

**Comment by litai686** [comment]
我们这边也是自己开发了一个离线钱包管理owner，并且把withdraw集成进去了，装在客户自己的笔记本上，如果客户要提币或者转账的时候开机，执行下提币或者命令就可以了，本地签名直接推到远程的全节点上链，不用的时候关机，确保key的安全性。管理owner的钱包跟worker钱包最好是分离的。

**Comment by Fatman13** [comment]
66666，厉害。笔记本客户端？https://fivetoken.co/ 也可以关注下。[doge]

**Comment by hunjixin** [comment]
至于过滤器功能，可以简单的增加一个jq消息过滤器，想象也可以简单的让用户自己判断需要签名什么类型的信息。 麻烦的地方在于签名的消息种类比较多，需要考虑怎么让过滤器好写一些。

**Comment by litai686** [comment]
加个配置就可以了，如果配置里面填写了全节点，就可以现实余额和nonce，可以转账，如果不填写全节点，之前啥样还是啥样，这样客户自己选择，更灵活

**Comment by hunjixin** [comment]
钱包独立出来是为了安全，查询交互倾向于在额外的工具中实现，现在有蛮多的类似的需求。钱包尽量保持简单，少依赖。
