### ISSUE TITLE
venus-worker配置项sealing_thread优化建议

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5184]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [X] venus-worker
- [ ] 文档 / docs

### 描述 / Description

当前如果p1有多个任务，需要在sealing_thread配置项下写多条location路径配置，导致配置文件看起来非常冗长，但是大部分情况下location其实只有一个，通过目录名+数字的形式来区分，如下图：
<img width="243" alt="image" src="https://user-images.githubusercontent.com/57161619/184472908-a8f6ed31-dbce-4414-b9aa-9e44147c1ce5.png">

建议修改为：
[[sealing_thread]]
num=3      #表示在当前location下线程数
location = "/sealer/"     #不变，依然填写pc1数据保持路径，当num=3时，自动在该目录下新建3个线程的工作目录
sealing.allowed_miners = [1357] 

感觉这样部署配置的时候能够简单些，配置文件看起来也不会那么冗长

**Comment by 0x5459** [comment]
>自动在该目录下新建3个线程的工作目录

按照你说的，这三个工作目录的名称是什么呢？根据数字分配吗。这样也会增加额外的理解成本。

当前的做法，虽然稍微冗长，但好在简单。

**Comment by dtynn** [comment]
简化配置的编写，可以通过一些外部途径来解决，如批量生成的脚本等
但命名规则（命名序列）这种事情，不同的使用者有不同的偏好，如
- 最简单的数字 `1-32`;
- 两位数字，0占位：`01-32`
- 字母 `a-z`, `aa-zz`, `A-Z` 

等等，不一而足
鉴于此，相比囊括所有使用者的偏好，我们还是更倾向于提供一个简单、明确、不会产生歧义的机制
