### ISSUE TITLE
[venus-wallet] 远程wallet兼容`lotus`节点的需求

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5186]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

是否可以考虑`wallet`兼容`Lotus`来推广用户？

![image](https://user-images.githubusercontent.com/1591330/184583406-9832ed2e-4385-4db2-979e-aefa0121afaa.png)

相关需求：
- 来自[Slack](https://filecoinproject.slack.com/archives/C028PCH8L31/p1660537171873359)

**Comment by woshidama323** [comment]
目前确定有一个场景： 
1. 我们想提高 lotus 钱包管理的安全性 所以希望可以将wallet 独立出来到一个安全级别比较高的服务器上，除了授信服务的签名请求，其他的都会受限，以此保护钱包私钥等信息 

2. 从lotus 与 venus 之间如果切换，是否可以不用动钱包，移来移去有泄漏风险

**Comment by diwufeiwen** [comment]
> 目前确定有一个场景：
> 
> 1. 我们想提高 lotus 钱包管理的安全性 所以希望可以将wallet 独立出来到一个安全级别比较高的服务器上，除了授信服务的签名请求，其他的都会受限，以此保护钱包私钥等信息
> 2. 从lotus 与 venus 之间如果切换，是否可以不用动钱包，移来移去有泄漏风险

lotus-->venus的场景: venus的链服务 + lotus-wallet；
venus-->lotus的场景: lotus + lotus-wallet； 保持一直使用lotus-wallet不变，还是：

lotus-->venus的场景: venus的链服务 + venus-wallet；
venus-->lotus的场景: lotus + venus-wallet

签名一直用venus-wallet？

**Comment by hunjixin** [comment]
@diwufeiwen  venus-wallet是能够兼容的么，issue可以关闭了么

**Comment by diwufeiwen** [comment]
lotus-wallet的主要接口 WalletHas/WalletSign应该是有的
