### ISSUE TITLE
venus 等仓库在本地make test的时候并没有跑完完整的测试流程

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5202]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
{
        "Version": "1.6.0+git.0ca0cdd8c"
}
```

### 描述 / Describe the Bug

在本地进行 make test 之后，ci中的测试仍不能通过
可见本地的测试并不完整
建议参照ci修改本地的测试

### 日志 / Logging Information

```text
略
```

**Comment by hunjixin** [comment]
@LinZexiao 补充信息
