### ISSUE TITLE
[venus-messager] 消息增加uuid?

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5203]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

待评估，venus可能不适用；Lotus给miner发送的消息带上uuid，不知道是否需要借鉴，还是完全不适用。

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9174

**Comment by hunjixin** [comment]
神奇这个东西。 我觉得有这个还不如让他们考虑往我们messager里面推送。

**Comment by Fatman13** [comment]
哈哈哈。

**Comment by diwufeiwen** [comment]
这个与venus-messager没有关系，是在mpool中保存已签名消息时用来生成k-v中的key的，建议引入
