### ISSUE TITLE
[venus-meesager] lotus mpool消息重新推送API

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5208]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

是否需要参考lotus mpool消息重新推送API命名规则和实现方式？

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9177

**Comment by diwufeiwen** [comment]
（1）lotus master 最新提交没有，估计有问题，暂时不引入。
（2）UuidWrapper 目的是为了在本地存储消息时引入MsgUuid uuid.UUID，主要是存储已签名消息时生成key的
