### ISSUE TITLE
[venus] ci 增加对go.mod文件的检查

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5219]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 存在问题

在 venus-auth 中， https://github.com/filecoin-project/venus-auth/commit/3313af6a9ba1e4cf5fe3afabacb1b265beecb9bd 已合入master，但go.mod还保留一个未使用的依赖

### TODO
在[common.yml](https://github.com/filecoin-project/venus/blob/master/.github/workflows/common_go.yml#L48)增加对go.mod的检查，增加 `go mod tidy`

**Comment by LinZexiao** [comment]
已经修复
