### ISSUE TITLE
[CI] Adding STM to CI

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5220]
源：[需求](https://filecoinproject.slack.com/archives/C0365S9E0JW/p1661422543264079?thread_ts=1661262528.272089&cid=C0365S9E0JW)

Is there a way you could add an extra step to the CI?
The STM dashboard uses the following information for every test (unit and integration):

```
{
  "name": "TestMulticoreSDR",
  "result": "success",
  "url": "https://app.circleci.com/pipelines/github/filecoin-project/lotus/21569/workflows/0c270977-e0a9-47b1-a33b-0c10843f1483/jobs/490307/tests"
  }
}
```

To summarize:
- Test name (required)
- Test status (success/failure) (required)
- URL to the CI that ran the test (optional, not required)

For lotus, the STM retrieves this information from the CircleCI's API, but since venus doesn't use CircleCI, we need this information to be uploaded in an artifact somewhere accessible.
Please note that this is not critical for the initial version of the STM dashboard, but the dashboard will not be able to link the behaviors with the test status in the CI.

**Comment by zl03jsj** [comment]
https://filecoinproject.slack.com/archives/C0365S9E0JW/p1662612081589399

发起了一个相关的讨论.等待回复中.

**Comment by zl03jsj** [comment]
结果: 
这个功能可选功能, 并且需要能上传下载附件的网络服务,或者重新使用circleci, 所以暂时不添加这个脚本. 
如果有其它法欢迎留言讨论.

**Comment by zl03jsj** [comment]
备用方案:  参考lotus, 同时使用`circleci`和`git action`, circleci只在 需要  测试的和上传测试结果 的工作流.

**Comment by zl03jsj** [comment]
#### 在这里汇总一下已完成添加注解的组件:
- [x] https://github.com/filecoin-project/venus-miner/pull/143
- [x] https://github.com/filecoin-project/venus-wallet/pull/103
- [x] https://github.com/filecoin-project/venus-auth/pull/103
- [x] https://github.com/filecoin-project/venus-messager/pull/255
- [x] https://github.com/filecoin-project/venus/issues/5421
#### 阻塞中的, 以下组件需等待STM团队将组件的注解分类系统加入到STM项目中之后才能继续
- [ ] https://github.com/filecoin-project/venus/issues/5385 
- [ ] venus-market 建议在[venus-market改造计划](https://github.com/filecoin-project/venus/issues/5453)完成后再设施。
