### ISSUE TITLE
[待评估] 是否需要支持wallaby网络？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5223]
是否需要支持wallaby网络？应该优先级很低。。wallaby目前是专供fvm测试的网络，由@f8-patrick负责运维。

相关：
- [ ] https://github.com/filecoin-project/lotus/pull/9200

**Comment by Fatman13** [comment]
关联：

- [ ] https://github.com/filecoin-project/lotus/pull/9399

**Comment by hunjixin** [comment]
不做，没什么需求。

**Comment by Fatman13** [comment]
关联PR：
- [ ] https://github.com/filecoin-project/lotus/pull/9411

**Comment by Fatman13** [comment]
> 不做，没什么需求。

那我先关掉啦。

**Comment by Fatman13** [comment]
- [ ] https://github.com/filecoin-project/lotus/pull/9514
