### ISSUE TITLE
[venus] 测试网导出快照文件用时是lotus的3.5倍

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#5228]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

性能问题，cali网络导出快照文件用时为lotus的3.59倍
**lotus:**      export finished  "duration": 141.98460
**venus:**    export finished  "duration": 510.7522

版本号:
venus version
{
	"Version": "1.6.1+git.8301cb853"
}

![image](https://user-images.githubusercontent.com/43364105/187026418-f7993ca7-a7d5-4ec8-ba3f-9813c719b02d.png)

**Comment by cloudxin** [comment]
验证方法:
time ./lotus chain export --recent-stateroots=920 --skip-old-msgs snapshot-lotus.car
time ./venus chain export --recent-stateroots=920 --skip-old-msgs snapshot-venus.car

![image](https://user-images.githubusercontent.com/43364105/187026673-ec2e23d9-29f1-4696-b511-6268de9491e6.png)
![image](https://user-images.githubusercontent.com/43364105/187026686-17a8ab69-267f-4455-bff4-9824753d79a3.png)

**Comment by zl03jsj** [comment]
https://github.com/filecoin-project/venus/issues/4922 重复的issue
