### ISSUE TITLE
[venus-market]增加venus-market接口层测试

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5236]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

- [ ] actor
- [ ] 存储订单部分
- [ ] 检索订单部分
- [ ] piece数据部分
- [ ] market funds部分
- [ ] dagstore部分
- [ ] piece storage部分
- [ ] 版本接口
- [ ] 配置部分接口设置不保留，后续会删除这部分接口和代码

产生的文件放到到tmp目录里面

**Comment by Fatman13** [comment]
market 改造计划跳过的 issue。先关掉。
