### ISSUE TITLE
[venus-market]配置重整， 支持每个矿工个性化配置

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5237]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

现在的配置从lotus迁移过来，只能在有一个矿工的时候有作用。所以venus-market需要针对每个矿工进行一些个性化的配置方法。需等待market账号这部分重构后才能继续

**Comment by zl03jsj** [comment]
duplicated issue.

**Comment by Fatman13** [comment]
这个题目有好多duplicate。。。😂
