### ISSUE TITLE
venus去除或者优化已失效命令

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5243]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

情况描述：venus中dag命令无效，drand命令无详细帮助信息，无法确定如何使用该命令

建议：如果确定不再需要可以从venus中清理掉这两个命令

**Comment by simlecode** [comment]
```
$ ./venus drand --help
USAGE
  ./venus drand - Retrieve randomness from drand server

SYNOPSIS
  ./venus drand [--height=<height>] [--round=<round>]

OPTIONS

  --height  uint64 - chain epoch (default 0).
  --round   uint64 - retrieve randomness at requested round (default 0).
```
