### ISSUE TITLE
[venus] 同步到最新高度时 sync status 不显示信息

### ISSUE THREAD

**Issue by YiRuiLiher** [filecoin-project/venus#5244]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
release/v1.7.0
```

### 描述 / Describe the Bug

当venus同步到最新高度后 ./venus sync status不会显示任何信息

### 日志 / Logging Information

```text
root@200-21:~/hj/venus# ./venus --repodir=./.venus-mainnet sync status
Syncing:
Waiting:
```

### 重现步骤 / Repo Steps

./venus sync status

**Comment by hunjixin** [comment]
可以显示最新的历史信息出来

**Comment by diwufeiwen** [comment]
./venus sync status
{source=12D3KooWLce5FDHR4EX4CrYavphA5xS3uDsX6aoowXh5tzDUxJav sender:12D3KooWLce5FDHR4EX4CrYavphA5xS3uDsX6aoowXh5tzDUxJav height=1323103 head={ bafy2bzacedfjoay7cy7v6v2hg532iek4raytgquis3lsbx7futcsphgdudone bafy2bzaceaymhj2n5cqcchvtijrmk6hop7ddkwxsgmyilforkmdd2hjnn2b3m bafy2bzacedcv5xdjxhdafkfr56y7ncg7shctztxbqo32yznfrwhdxciayghc2 }}
Done!
