### ISSUE TITLE
[venus] force测试网络不支持512Mib矿工

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5249]
### 链服务模块 / Chain Service Components

- [x] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
最新版本
```

### 描述 / Describe the Bug

创建512矿工，消息报错不支持这种功能类型

"gas estimate: estimating gas limit: message execution failed: exit 16, reason: message failed with backtrace:\n00: f04 (method 2) -- send to f01 method 2 aborted with code 16 (16)\n01: f01 (method 2) -- constructor failed: send to f01021 method 1 aborted with code 16 (16)\n02: f01021 (method 1) -- proof type StackedDRGWindow512MiBV1 not allowed for new miner actors (16)\n (RetCode=16)",
    "GasUsed": 0

### 日志 / Logging Information

```text
"gas estimate: estimating gas limit: message execution failed: exit 16, reason: message failed with backtrace:\n00: f04 (method 2) -- send to f01 method 2 aborted with code 16 (16)\n01: f01 (method 2) -- constructor failed: send to f01021 method 1 aborted with code 16 (16)\n02: f01021 (method 1) -- proof type StackedDRGWindow512MiBV1 not allowed for new miner actors (16)\n (RetCode=16)",
    "GasUsed": 0
```

**Comment by diwufeiwen** [comment]
这个应该是`specs-actors v8`中的bug，v8将proof-type等的定义移到了`go-state-types` package, venus/lotus 自定的 `proof-type` 都是注册到`go-state-types`的,但是在`specs-actors v8`中却是用自己模块的变量判断的：
filecoin-project/specs-actors/v8@v8.0.1/actors/builtin/miner/miner_actor.go#L110
```
if !CanWindowPoStProof(params.WindowPoStProofType) {
		rt.Abortf(exitcode.ErrIllegalArgument, "proof type %d not allowed for new miner actors", params.WindowPoStProofType)
	}
```
filecoin-project/specs-actors/v8@v8.0.1/actors/builtin/miner/policy.go#L119
```
var WindowPoStProofTypes = map[abi.RegisteredPoStProof]struct{}{
	abi.RegisteredPoStProof_StackedDrgWindow32GiBV1: {},
	abi.RegisteredPoStProof_StackedDrgWindow64GiBV1: {},
}

// Checks whether a PoSt proof type is supported for new miners.
func CanWindowPoStProof(s abi.RegisteredPoStProof) bool {
	_, ok := WindowPoStProofTypes[s]
	return ok
}
```
实际上自定义的512M生效的是`go-state-types` 中的WindowPoStProofTypes

**Comment by diwufeiwen** [comment]
所以目前venus的修改是临时方案
