### ISSUE TITLE
在github release中发布可执行文件

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5255]
### 链服务模块 / Chain Service Components

- [X] venus
- [X] venus-auth
- [X] venus-gateway
- [X] venus-messager
- [X] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [X] venus-sector-manager
- [X] venus-worker
- [ ] 文档 / docs

### 描述 / Description

除了增加在github的发布之外，还应考虑对各个平台的兼容性

**Comment by YiRuiLiher** [comment]
除cluster外都已有可执行文件
