### ISSUE TITLE
[market-client]批量发单功能？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5261]
@cloudxin 提出的批量发单功能需求；应用场景和具体做与不做待评估；

**Comment by hunjixin** [comment]
1.  客户端获取ask
2. 客户端批量生成client proposal
3. 客户端发送client proposal到服务端
4. 服务端验证proposal， 获取数据，签名上链。
5. 上链后生成等待封装的订单

**Comment by Fatman13** [comment]
这个确实，如果真的要做，得申请个grant。

**Comment by Fatman13** [comment]
社区[关注点](https://filecoinproject.slack.com/archives/CR98WERRN/p1662522234248649)之一。

**Comment by Fatman13** [comment]
## 功能需求

- DC发单成为主流，SC需要发单工具辅助SC按照f+规则进行发单。
- 数据库记录SC地址发单信息，CID，多少个copy等等信息？
- 多发单地址管理？剩余DC查询？

**Comment by hunjixin** [comment]
关于多发单地址管理， 剩余dc查询功能：
1. market-client 现有的default 地址默认采用节点或者钱包中设置的默认地址 修改初始化逻辑， 如果没有手动设置默认地址，则直接采用钱包中的默认地址
2. market-client支持钱包中地址Dc查询.  可以考虑增加一个专门的子命令分类，用于dc相关的操作 @Fatman13  可能需要调研现有产品的一些功能。
3. market-client需支持多地址的发送订单(存储和检索)的保存， 防止和现有逻辑出现冲突导致数据丢失
4. 上面功能中，发送批量订单的时候需要支持通过具体哪个dc地址进行订单发送， 可参考现有storage deals init的发送地址选择逻辑

**Comment by Fatman13** [comment]
dup
