### ISSUE TITLE
[venus-messager] 搜索的地址信息与实际显示的不一致

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5275]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
version v1.6.0--df5e882
version v1.6.0--58feea4
```

### 描述 / Describe the Bug

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/57161619/189029461-c2e41d75-cf1b-412b-a77f-2a90e599a9c3.png">
使用
t3rugtczeric5kypbgnt7643omyxia6mkrevryrggrksqx73zfbqthgj7eumxbeap6hoctj45dc6k6ylyfm57b
t3rugtczeric5kypbgnt7643omyxia6mkrevryrggrksqx73zfbqthgj7eumxbeap6hoctj45dc6k6ylyfm57c
t3rugtczeric5kypbgnt7643omyxia6mkrevryrggrksqx73zfbqthgj7eumxbeap6hoctj45dc6k6ylyfm57d
等地址查出来的却是t3rugtczeric5kypbgnt7643omyxia6mkrevryrggrksqx73zfbqthgj7eumxbeap6hoctj45dc6k6ylyfm57a信息
同时del、forbidden、active也存在该情况

### 日志 / Logging Information

```text
无
```

### 重现步骤 / Repo Steps

1、该钱包为测试地址，私钥为7b2254797065223a22626c73222c22507269766174654b6579223a2255694b374e2f74322b3474777262793461753235317337596848646b414c686e58595665567a75524656383d227d
2、导入venus系统后，执行./venus-messager address search t3rugtczeric5kypbgnt7643omyxia6mkrevryrggrksqx73zfbqthgj7eumxbeap6hoctj45dc6k6ylyfm57d即可复现

**Comment by simlecode** [comment]
需要复现与确认

**Comment by simlecode** [comment]
go-address 库的问题：https://github.com/filecoin-project/go-address/issues/22 ，升级到`v1.0.0`可以解决，venus-messager升级后 (commit: `41db9c7710e111276ed8b919ff1a4348725e0ffb`) 测试，没有出现类似问题
