### ISSUE TITLE
[venus-messager]按照钱包地址设置消息推送条数时如果不按照命令要求提交会导致原来的值被覆盖

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5277]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

情况描述：正确修改消息数命令格式应该是 ./venus-messager address set-sel-msg-num  --num=20  t3地址，如果将num放到最后，比如./venus-messager address set-sel-msg-num t3地址 --num=20，这时不会提示命令执行失败，num也不会成功，但是却将selMsgNum重置为了0

建议：
1、命令参数支持无顺序设置，将num放t3地址前后均可
或者
2、如果没按照命令参数顺序设置，直接报错，并且不再将selMsgNum重置为0

**Comment by simlecode** [comment]
`./venus-messager address set-sel-msg-num --num=20 <address>` 还是保持这种格式，`--num` 改为必须要设置值
