### ISSUE TITLE
[追踪] FIP0045 相关实现追踪

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5281]
追踪FIP0045相关PR和实现：
- [ ] https://github.com/filecoin-project/lotus/issues?q=is%3Aopen+is%3Aissue+label%3AFIP-0045

**Comment by simlecode** [comment]
持续关注

**Comment by Fatman13** [comment]
和 https://github.com/filecoin-project/venus/issues/5347 重复。
