### ISSUE TITLE
[venus-docs] venus-market链服务部署流程文档更新

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5282]
有群众反映venus-doc中[这个文档](https://venus.filecoin.io/zh/market/using-venus-market-for-master.html)疏于更新：

- 作为链服务部署market少了set-addrs和set-peer-id的步骤？
- 缺少配置piecestore的步骤？
- 直接修改配置文件？文档没有明确说明
- 按当前文档无法正常跑完接发单流程

![image](https://user-images.githubusercontent.com/1591330/189827324-934c1535-7032-4edb-9d95-55e0c836b4ee.png)

**Comment by zl03jsj** [comment]
原文文档:
> 可以参考 `market为miner挂单`

而`market为miner挂单`的内容中, 包含了:`set-peerid`和`set-addrs`. **个人认为这里不需要重复这一部分内容了.**

这种引用链接的作用正是:

1: 为了避免相同的内容需要在不同的地方反复的编写.
2: 如果出现需要修改文档的情况, 只需要修改一个地方就可以了.

**Comment by zl03jsj** [comment]
这里的确有几个地方需要重新整理:
1. `market为miner挂单` 的内容过于陈旧, 里面应该把`venus-sealer`的内容去掉, 替换为`cluster`.
2. 的确需要明确的指出需要`set-peerid`和`set-addres`并给出准确的链接.

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus-docs/pull/344
