### ISSUE TITLE
[venus-miner]命令行工具建议

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5285]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [X] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

1、./venus-miner stop停止程序看起来与kill命令效果一致，这个命令感觉可以取消，麻烦评估下这个命令是否有存在必要；
2、./venus-miner config仅仅用来打印miner默认配置，既不能改配置，也跟实际配置不一样，意义不大，麻烦评估是否可以取消，或者赋予更多实际有用功能；
3、./venus-miner -h中提到有三个开发者功能，除log可用外，其余两个 Manage logging并不能执行，如果没用，麻烦在帮助信息中取消；
4、./venus-miner -h中提到有--color参数，使用后没发现有什么颜色变化或其它效果，并且也没有帮助说明，如果没用，麻烦取消

**Comment by diwufeiwen** [comment]
venus-miner stop这个建议保留，一个软件应该有正常的退出命令，kill 是因为其他组件缺少stop命令，所以其他组件应该增加stop命令用于正常退出服务。
