### ISSUE TITLE
请问msg中的params怎样解码？

### ISSUE THREAD

**Issue by 17621859515** [filecoin-project/venus#5292]
如图所示，这个是什么编码，应该怎样解码？
![image](https://user-images.githubusercontent.com/69946784/190540981-f1e9e9c1-aed2-49ba-bf89-b5fe454312be.png)

**Comment by zl03jsj** [comment]
### 如果只是想查看这个消息的参数详情: 
可以直接在`filscan.io`上查询, 输入消息id查询, 你图上的消息查询结果如下:
https://filscan.io/tipset/message-detail?cid=bafy2bzacec33bn7v4rx65q7mwuyiqeecxfqz6nenxmuk4eabkqyrgn6kspwd6

### 通过代码解析的逻辑流程为:
这是一段二进制编码的base64字符串, 其本质为一个支持cbor持久化的对象, 是`Msg.To`所代表的Actor的`Msg.Method`的方法的调用参数.
具体解析流程为:
1. 根据`Msg.To`, 找到这个`To`地址的Actor类型.(此处为`f2a5cpqwnvf3gbvu24gfkdtf5yvwst6fmv6lzl3ia`,是一个multisig actor)
2. 找到`multisig` actor的函数列表中, `MethodNum` = `Msg.Method`的方法(此处为2, 即mutlsig.Approve) , 查看次函数的参数:
```go
type ProposeParams struct {
	To     addr.Address
	Value  abi.TokenAmount
	Method abi.MethodNum
	Params []byte
}
```

 https://github.com/filecoin-project/specs-actors/blob/d8d9867f68a3c299295efdc6d1b3421c9b63df57/actors/builtin/multisig/multisig_actor.go#L227

3. "Params"为base64编码, 将其解码为二进制数据.
4. 然后将这个二进制数据`cbor`解码,  就得到了这个函数的具体参数的对象.
```go
func (t *ProposeParams) MarshalCBOR(w io.Writer) error {.......}
```

**Comment by 17621859515** [comment]
> https://github.com/filecoin-project/specs-actors/blob/d8d9867f68a3c299295efdc6d1b3421c9b63df57/actors/builtin/multisig/multisig_actor.go#L160

谢谢，我要的是代码解析逻辑，我去试试看

**Comment by 17621859515** [comment]
> ### 如果只是想查看这个消息的参数详情:
> 可以直接在`filscan.io`上查询, 输入消息id查询, 你图上的消息查询结果如下: https://filscan.io/tipset/message-detail?cid=bafy2bzacec33bn7v4rx65q7mwuyiqeecxfqz6nenxmuk4eabkqyrgn6kspwd6
> 
> ### 通过代码解析的逻辑流程为:
> 这是一段二进制编码的base64字符串, 其本质为一个支持cbor持久化的对象, 是`Msg.To`所代表的Actor的`Msg.Method`的方法的调用参数. 具体解析流程为:
> 
> 1. 根据`Msg.To`, 找到这个`To`地址的Actor类型.(此处为`f2a5cpqwnvf3gbvu24gfkdtf5yvwst6fmv6lzl3ia`,是一个multisig actor)
> 2. 找到`multisig` actor的函数列表中, `MethodNum` = `Msg.Method`的方法(此处为2, 即mutlsig.Propose) , 查看次函数的参数:
> 
> ```go
> type ProposeParams struct {
> 	To     addr.Address
> 	Value  abi.TokenAmount
> 	Method abi.MethodNum
> 	Params []byte
> }
> ```
> 
> https://github.com/filecoin-project/specs-actors/blob/d8d9867f68a3c299295efdc6d1b3421c9b63df57/actors/builtin/multisig/multisig_actor.go#L160 3. "Params"为base64编码, 将其解码为二进制数据. 4. 然后将这个二进制数据`cbor`解码, 就得到了这个函数的具体参数的对象.
> 
> ```go
> func (t *ProposeParams) MarshalCBOR(w io.Writer) error {.......}
> ```

谢谢，我要的是代码解析逻辑，我去试试看

**Comment by zl03jsj** [comment]
> 谢谢，我要的是代码解析逻辑，我去试试看

这里已经提供了可直接使用的包, 可以直接用, 也可以作为参考:
https://github.com/filecoin-project/venus/tree/master/venus-shared/utils/msg_parser

**Comment by 17621859515** [comment]
> https://github.com/filecoin-project/venus/tree/master/venus-shared/utils/msg_parser

我应该怎样下载这个sdk，我这样使用go.mod文件。
下载的sdk中很多依赖都是未下载的。
![image](https://user-images.githubusercontent.com/69946784/190580084-6433cbdf-f09c-43e3-91c7-b526155093d8.png)

**Comment by zl03jsj** [comment]
> 我应该怎样下载这个sdk，我这样使用go.mod文件。下载的sdk中很多依赖都是未下载的。

在`go.mod`的同级目录执行`go mod download && go mod tidy` 

使用方法, 参考:
https://github.com/filecoin-project/venus-messager/blob/308f6abc46254801729f55301ec1e8761d71cf7e/cli/msg.go#L120
