### ISSUE TITLE
[index-provider] index-provider服务化提案？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5295]

**Comment by Fatman13** [comment]
@hunjixin 一起讨论讨论看看？

**Comment by zl03jsj** [comment]
我会抽时间再研究一下index-provider, 看看这一部分功能, 是不是index-provider本身缺少的. 
如果这一部分是它本身就缺少的, 是值得作为一个新的方向的.

**Comment by zl03jsj** [comment]
同时也想看看 @hunjixin 的意见.

**Comment by Fatman13** [comment]
这个太老了。应该暂时可以关闭。
