### ISSUE TITLE
[chore] CLI最佳实践优化？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5298]
CLI最佳实践优化？help文字，IsError()，NArg()等等；

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9317

**Comment by zl03jsj** [comment]
需要, 但优先级不高.

在实施过程中, 需要考虑以下因素:

由于venus的包含各种组件, 对于一些公共的封装如:
https://github.com/filecoin-project/lotus/blob/4f75e2041c13cdd8be8bdcd790449c2ec7f0091f/cli/helper.go#L34

可以考虑放到公共的库中, 供各个组件引用.
