### ISSUE TITLE
[Go] `osutil.ReadDir()`被`os.ReadDir()`替换

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5300]
这个一直给venus和lotus提交go相关pr的杰尼龟同志。

![image](https://user-images.githubusercontent.com/1591330/190586201-5cfbb71d-5eed-4278-ab15-8a11f53126d1.png)

相关：
- [ ] https://github.com/filecoin-project/lotus/pull/9282

**Comment by simlecode** [comment]
已替换
