### ISSUE TITLE
venus-doc 中优化对组件仓库文档的引用方式

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5302]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [X] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

现在我们文档的网站中比较多的都是对子仓库文档的引用，往往一个页面就一个链接，然后一片空白，是否可以考虑将这些连接规整到一个页面，或者直接将链接的目标文档渲染出来？

**Comment by Fatman13** [comment]
有道理，现在venus-docs用的这个vuepress，不知道是不是可以直接渲染github上面markdown的文章？

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus-market/pull/199

**Comment by LinZexiao** [comment]
我觉得可以尝试一下直接引用文档的url，不行的话，可以可以在ci中先下载对应文档，然后渲染
