### ISSUE TITLE
FIP45解读, 并组织一次分享.

### ISSUE THREAD

**Issue by zl03jsj** [filecoin-project/venus#5303]
fip45调研. 
 - [相关issue](https://github.com/filecoin-project/lotus/issues?q=is%3Aissue+is%3Aopen+label%3AFIP-0045)
 - [相关讨论](https://github.com/filecoin-project/FIPs/discussions/313)
 - [FIP45](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md)

并组织一次分享。(由于国庆节, 推迟到sprint50)

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus/issues/5281

**Comment by Fatman13** [comment]
关联
- [ ] https://github.com/filecoin-project/community/discussions/74?sort=top#discussioncomment-3825422

**Comment by zl03jsj** [comment]
调研结果:
fip45文档:https://github.com/ipfs-force-community/dev-guidances/blob/master/%E7%A0%94%E7%A9%B6%E7%AE%A1%E7%90%86/Filecoin/FIP0045%E8%B0%83%E7%A0%94.md
fip34文档:https://github.com/ipfs-force-community/dev-guidances/blob/master/%E7%A0%94%E7%A9%B6%E7%AE%A1%E7%90%86/Filecoin/FIP0034%E8%B0%83%E7%A0%94.md

**Comment by Fatman13** [comment]
已完成。暂不分享。
