### ISSUE TITLE
搭建稳定的测试环境的方案

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5305]
### 链服务模块 / Chain Service Components

- [X] venus
- [X] venus-auth
- [X] venus-gateway
- [X] venus-messager
- [X] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [X] venus-sector-manager
- [X] venus-worker
- [ ] 文档 / docs

#### 为什么需要
1. 开发团队内部需要有自己的一个稳定的测试环境用于开发自测，避免对测试团队自建的环境造成破坏和不良影响，也有可能会给调试带来一些出乎意料的副作用
2. 当前部署的测试环境并不稳定，原因是lotus的创世节点总是崩溃，一旦测试环境的节点在测试的过程被重启或者崩坏就会导致测试环境彻底无法使用

####  待定方案

- 方案一：
  1. 保留一个有一定算力的venus节点，用于链增长，不用于直接测试
  2. 同步出 多个节点用于开发过程中的测试

- 方案二：
  1. 构建 算力 组件的docker容器
  2. 编写用于启动测试环境的 docker-compose file，可以较快的拉起一套测试环境，并且用完销毁也没有关系

#### 建议
1. 采用方案一时，开发的同学可以在开发机上通过docker-compose 较快地拉并维护一套链服务用于独自使用，这样可以避免别的同学地测试流程对自己地测试环境造成影响

**Comment by LinZexiao** [comment]
@hunjixin @diwufeiwen 请两位评估一下

**Comment by hunjixin** [comment]
方案一需要一个稳定的测试网络， 目前并没有这样一个好的基础。
方案二如果能做到容易起停，我觉得是可以接受的。

**Comment by elvin-du** [comment]
现在的情况是？
