### ISSUE TITLE
[venus] PropagationDelaySecs全球变量设置问题？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5336]
PropagationDelaySecs 全球变量之前好像没有准确被设置，lotus fix了一下。不知道Venus这边有没有相同的问题？

关联：

- [ ] https://github.com/filecoin-project/lotus/pull/9358

**Comment by diwufeiwen** [comment]
我们没有环境变量，在配置文件中，不需要按照lotus的改动改
