### ISSUE TITLE
[venus] 重构，去除NewestNetworkVersion

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5338]
不知道Venus有没有关联的改变？

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9351

**Comment by hunjixin** [comment]
需要评估有没有用这个接口，如果用了这个接口，那么大概率需要兼容此接口

**Comment by simlecode** [comment]
全局的一个参数名字改了，可以放到 nv18 里面

**Comment by Fatman13** [comment]
兄弟们，评估好了记得脱掉 c-triage 这个标签。[doge]

**Comment by simlecode** [comment]
好的
