### ISSUE TITLE
[venus*] reviewe规范制订

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5343]
### 链服务模块 / Chain Service Components

- [X] venus
- [X] venus-auth
- [X] venus-gateway
- [X] venus-messager
- [X] venus-miner
- [X] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

编写venus review的规范，方便大家在review的时候有迹可循。

**Comment by Fatman13** [comment]
这个 @elvin-du 大佬有空的时候可看看？到时候可以另开 issue。
