### ISSUE TITLE
check db nullable column in venus*/过一遍数据库中可空值

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5344]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [X] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

1. 需要设置default值的设置default
2. 数值类型的设置成not null.
3. bit.Int默认值改成0字符串

**Comment by YiRuiLiher** [comment]
✅
