### ISSUE TITLE
[venus-market] boost协议兼容调研

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5345]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [x] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

从会议沟通获得的成果
1. go-fil-market逐渐会被淘汰掉，以后会使用心得boost协议
2. boost协议目前的实现，我们现在不是非常清楚，需要调研，必须弄清楚细节部分
3. 结合我们的需求和第二步中得到的信息， 尽量从协议层满足我们的需求，保证以后的工作推进比较合理且容易。
4. 第二部中得到的信息在非协议部分可能存在对我们不合理的地方，可以提出我们的建议进行修正。

**Comment by Fatman13** [comment]
关联：
- [ ] [Slack](https://filecoinproject.slack.com/archives/CEHHJNJS3/p1664333835286909)

**Comment by Fatman13** [comment]
CC @LexLuthr

**Comment by LinZexiao** [comment]
https://github.com/LinZexiao/document/blob/main/venus/boost_compatibility.md

**Comment by Fatman13** [comment]
> https://github.com/LinZexiao/document/blob/main/venus/boost_compatibility.md

这个调研感觉可以发到 venus-market/docs/dev 下面？ @LinZexiao 参考cluster这个路径。https://github.com/ipfs-force-community/venus-cluster/tree/main/docs/dev
