### ISSUE TITLE
[venus-messager] apply 多个高度时，消息处理错误

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5375]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
master
```

### 描述 / Describe the Bug

当revert多个高度时， messager回滚消息正确，但是重新附加消息时，会丢失中间的一些区块内的消息。

### 日志 / Logging Information

```text
忽略
```

**Comment by YiRuiLiher** [comment]
难以复现
