### ISSUE TITLE
[venus*] 用户数据隔离

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5384]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

未来希望用户可以查看自己的信息，或者对自己的信息进行处理。
1.   通过 token 鉴别用户身份,只允许用户访问自己相关的数据 
2.   admin 权限是最高权限, 可以访问所有的接口或者说数据, 该权限只应 链服务管理员持有, 其他用户 最高可以拥有 sign 权限
3.  详细的接口权限变动以及注意事项 参见 各组件对应PR(下面的回复中) ,主要包括 messager, market, miner, auth

**Comment by diwufeiwen** [comment]
用户的入口：
首先，用户需要一个UI来执行查询，目前貌似可供选择的只有venus-sector-manager，比如订单管理（查询，重新标识状态等），消息关系（查询，替换等），这些本就是与venus-cluster强关联的数据，在vsm上操作是合理的。除此之外，是不是有部分数据与venus-cluster没有关系的，比如想查看一天出块权等（venus-miner上的API），这种用户的操作入口是什么，新开发的venus-tools？

**Comment by diwufeiwen** [comment]
数据分类：
要展示什么数据，提供哪些操作，在哪里操作等

**Comment by diwufeiwen** [comment]
实现方式：
RPC接口的token感觉没啥问题，根据token可以找到对应的minerID，signer等，有这些足够查询出关联的数据了

**Comment by hunjixin** [comment]
现在在auth中保存了地址信息， 如果venus-tool中用户需要管理地址， 那么这里可能是需要连接到auth中。

**Comment by LinZexiao** [comment]
- [ ] https://github.com/filecoin-project/venus/pull/5521
- [ ] https://github.com/filecoin-project/venus-messager/pull/293

**Comment by LinZexiao** [comment]
venus-market

- [ ]  https://github.com/filecoin-project/venus/pull/5540
- [ ]  https://github.com/filecoin-project/venus-market/pull/254

**Comment by LinZexiao** [comment]
venus-miner

- [ ] https://github.com/filecoin-project/venus-miner/pull/163

**Comment by LinZexiao** [comment]
vanus-auth

- [ ] https://github.com/filecoin-project/venus/issues/4870
