### ISSUE TITLE
[venus-market] 拆解数据层单元测试

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5399]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

当前数据层的单元测试子测试之间存在存在耦合,不利于单一测试的情形

**Comment by Fatman13** [comment]
这个算一个大的feature，可以放在订单服务v2.5.0的milestone里面嘛？
