### ISSUE TITLE
[venus-market]:  矿工属性可独立配置

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#5410]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

前提是venus-market的定位？作为链服务组件是否合适，主要是pieces数据的传输问题？

1. 作为独立组件，类似目前的venus-cluster，配置也是，相对简单。

2. 作为链服务组件时，能不能把pieces数据直接传到对应的SP而不经过venus-market？配置是保存在venus-market还是venus-auth，目前的miner list是在venus-auth？用户操作界面是venus-cluster？

**Comment by Fatman13** [comment]
讨论：
- [ ] https://github.com/filecoin-project/venus/discussions/5425

venus-docs PR：
- [ ] https://github.com/filecoin-project/venus-docs/pull/351

**Comment by Fatman13** [comment]
是不是和这个[issue](https://github.com/filecoin-project/venus/issues/5115)重复了？

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus-market/pull/235
