### ISSUE TITLE
[venus-miner] 把是否开启出块功能添加到数据库

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#5415]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [X] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

针对每次重启都会默认打开所有miner出块功能，建议把venus-miner的出块功能配置的数据库。可以每个高度都从数据库中读取哪些miner是从venus这边出块

**Comment by diwufeiwen** [comment]
可以每个高度都从数据库中读取哪些miner是从venus这边出块，这个没有明白啥意思，和前面一句貌似不搭配，是另外一个需求？

**Comment by cloudxin** [comment]
可以理解为两个需求
1、开启出块功能迁移到数据库中；
2、venus-miner每个高度从数据库中，过滤出开启出块的miner进行赢票轮询。

**Comment by diwufeiwen** [comment]
这个在v1.7.0的 venus-auth只提供字段，mysql数据库可修改，完整的操作命令在签名重构版本提供

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus-auth/pull/107

**Comment by diwufeiwen** [comment]
venus-auth v1.8.0-rc2
