### ISSUE TITLE
[venus-market]水平部署模式下，dagstore缓存中间文件会被别的机器删除

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5441]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [x] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
最新版本
```

### 描述 / Describe the Bug

dagstore每次启动的时候会尝试清理下载的中间文件
但是在水平部署模式下，两个机器共享一个缓存存储的情况下，a机器重启会把b机器正在下载的文件清理掉。

### 日志 / Logging Information

```text
。
```

**Comment by diwufeiwen** [comment]
这个放到 #5451 下作为一个小项
