### ISSUE TITLE
[venus-auth] 鉴权失败后返回非空请求体

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5448]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
auth 1.18
```

### 描述 / Describe the Bug

当前版本的auth,鉴权失败之后会返回空的请求体,以及401 错误码
但是 jsonrpc client 接收到 response 之后 会直接 解码空的请求体,然后报解码出错,这会导致错误信息不明确

建议 返回错误状态码的同时,也返回一个非空 的http body

### 日志 / Logging Information

```text
2022-11-04T03:06:58.238Z        ERROR   chain-ro        cmd/main.go:76  CLI error: (error code -32700) unmarshaling response: EOF: error code -32700
```

**Comment by hunjixin** [comment]
jsonrpc中非200类型的返回值不应当进行unmarshal操作，不能保证非200类型返回值是个标准jsonrpc返回

**Comment by simlecode** [comment]
错误信息增加了 http status
