### ISSUE TITLE
[venus-market] HA optimization / 水平扩充优化

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5451]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

目前的venus-market水平扩充存在一些问题，
1. dagstore多机器模式下会删除其他机器的中间数据数据
2. 支持libp2p级别的负载均衡

**Comment by Fatman13** [comment]
1）多矿工配置，2）水平扩充，3）统一启动模式（脱离auth），这3个优先级是不是需要排一排？[doge]

**Comment by hunjixin** [comment]
1,3,2

**Comment by diwufeiwen** [comment]
待解决问题： 水平部署模式下，dagstore缓存中间文件会被别的机器删除

**Comment by hunjixin** [comment]
以后market的一个开发主题， 还要写一个类似chain-co的路由组件。

**Comment by Fatman13** [comment]
部分block，数据库等可以先思考。当前检索比较少，可以放一放？

**Comment by hunjixin** [comment]
- [ ] 水平部署模式下，dagstore缓存中间文件会被别的机器删除
- [ ] 重写fundmanager，目前fundmanager中设计到资金合并，保留资金这种操作。 考虑做一个简单资金管理， 简化这种精细化，自动加钱的的方式。 用户提前往market中抵押资金。 用的时候只检查资金够不够。 整体实现简单，用起来也比较高效。
- [ ] paychannel机制不明，需要看代码进行评估
- [ ] 需要一个类似于chain-co的负载均衡组件

**Comment by Fatman13** [comment]
这个好像当前需求不大？等 @elvin-du 大佬再看看咱们生态伙伴的需求？

**Comment by Fatman13** [comment]
参考：
- [ ] https://github.com/filecoin-project/lotus/pull/10895
