### ISSUE TITLE
[venus-market] `market` rework and redesign planning / `market`改造计划

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5453]
## Background / 背景

filecoin生态存储订单流程逐渐变得越来越重要的位置。为了更好的适应用户需求，支持使用场景。针对`venus-market`进行一系列的改造。

## Use cases / 支持场景

- 孵化器，订单加速器
- 企业级运维需求
- 企业级data-onboarding服务商
- Boost协议集成

## Design / 设计

- [x] https://github.com/filecoin-project/venus/discussions/5425
- [x] https://github.com/filecoin-project/venus-docs/pull/351
- [x] https://github.com/filecoin-project/venus/issues/5345

## Main Tasks / 核心任务（按优先级顺序）

- [x] https://github.com/filecoin-project/venus/issues/5410
- [x] https://github.com/filecoin-project/venus/issues/5498
- [ ] https://github.com/filecoin-project/venus/issues/5451

## Bug & Improvements P1

- [x] https://github.com/filecoin-project/venus/issues/5441
- [x] https://github.com/filecoin-project/venus/issues/5447
- [x] https://github.com/filecoin-project/venus/issues/5355
- [ ] https://github.com/filecoin-project/venus/issues/5261
- [ ] https://github.com/filecoin-project/venus/issues/5236
- [ ] https://github.com/filecoin-project/venus/issues/5126
- [x] https://github.com/filecoin-project/venus/issues/5021
- [x] https://github.com/filecoin-project/venus/issues/4952

## Bug & Improvement P2 (Q4)

- [ ] https://github.com/filecoin-project/venus/issues/5494
- [x] https://github.com/filecoin-project/venus/issues/5517
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/536

**Comment by hunjixin** [comment]
主要已完成
