### ISSUE TITLE
[venus接口文档] 是否有curl方式的api接口文档

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#5461]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [X] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [X] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [X] 文档 / docs

### 描述 / Description

一些关键性数据的远程调用及监控，需要venus提供一下相关的接口文档。例如:消息、赢标和订单等状态信息的数据。

**Comment by Fatman13** [comment]
一个初步的合集在这里，@cloudxin 看看够用吗？https://github.com/filecoin-project/venus/discussions/5450

**Comment by Fatman13** [comment]
指标应该就是通过一个ip+端口暴露出来，不知道curl访问的话，能不能保持一个长期读取的状态，不清楚和普罗米修斯读取的方式有没有不同。

**Comment by LinZexiao** [comment]
> 指标应该就是通过一个ip+端口暴露出来，不知道curl访问的话，能不能保持一个长期读取的状态，不清楚和普罗米修斯读取的方式有没有不同。

我觉得,metrics 接口里面返回的数据,一般是统计信息,如果希望获取具体详细的数据的话,可能就需要直接调用API接口了

**Comment by Fatman13** [comment]
> 我觉得,metrics 接口里面返回的数据,一般是统计信息,如果希望获取具体详细的数据的话,可能就需要直接调用API接口了

这种钱包余额也可以从指标里面来？

![image](https://user-images.githubusercontent.com/1591330/200999163-bbd3a8f4-3431-48c9-be15-85661d7a5aa0.png)

**Comment by LinZexiao** [comment]
> > 我觉得,metrics 接口里面返回的数据,一般是统计信息,如果希望获取具体详细的数据的话,可能就需要直接调用API接口了
> 
> 这种钱包余额也可以从指标里面来？
> 
> ![image](https://user-images.githubusercontent.com/1591330/200999163-bbd3a8f4-3431-48c9-be15-85661d7a5aa0.png)

@cloudxin

**Comment by LinZexiao** [comment]
https://venus.filecoin.io/advanced/chain-api-v0.html#account

**Comment by Fatman13** [comment]
66666！👍

例： https://venus.filecoin.io/zh/advanced/chain-api-v0.html#account

**Comment by YiRuiLiher** [comment]
缺少curl的信息，需要再完善一下

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus/issues/5560
