### ISSUE TITLE
[venus-messager] set GasOverEstimation not null after related issue is fixed  

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5467]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

message 数据层应该确保 GasOverEstimation 和 GasOverPremium 不为空
但是因为 gorm 自动迁移时,将精度和 not null 组合到一起就会有问题
等[关联issue](https://github.com/go-gorm/sqlite/issues/121)修复之后,再将 not null tag 加上
涉及数据结构 sqliteAddress , MsgMeta

**Comment by hunjixin** [comment]
直接使用sqlite的基础类型real不会有问题。

**Comment by LinZexiao** [comment]
> 直接使用sqlite的基础类型real不会有问题。

那是不是 也要改一下代码,另外 MySQL 那边也相应修改?
