### ISSUE TITLE
[chain-co] `lotus`多节点方案调研

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5497]
`Lotus`出了一个新的`Raft Consensus`，实现了多节点高可用的方案。是否需要调研一下？

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9294

**Comment by hunjixin** [comment]
用于协调多节点上nonce值的，对我们意义不大。 个人意见不做

**Comment by simlecode** [comment]
我们有venus-messager，可以不做

**Comment by Fatman13** [comment]
好德～
