### ISSUE TITLE
[venus] 导入快照后同步失败

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5501]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
v1.8.0
```

### 描述 / Describe the Bug

主网导入快照后同步失败
快照：https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_2347440_2022-11-18_00-00-00.car

### 日志 / Logging Information

```text
无
```

**Comment by YiRuiLiher** [comment]
✅
