### ISSUE TITLE
[venus-auth] 启动失败，1.9.x 版本

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5504]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
commit: 59c01fc715d6b471d0eb35727fe0c7c5ef90721a
```

### 描述 / Describe the Bug

2022/11/23 13:38:11 /Users/haoziyan/Desktop/code/github.com/filecoin-project/venus-auth/storage/mysql.go:505 Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key
[25.394ms] [rows:0] alter table `miners` drop primary key;
FATA[2022-11-23T13:38:11+08:00] Failed to init venus-auth: migrate store failed:migrate from store version:2 failed:Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key: Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key: migrate from store version:2 failed:Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key: Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key 

### 日志 / Logging Information

```text
无
```

### 重现步骤 / Repo Steps

1. 删除 `miners` 表 和 `store_versions` 表
2. 启动 venus-auth

**Comment by diwufeiwen** [comment]
仅有的自增列必须被定义为主键，在 ver <= 1.8.* 版本中主键是`miner` field,删除才可以重建

**Comment by hunjixin** [comment]
1.8.0 到1.9.0

**Comment by hunjixin** [comment]
测试： 
-  [ ] 完全新起venus-auth
-  [ ] 1.8版本到1.9版本
-  [ ] 能否回退， 如果不行可能要手动改表结构才能回退
