### ISSUE TITLE
[venus-auth] AuthClient接口可以不带token请求，存在安全隐患?

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#5507]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

func NewAuthClient(url string) (*AuthClient, error) {
	client := resty.New().
		SetHostURL(url).
		SetHeader("Accept", "application/json")
	return &AuthClient{cli: client}, nil
}

**Comment by hunjixin** [comment]
前面有个venus接口保护的issue了
