### ISSUE TITLE
[venus] chain/actor: expose address map / 重构，暴露address map？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5516]
关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9668

**Comment by Fatman13** [comment]
另外一个重构，可能有部分关联？
- [ ] https://github.com/filecoin-project/lotus/pull/9667

**Comment by simlecode** [comment]
已合并，在分支 feat/nv18-fevm
