### ISSUE TITLE
venus服务各组件配置文件目录建议统一

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5532]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

当前venus各组件配置文件目录命名方式不统一，虽然不影响程序运行，但是不方便管理和维护，也不够美观，建议尽量统一。
比如，现在云上组件配置文件目录名称为：
.venus-auth
.venusmarket
.venus-messager
.venusminer
.venus_wallet
.marketclient
.venusgateway
建议：全部统一成.venus-auth这种命名方式，前面'venus'表示属于venus业务组件，后面'auth'为组件名称，中间用短横线连接

**Comment by Fatman13** [comment]
和#5528重复，可以关注#5528。
