### ISSUE TITLE
[venus] venus connect all peer for storage power measurement / 增加`venus`链接更多`peer`统计`agent`功能？

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5536]
## 背景

- [ ] https://github.com/filecoin-project/venus/discussions/5452

## 结果

- [ ] https://github.com/filecoin-project/venus/discussions/5452#discussioncomment-4310524

当前默认链接210个peer的情况下，统计不到venus agent的节点。~~是否考虑程序上提供命令？~~

或者[修改](https://github.com/filecoin-project/venus/issues/5536#issuecomment-1336874252)lotus的配置？

**Comment by Fatman13** [comment]
CC @simlecode

**Comment by Fatman13** [comment]
peer数量配置修改：
- [ ] [Slack](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1670137759176709)

**Comment by Fatman13** [comment]
需要看看社区里面有没有人能够连到更多的peer？

**Comment by simlecode** [comment]
试了下调大最大连接数，但没啥效果，其它节点连接到的peer过多时，会对连接的peer进行裁剪和关闭连接

**Comment by simlecode** [comment]
[peer_info.log](https://github.com/filecoin-project/venus/files/10159730/peer_info.log)

**Comment by Fatman13** [comment]
为啥@reiers可以连到2700个peer。。😂

![image](https://user-images.githubusercontent.com/1591330/205792276-0c572f27-fbb7-4435-b3d9-8ebc13346a14.png)

**Comment by Fatman13** [comment]
[厉害](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1670293224612029?thread_ts=1670137759.176709&cid=CPFTWMY7N)了。。

**Comment by Fatman13** [comment]
先关掉了。
