### ISSUE TITLE
[venus*] add namespace and curl example in jsonrpc example / 在jsonrpc文档中增加方法的namespace和curl命令案例

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5560]
### 链服务模块 / Chain Service Components

- [x] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [X] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

- [ ] 因为venus中存在不同的namespace类型，所以生成的方法名中可能需要说明namespace是什么
- [ ] 增加curl例子，方便不了解jsonrpc的人使用

**Comment by diwufeiwen** [comment]
(1) 应该是一个文档中所有的接口都是一个namespace，没必要每个方法都说明，在文档最开头指明？
(2) curl也没必要每一个方法都说明，在文档开头加个规则：
// ./venus-shared/api/messager/method.md
```bash
# Groups

namespace = "Filecoin"
ip = ""
port = 3453
token = ""
method = 

# <Inputs> corresponding to the value of `Inputs` Tag of each API
curl http://$ip:$port/rpc/v0 -X POST -H "Content-Type: application/json"  -H "Authorization: Bearer $token"  -d '{"method": "Filecoin.ActiveAddress","params":<Inputs>, "id": 0}'
```
这样如何
