### ISSUE TITLE
[venus*] unify cloud servier export / 统一云服务出口

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5561]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [X] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

market，cluster迁移到线下后。 为了简化线下的部署，云上目前的node服务出口配置， messager出口配置， gateway出口配置，全部通过一个负载均衡出去， 负载均衡通过配置header进行路由到各自服务的内网负载上。

优势：
1. 线下组件只需要指定一个ipendpoint和token即可
2. 简化配置链接多个gatway实例的，代码，配置增加了复杂度。

阻碍：
1. 对于客户端 目前gateway支持部署多个， 线上组建（miner）链接多个gateway， 线下组件链接多个gateway。 因为以前为了支持在双云之间互相切换， 但是现在已经不存在这种部署方案， 在一个客户端链接一个云中的两个gateway不具备实际的价值（如果网络存在问题，大概率两个gateway都是坏的）。   

2. 对于服务端 gateway不同于其他服务的地方在于， gateway本身即是有状态的， 客户端和gateway建立连接后，链接本身就是一种状态，链接携带的信息又是另一种状态。 比如venus-wallet A以账号m携带pk1，pk2 注册到gateway A， vennus-wallet B以账号m携带pk3，pk4注册到gateway B。 这样m账号支持pk1，pk2，pk3，pk4签名， 但是pk1，pk2必须到gatewayA发送请求， pk3，pk4必须到gatewayB发送请求。因而在服务端在目前的结构下是无法直接通过负载均衡为云组建提供服务（客户端因为是被动的，所以不受这个因素的影响）。 目前的做法是在miner和messager中存在一个根据地址来选择的过程。这种做法是当时的一个妥协策略，这种做法事实上造成gateway的服务不完备，影响gateway不能成为一个完善的服务。

解决办法：
分布式方式： gatway之间互相协调，采用gossip各自广播自己的数据信息。 每个gateway节点维护了所有节点的信息，gateway获取到信息后先看本地能不能下发请求，如果不行本身作为一个跳板，请求其他gateway，通过其他gateway下发信息。可能响应会慢，但是效果应当是比较好的。

中心调度： 所有gateway向一个调度器发送信息，调度器维护各种信息， gateway本身蜕化成 每次信息变化时同样向调度器更新信息。所有的任务首先发送到调度器，在通过调度器发送到对应的gateway链接。部署会相对复杂。

采用消息队列：但是由于客户端消费能力各有不同，topic的设计会比较复杂。比如钱包A支持账号b,c,d签pk1，pk2，pk3. 那么这里的topic可能就要设计成b-pk1, b-pk2, b-pk3,....d-pk3, topic会比较膨胀。还需要更近一步的研究。

**Comment by Fatman13** [comment]
这个也可以考虑作为版本目标？CC @elvin-du
