### ISSUE TITLE
[venus-messager] short for verbose / 简化-verbose为 -v

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5568]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

./venus-messager msg list -verbose  
简化成
./venus-messager msg list -v

**Comment by YiRuiLiher** [comment]
✅
