### ISSUE TITLE
[venus-market] not change local token when reboot venus-market / venus-market重启时不改变本地token

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5570]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

venus-market本地部署后由于不在链接venus-auth， 因此需要保持本地token不变， 重启时保持本地token不变。

**Comment by YiRuiLiher** [comment]
pass
