### ISSUE TITLE
Try chain-co with lotus failure

### ISSUE THREAD

**Issue by joyceqingling** [filecoin-project/venus#5576]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [X] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [X] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
repo: https://github.com/ipfs-force-community/lotus
branch: v1.11.2_incubation
```

### 描述 / Describe the Bug

I want try chain-co with lotus, following the document:https://venus.filecoin.io/zh/operation/#%E9%83%A8%E7%BD%B2%E8%8A%82%E7%82%B9.

Errors occurs when building lotus. Below is the logs.

And does branch v1.11.2_incubation support network shark?

### 日志 / Logging Information

```text
make[1]: Leaving directory '/tank1/joyce/lotus/extern/filecoin-ffi'
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.fc720313c" -o lotus ./cmd/lotus
# github.com/lucas-clemente/quic-go/internal/qtls
/root/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.21.2/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
Makefile:92: recipe for target 'lotus' failed
```

### 重现步骤 / Repo Steps

git clone https://github.com/ipfs-force-community/lotus.git
git checkout v1.11.2_incubation
make calibnet

**Comment by Fatman13** [comment]
> git checkout v1.11.2_incubation

@simlecode @hunjixin 这个是不是用最新的ipfsforce的lotus release版本就可以了？

**Comment by simlecode** [comment]
对，用 venus/v1.18.0

**Comment by Fatman13** [comment]
@joyceqingling 可以试试这个版本 `venus/v1.18.0`。

**Comment by hunjixin** [comment]
close this issue, welcome reopen if have any problem
