### ISSUE TITLE
[venus-auth]  IAuthClient interface refactor / IAuthClient interface 拆解成各自组件调用的接口 

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#5579]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

 IAuthClient interface 包含了各种类型的接口，但是venus-messager、venus-gateway及venus-miner不需要都调用，只需要其中的部分接口，这样在写IAuthClient mock时比较烦，要实现不需要的接口。
为什么不在auth里实现一个mock呢？因为每个组件mock的功能点不一样

**Comment by LinZexiao** [comment]
现在 1.10.0 版本的分支中已经有 IAuthClient 的 [mock](https://github.com/filecoin-project/venus-auth/blob/dev/v1.10.0/jwtclient/mocks/mock_auth_client.go)
