### ISSUE TITLE
[dev-prod] Product release optimization / 发版流程优化

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5581]

**Comment by simlecode** [comment]
## 开发分支

开发分支指形如 `dev/vX.Y.Z` 的分支

### 开发分支格式

1. 常规情况

`dev/vX.Y.Z`，例：`dev/v1.9.0`

2. venus 网络升级

* 非网络升级代码合并到开发分支
* 网络升级相关代码合并到类似 `feat/nv18` 或者 `feat/nv18-fevm` 的分支，等代码合并完成后合入到 `master`

### 开发分支创建

根据milestones的计划来创建开发分支，开发分支从上一个稳定版本切出来，若上一个版本还未发布稳定版本，
则从上一个版本的rc版本切出来，若上个版本还未发布rc版本，则从上上个版本稳定版本切出来。

### 开发分支合入master

1. 待上一个版本的稳定版本发布后，当前版本开发分支可以合入`master`，通过`merge master`的方式来解决与`master`上的冲突
2. 当前版本开发分支合入`master`后，后续当前版本的`pr`都往`master`合并
3. 当前版本发布`rc`版本后，只能往`master`合入当前版本的修复代码和版本更新代码（社区发起`pr`除外）

### 一个pr需要合并到多个开发分支

1. 把该`pr`合并到一个开发分支
2. 通过`cherry-pick`方式把该`pr`合并到其它的开发分支

## 版本发布

### 常规版本

* 升级依赖
* 更新changelog
* 更新版本号
* 在`master`分支发布版本

### bug修复版本

若同一bug包含在多个稳定版本中，则根据下面`1-4`的步骤逐个发布bug修复版本

1. 从稳定版本切出`release/vX.Y.Z`分支
2. 把修复代码合入`release/vX.Y.Z`分支
3. 更新changelog和版本号
4. 在`release/vX.Y.Z`分支发布版本
5. 把修复代码`cherry-pick`到`master`分支

**Comment by Fatman13** [comment]
66666 拜读一下。👍

**Comment by diwufeiwen** [comment]
版本号和changelog是先提交pr合并到master分支,还是先切出release/***然后提交到release分支（如果是2，后面还要合并回master分支吗）

**Comment by diwufeiwen** [comment]
在现在多个开发版本进行时，假如dev/v1.10.0和dev/v1.11.0，这两个分支最初都是从v1.9.*的稳定版本切出来吗

**Comment by simlecode** [comment]
> 版本号和changelog是先提交pr合并到master分支,还是先切出release/***然后提交到release分支（如果是2，后面还要合并回master分支吗）

发第一个rc版本的时候是版本号和changelog是先提交pr合并到master分支，再切出release/***分支，后续的rc版本和稳定版本是直接提交到release/***分支
venus 网络升级在发布稳定版本后要合回master，其他的目前不打算合回master

**Comment by 0x5459** [comment]
> 一个版本只建一个release分支，v1.8.x版本只会建release/v1.8.0分支，不会在发布版本v1.8.1时建release/v1.8.1分支，v1.8.1版本的修改都合入到release/v1.8.0分支，并从release/v1.8.0分支发布版本

分支名称为 `release/v1.8` 或者 `release/v1.8.*` 是不是更好？

**Comment by simlecode** [comment]
> 在现在多个开发版本进行时，假如dev/v1.10.0和dev/v1.11.0，这两个分支最初都是从v1.9.*或v1.8.*的稳定版本切出来吗

现在是直接从master切出来的，打算这样做（后续合并可能冲突多）

**Comment by Fatman13** [comment]
先试运行，再迭代？

cluster目前除了dev分支，基本按照这个规则执行。

**Comment by Fatman13** [comment]
合并到 dev-guidance

**Comment by diwufeiwen** [comment]
发布稳定版本后需要修改，先把代码合入到 master       ---->  这里是怎么合并，直接从release分支建立pr吗，这种会存在有冲突的问题，那就是，先从release分支切出临时分支，解决冲突，在pr到master分支？
![image](https://user-images.githubusercontent.com/40375298/224929754-2bd6e663-9ffc-489b-9bb2-b3608bb8decb.png)

**Comment by simlecode** [comment]
> 发布第一个稳定版本后需要把代码合入到 master ----> 这里是怎么合并，直接从release分支建立pr吗，这种会存在有冲突的问题，那就是，先从release分支切出临时分支，解决冲突，在pr到master分支？

我是先从 release 分支切出临时分支，把 master merge 到临时分支，解决冲突后合到 master
