### ISSUE TITLE
[venus-messager] adjust default gas settings / 调整默认gas参数

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5591]
调整默认gas参数值，方便新人直接能够默认gas参数，能够消息上链？

CC @cloudxin，好像上次提到过一次？

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/issues/5546

**Comment by diwufeiwen** [comment]
这关联pr不是已经关了吗，另外上面已经有个gas相关的issue，这个关闭了。
对于调整默认值，多宝的意见是lotus默认也是那个值，限制于base的变化，默认多少都不会很合适
