### ISSUE TITLE
[venus-message]建议优化负载均衡情况下手动切换推消息节点

### ISSUE THREAD

**Issue by YiRuiLiher** [filecoin-project/venus#5613]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
1.9.0-rc1
```

### 描述 / Describe the Bug

1. 当message在负载均衡的情况下只能设置一个主推消息的节点
2. 当推消息的节点损坏时需要手动修改接受消息的节点，然后重启
3. 这种方式并不能完全算负载容灾，一旦出问题非常依赖运维反应速度
4. 建议后续改成自动选择推消息的节点，当一个节点损坏时自动切换到另一个

### 日志 / Logging Information

```text
如上所诉
```

**Comment by hunjixin** [comment]
这个问题谛听在的时候讨论过， 否了

**Comment by hunjixin** [comment]
探测，协调的时间可能都足够维护人员手动切换了。

**Comment by YiRuiLiher** [comment]
维持现有配置需要做的事情：
1. 所有的运维都要掌握这种方式
2. 在几个月之后的某次紧急情况下还能想到这个操作

这似乎是给自己设置了个炸弹，在不知道的某天自己就会踩到，1.9.0修改了消息推送开关的配置方式，开关逻辑更加复杂，很难保证运维都能掌握，并且关键时刻还能记得这块的逻辑

即便是不修改代码，也希望能有一些相关的提示或者某些方式能够避免踩雷，比如不断的打印 WARN日志提示消息推送已经关闭

**Comment by hunjixin** [comment]
有的配置字段是可以考虑进行一些合并。或者直接使用默认值。一个配置中真正需要改的也没多少。至于几个月后忘记了这种事就没什么办法了。

**Comment by YiRuiLiher** [comment]
尽量加些引导，避开没有任何提示又靠记忆力的东西
