### ISSUE TITLE
[venus-message]多node配置方式优化建议（配置体验）

### ISSUE THREAD

**Issue by YiRuiLiher** [filecoin-project/venus#5617]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus message version 1.9.0-rc1+git.372f829
```

### 描述 / Describe the Bug

1. 在这个版本中引入 node 命令管理节点
2. gateway是配置文件中数组的方式进行管理

多种方式会造成部分功能非必要不会使用的情况

尽量统一配置，降低复杂度

### 日志 / Logging Information

```text
略
```

**Comment by Fatman13** [comment]
是得需要统一一下。建议都改成通过配置文件来？

**Comment by elvin-du** [comment]
统一改成写到配置文件
