### ISSUE TITLE
[ssm] add cmd to set beneficiary / 增加设置 beneficiary 的命令

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5642]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

增加设置 beneficiary 的命令

**Comment by Fatman13** [comment]
66666，lotus也从miner里面把这一块移出来了。他们把受益人地址相关放到了lotus-shed里面。

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10037
