### ISSUE TITLE
[venus-market] opt slow sql / 慢查询优化

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5645]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

SELECT * FROM `storage_deals` WHERE cdp_provider = '0522948' AND state IN (7)
当该表数据较多时该sql执行比较耗时(参考:扫描1k行需要3~10秒),建议添加个联合索引:
ALTER TABLE `venus_market`.`storage_deals` ADD INDEX `idx_cdpprovider_state` (`cdp_provider`, `state`)

**Comment by simlecode** [comment]
给 `storage_deals` 表增加索引：`CREATE INDEX idx_cdpprovider_state ON storage_deals(cdp_provider,state)`
