### ISSUE TITLE
[venus-cluster] failed to extend new sector in renew command / renew续期命令中包含新版本扇区时会发生错误

### ISSUE THREAD

**Issue by caijian76** [filecoin-project/venus#5684]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [X] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus message version 1.8.0+git.a1b2601

venus-sector-manager version v0.5.0-beta3-prod-git.7f215b3
```

### 描述 / Describe the Bug

续期节点扇区，采用如下命令：
 venus-sector-manager util sealer sectors renew --miner xxxxx   --from aaaa --to bbbb  --new-expiration cccc --really-do-it
 如果扇区匹配数量太多，或者扇区中含有订单数据，有概率消息签名失败：
 消息处理的错误为
 gas estimate: estimating gas limit: message execution failed: exit 18, reason: message failed with backtrace:
00: f0xxxxxx (method 8) -- cannot use legacy sector extension for simple qa power with deal weight 54233 (18)
 (RetCode=18)  
 
 如果通过修改--from --to参数，减少匹配的扇区数量，则消息签名上链成功。

### 日志 / Logging Information

```text
none
```

**Comment by hunjixin** [comment]
extend方法中，如果混合了新的有真实数据的扇区，会报这个错误。

需要看一下extend2方法，看看是否需要一个新的命令用新的方法来延长扇区生命周期。

**Comment by Fatman13** [comment]
CC @0x5459

**Comment by caijian76** [comment]
实际上，如果一次续期的扇区数较少，2000左右，就可以成功续期（包括了含有deal的扇区）。

**Comment by caijian76** [comment]
实际上，如果一次续期的扇区数较少，2000左右，就可以成功续期（包括了含有deal的扇区）。

**Comment by 0x5459** [comment]
> 实际上，如果一次续期的扇区数较少，2000左右，就可以成功续期（包括了含有deal的扇区）。所以应该还不是新旧扇区的问题，应该还是gas类的问题。


> 实际上，如果一次续期的扇区数较少，2000左右，就可以成功续期（包括了含有deal的扇区）。

非常好的反馈！ 感谢！

**Comment by 0x5459** [comment]
tranfer to https://github.com/ipfs-force-community/venus-cluster/issues/636
