### ISSUE TITLE
[venus-auth] secret config is useless / 配置中的 secret 已经失去作用了

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5697]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

原本用于 token 生成,现在每个 token 都会有对应的 secret ,全局的 secret 已经不需要了

**Comment by hunjixin** [comment]
@LinZexiao 结论是可以删除吗
