### ISSUE TITLE
[venus-worker]当配置多台永久存储时优化建议

### ISSUE THREAD

**Issue by kunyaokeji** [filecoin-project/venus#5699]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [X] venus-worker
- [ ] 文档 / docs

### 描述 / Description

问题描述:当前venus-worker配置文件attached中如果配置了多台永久存储,只有当存储空间不足扇区大小2倍的情况下才会切换,预留的空间较小,如果有多台venus-worker同时工作,则有可能会写爆存储服务器导致任务报错

建议:切换的条件修改为可配置方式,比如在attached中增加一条配置下disk_left="1TiB",当检查到磁盘空间不足1T的时候就不再使用该存储

**Comment by 0x5459** [comment]
当前 venus-cluster 的设计是：每个 worker 在需要写入永久存储前都会先向 vsm 申请预留扇区大小两倍的容量，vsm 会记录这些数据，在封装任务完成后 vsm 释放多申请的空间。vsm 也提供了 `storage release-reserved` 命令手动释放空间。在这种设计下多台 venus-worker 同时工作是不会写满存储服务器导致任务报错的。
所以暂时是不需要新增配置。
