### ISSUE TITLE
[venus-market] venus-market检索优化汇总

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5720]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

针对目前filplus更强烈高频的检索需求， 需要针对venus-marke进行一些优化

1. 增加cancelbyinitor，根据发送方peerid批量终止
2. deal list 优化， 自动屏蔽一些失败的的订单， 进行分页显示， 按一定的条件（比如发送方peerid）进行获取
3. 增加显示单个存储和检索订单的接口，使用两列table显示内容

| name      | value |
| ----------- | ----------- |
| dealid      | 123       |
| data root   | xxxx        |

需要验证的内容：
1. 检索传输阈值设置是否生效

**Comment by kunyaokeji** [comment]
问题描述:客户端发起较多检索后,venus-market可能出现占用系统资源较多、卡住情况,需要有一个手段,允许手动结束掉部分检索任务

建议:
1、能够指定客户端peerid结束检索任务;
2、能够指定检索文件的Root Cid结束检索任务;

**Comment by hunjixin** [comment]
已经独立建issue了
