### ISSUE TITLE
[venus] 无法获取扇区的开始和过期时间

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#5756]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus -v
{
	"Version": "1.9.0+git.f17611ee1"
}
```

### 描述 / Describe the Bug

**venus state sector f0694928  4700487**
```
SectorNumber:  4700487
SealProof:  9
SealedCID:  bagboea4b5abcbqo5nz3evkiflryz6ecg4ttvz57rfoqwp47vajxjzfvmke25jrj7
DealIDs:  []

Activation:  1149537 (0 seconds ago)
Expiration:  3399951 (in 0 seconds)

DealWeight:  0
VerifiedDealWeight:  0
InitialPledge:  0.30518241913628333 FIL
ExpectedDayReward:  0.001759925835610332 FIL
ExpectedStoragePledge:  0.033475111194868978 FIL

Deadline:  21
Partition:  1
```

其中的**Activation**和**Expiration**转换时间为0是错误

### 日志 / Logging Information

```text
null
```

**Comment by BaiYuTest** [comment]
在v1.10.1版本验证通过：
./venus -v
"Version": "1.10.1+git.6b723d81b"

./venus state sector f04079 160
SectorNumber:  160
SealProof:  8
SealedCID:  bagboea4b5abca7uojfsbkjga2uypz4q4tznnoegbmbycpawqwm443shdkgssgokn
DealIDs:  [33746]

Activation:  329543 (24 Feb 23 12:24 CST, 2 weeks 4 days ago)
Expiration:  1820892 (26 Jul 24 08:19 CST, in 1 year 19 weeks)

DealWeight:  390948192256
VerifiedDealWeight:  0
InitialPledge:  0.99999998430674944 FIL
ExpectedDayReward:  2.418025816300212062 FIL
ExpectedStoragePledge:  48.804337859534356991 FIL

Deadline:  1
Partition:  0
