### ISSUE TITLE
[venus-market] 根据条件取消检索订单（订单和传输） / cancel retrieval deals and datatransfer by condition

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5766]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

问题描述:客户端发起较多检索后,venus-market可能出现占用系统资源较多、卡住情况,需要有一个手段,允许手动结束掉部分检索任务

建议:
1、能够指定客户端peerid结束检索任务;
2、能够指定检索文件的Root Cid结束检索任务;

**Comment by simlecode** [comment]
新增命令：`./venus-market data-transfers batch-cancel`
