### ISSUE TITLE
[venus-market] opt deal list command / 订单查询优化 

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5767]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

现在生产存储检索订单非常多，需要根据实际情况对订单查询进行优化。

1. deal list 优化， 自动屏蔽一些失败的的订单， 进行分页显示， 按一定的条件（比如发送方peerid）进行获取
2. 增加deal list条件查询 具体需要哪些条件可以根据生产场景来

**Comment by simlecode** [comment]
### 增加两个新的命令行：
* 输出存储订单的所有状态：`./venus-market storage deal states`
* 输出检索订单的所有状态：`./venus-market retrieval deal statuses`

### 调整存储订单和检索订单 list 命令

主要是增加了按条件过滤和分页
