### ISSUE TITLE
[venus-market] 增加获取单一订单显示详情的功能 / add command to query single deal

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5768]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

订单字段太多， list table很难显示的全， 增加一个接口和command用来显示某个订单的详细信息

增加显示单个存储和检索订单的接口，使用两列table显示内容

| name      | value |
| ----------- | ----------- |
| dealid      | 123       |
| data root   | xxxx        |

**Comment by simlecode** [comment]
增加两个命令行：`./venus-market retrieval deal get` `./venus-market storage deal get`
