### ISSUE TITLE
[venus-market] deal filter not properly called / deal filter 接单时没有被触发

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5784]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
带 deal filter 的版本。
```

### 描述 / Describe the Bug

背景：https://github.com/filecoin-project/venus/issues/5669

当 filter 配置了命令之后，market 接到订单之后，并没有执行 filter 中配置的命令。

### 日志 / Logging Information

```text
略。。。
```

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus/issues/5669

**Comment by LinZexiao** [comment]
值得注意的是:

1. 存在 公共配置和 矿工单独配置 两种方案
2. 如果 矿工没有任何独立配置, 就会直接使用共同配置
3. 如果 矿工独立配置了某些项, 就应该其他配置项会只用空值

所以,目前的情况来说, 矿工的配置有两种选择, 要么直接使用共同配置, 要么独立配置所有配置项
