### ISSUE TITLE
[droplet] add cmd to manage miner / 增加管理miner 的命令

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5790]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

现在 market 新增 miner 只能通过修改配置文件来添加,稍有不便
考虑增加 管理miner 的命令行工具
或者重新考虑通过 auth 同步 miner

**Comment by diwufeiwen** [comment]
已经有一个issue，重复的？

**Comment by diwufeiwen** [comment]
#5783
