### ISSUE TITLE
[venus*] repo migration / 迁移 repo

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5808]
## 背景

- [ ] https://github.com/filecoin-project/venus/issues/5760

**Comment by Fatman13** [comment]
在 ipfsforce 组织中，创建了新的 `Venus Team Project(s)` 的 github project。测试了一下，能够囊括智子，执剑人，水滴各项目的 issue，misletone，都没有问题。

- [ ] https://github.com/orgs/ipfs-force-community/projects/9/views/5

**Comment by elvin-du** [comment]
> 添加 venus-core-devs 作为以后 sprint 或者其他 core-dev 用途的仓库。
> 
> * [ ]  https://github.com/ipfs-force-community/venus-core-devs

以后的括智子，执剑人，水滴的issue都提交在这个repo里面吗？还是继续在venus repo 里面？

**Comment by elvin-du** [comment]
> 在 ipfsforce 组织中，创建了新的 `Venus Team Project(s)` 的 github project。测试了一下，能够囊括智子，执剑人，水滴各项目的 issue，misletone，都没有问题。
> 
> * [ ]  https://github.com/orgs/ipfs-force-community/projects/9/views/5

project好像只能管理一个组织下的repo，看来我们只能同时进行两个project的管理了对吧

**Comment by Fatman13** [comment]
> 以后智子，执剑人，水滴的issue都提交在这个repo里面吗？还是继续在venus repo 里面？

每个产品的 issue 到时候提到各自自己的 repo，总体各产品的 issue 都可以集合到 venus team project(s) 这个大面板里面。sprint 可以在这个大面板里面整体维护。只有 sprint issue 在 venus-core-devs。

**Comment by Fatman13** [comment]
> project好像只能管理一个组织下的repo，看来我们只能同时进行两个project的管理了对吧

对，除了 venus 和 venus-wallet 其他都能管。

**Comment by Fatman13** [comment]
已联系 filecoin-project owners 待他们答复。

**Comment by Fatman13** [comment]
J 已经帮忙完成 repo 迁移，可以进一步推进这个 issue。

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/issues/5760

**Comment by hunjixin** [comment]
repo迁移过程 数据目录原则上兼容两个目录一个大版本， 下个大版本已出（或者持续多个）。 最后需要给出一个迁移的注意事项和流程

**Comment by LinZexiao** [comment]
编译之后的可执行文件, 统一输出到  ./dist/ 下面

**Comment by Fatman13** [comment]
完成！
