### ISSUE TITLE
[venus] eth optimization / eth 优化合集

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5812]
看看需不需要？lotus那边都直接合到master里面了。

关联 [03/20](https://github.com/filecoin-project/venus/discussions/5769#discussioncomment-5364184)：

- [x] https://github.com/filecoin-project/lotus/pull/10495
- [x] https://github.com/filecoin-project/lotus/pull/10485
- [ ] ~~https://github.com/filecoin-project/lotus/pull/10474~~
- [x] https://github.com/filecoin-project/lotus/pull/10467
- [ ] ~~https://github.com/filecoin-project/lotus/pull/10464~~
- [ ] ~~https://github.com/filecoin-project/lotus/pull/10461~~
- [x] https://github.com/filecoin-project/lotus/pull/10460
- [x] https://github.com/filecoin-project/lotus/pull/10456

关联：
- [x] https://github.com/filecoin-project/lotus/pull/10446
- [ ] https://github.com/filecoin-project/lotus/pull/10445
- [x] https://github.com/filecoin-project/lotus/pull/10443
- [x] https://github.com/filecoin-project/lotus/pull/10440
- [x] https://github.com/filecoin-project/lotus/pull/10427
- [x] https://github.com/filecoin-project/lotus/pull/10419
- [x] https://github.com/filecoin-project/lotus/pull/10413
- [x] https://github.com/filecoin-project/lotus/pull/10411
- [x] https://github.com/filecoin-project/lotus/pull/10409
- [ ] ~~https://github.com/filecoin-project/lotus/pull/10389~~
- [ ] ~~https://github.com/filecoin-project/lotus/pull/10380~~

**Comment by simlecode** [comment]
10389 和 10380 不需要，其他都要

**Comment by Fatman13** [comment]
CC @simlecode 3月20号更新更多的 eth API 相关的优化。
