### ISSUE TITLE
[venus] ffi validation parallelism / ffi 验证平行计算

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5838]
可能会对链同步有一定帮助？平行验证 fvm 的一些东西。

![image](https://user-images.githubusercontent.com/1591330/226256520-4f50022b-8d86-4a62-8088-a320548eb43b.png)

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10480
- [ ] https://filecoinproject.slack.com/archives/C027TQMUVJN/p1679080889058639（Slack）

**Comment by simlecode** [comment]
试了下，没有明显提升
