### ISSUE TITLE
[venus] applyBlock metrics / ApplyBlock 时间&Gas指标

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5841]
之前 venus 是不是没有指标？这个指标感觉能比较好的评估节点验证的效率？

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10470

**Comment by elvin-du** [comment]
后面会做一个完备的监控方案。

**Comment by elvin-du** [comment]
我们会增加更多metrics，具体请参考 https://github.com/filecoin-project/venus/issues/6051

**Comment by LendvaiPista** [comment]
5841
