### ISSUE TITLE
[venus-messager] gas_fee_cap fields in address turned max_fee_cap  / 地址表的gas_fee_cap 字段变成了max_fee_cap

### ISSUE THREAD

**Issue by BaiYuTest** [filecoin-project/venus#5844]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus message version 1.10.1+git.9dda702
```

### 描述 / Describe the Bug

venus-messager组件 数据库addresses 表gas_fee_cap 字段变成了max_fee_cap

### 日志 / Logging Information

```text
无
```

**Comment by elvin-du** [comment]
关闭的原因是？无法复现还是？

**Comment by simlecode** [comment]
查了下 max_fee_cap 是很久之前的字段，gas_fee_cap 字段最近几个版本没有变化
