### ISSUE TITLE
[venus-market]dagstore中检索错误的信息需要能删除

### ISSUE THREAD

**Issue by waleyhi** [filecoin-project/venus#5854]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [X] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

![image](https://user-images.githubusercontent.com/57161619/226855803-71dab6f7-d7e2-490c-83b0-131df0efa6c8.png)
./venus-market dagstore list-shards中检索错误的信息无法删除,越积越多

**Comment by simlecode** [comment]
新增命令：`./venus-market dagstore destroy-shard`
