### ISSUE TITLE
[chain-co] Error `ipld: could not found xxxxxx` occurred

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5860]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
v1.10.0
```

### 描述 / Describe the Bug

![image](https://user-images.githubusercontent.com/69969590/227429388-52fec110-a4bf-4709-8b81-9be247958912.png)

### 日志 / Logging Information

```text
.
```

**Comment by simlecode** [comment]
https://github.com/ipfs-force-community/venus-cluster/issues/678

**Comment by elvin-du** [comment]
还是经常出现lpld找不到的错误。

**Comment by simlecode** [comment]
长时间未出现

**Comment by elvin-du** [comment]
sophon-co已经对入参是tipsetkey的请求，首先根据node是否包含这个tsk，然后返回了响应的node。应该不会再出现收到了chainnotify，但是获取tipset却得不到，从而出现 lpld：could not found的错误。
