### ISSUE TITLE
[Ecosystem] integrate with collectif DAO SDK / 探索集成 collectif DAO SDK

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5874]
与 collectif DAO 团队接触了一下。collectif DAO staking 产品[概要](https://docs.collectif.finance/)。从了解的情况来看，collectif DAO 的 staking 平台，设计上偏去中心化。为了更自动化，capital efficient 的从 staking pool 中收到质押，需要与协议，挖矿客户端的深度集成。这里可以探索下与其 [SDK](https://github.com/collective-dao/collectif-go-sdk) 集成的可能性。

**Comment by elvin-du** [comment]
通过FEVM上面执行智能合约已经可以获取SP的QAP算力了，不需要进行客户端级别的修改，就可以完成这个功能。

**Comment by Fatman13** [comment]
> 通过FEVM上面执行智能合约已经可以获取SP的QAP算力了，不需要进行客户端级别的修改，就可以完成这个功能。

他这个是以扇区为粒度，会更精细化一些。

**Comment by Fatman13** [comment]
搬迁至 https://github.com/ipfs-force-community/venus-core-devs/issues/13
