### ISSUE TITLE
[venus] snapshot index perf opt / snapshot index 优化

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5880]
关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10556

**Comment by elvin-du** [comment]
10556 依赖 https://github.com/filecoin-project/lotus/pull/10452。代码好多啊

**Comment by elvin-du** [comment]
lotus用的是sqlite，所以需要单独加index，而venus没有用sqlite，只用了一个badger的k/v数据库，k/v数据库是不需要专门加索引的。
