### ISSUE TITLE
[docs] update document / 更新文档（nv19）

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5905]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [x] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

`venus-auth` 在 `v1.10` 版本之后访问需要携带 token，所以所有会访问 `venus-auth` 的组件都需要加上 auth token，文档也需要相应的更新

**Comment by Fatman13** [comment]
确实社区里面最近有这个问题。👍
