### ISSUE TITLE
[venus] consensus: validate block within range / 共识：验证区块进来的时间

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5931]
@diwufeiwen 大佬，这个是不是就是你之前说的，直接协议里面验证后来的区块，直接否定掉？

关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10691

> This will reject blocks in pubsub validation if they're either:

> - Too far into the future (5 blocks beyond the expected head).
> - Too far into the past (before finality).

> Specifically:

> - We were previously rejecting future blocks in the sync logic, but not in pubsub itself.
> - We never used to check if a block was too old.

> Motivation: Blocks that are too new/too old can cause us to perform quite a bit of unnecessary work.

> We should carefully consider that second check as we may need to tweak it (e.g., to handle network issues?). We may want to base this check on the latest synced head, not the expected epoch.

**Comment by diwufeiwen** [comment]
不是，这个是在同步模块的pubsub（libp2p）层检查排除来自未来的或者太过落后于当前head的区块。修改前的逻辑，假设一个区块来自未来，在libp2p收到区块不会验证，进入同步逻辑时才验证，修改后收到广播的区块就会就行前面说的两个验证。

**Comment by diwufeiwen** [comment]
venus的同步逻辑不一样，无需引入
