### ISSUE TITLE
[droplet] retrieval http research / 调研检索 http 协议

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5965]
根据 [Slack](https://filecoinproject.slack.com/archives/C04Q63M929Z/p1683825880059939?thread_ts=1683788012.522799&cid=C04Q63M929Z) 中 Hannah 提到的 http 协议，进行调研。看看集成的难度。

- [ ] https://github.com/ipfs/specs/pull/402

**Comment by Fatman13** [comment]
> 单独的 `boost` 检索实现了 `graph sync`。
> http 检索需要启动一个叫 `booster-http` 的辅助程序，用户请求 `booster-http`，然后 `booster-http` 根据 `piececid` 调用 `boost` 接口找 `pieceinfo`，再根据 `pieceinfo` 调用矿工接口获取数据。
bitswap 检索需要启动一个叫 `booster-bitswap` 的辅助程序，用户请求 `booster-bitswap`，然后 `booster-bitswap` 再调用 `boost` 接口获取数据。

**Comment by elvin-du** [comment]
https://github.com/ipfs-force-community/droplet/issues/336

已完成支持http检索功能。
