### ISSUE TITLE
[droplet] research if droplet satisfies bot's requirement / 调研水滴是否满足检索 bot 的功能需求 

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5968]
这个感觉优先级比较高。调研一下看看？

- [ ] https://github.com/data-preservation-programs/ValidationBot/
- [ ] https://github.com/data-preservation-programs/RetrievalBot (新加一个)
- [ ] [Slack](https://filecoinproject.slack.com/archives/C04Q63M929Z/p1684315114561489?thread_ts=1683788012.522799&cid=C04Q63M929Z)

**Comment by Fatman13** [comment]
retrieval bot 已经得到 f+ 认可，建议提高优先级；确认水滴满足 bot 的功能要求。
![image](https://github.com/filecoin-project/venus/assets/1591330/ed340e89-2a24-4cc8-b7be-a0b1d680da5d)

**Comment by simlecode** [comment]
market 现在不支持 bitswap, http 检索

**Comment by Fatman13** [comment]
> market 现在不支持 bitswap, http 检索

那 2 个 bot 会用 bitswap 和 http 抽查检索吗？

**Comment by simlecode** [comment]
> 那 2 个 bot 会用 bitswap 和 http 抽查检索吗？

ValidationBot 支持 graphsync 和 bitswap 检索，也就可能用 bitswap 检索
RetrievalBot 支持 graphsync、bitswap 和 http 检索，也就可能用 bitswap 和 http 检索

**Comment by Fatman13** [comment]
f+ 治理会议最新提到 retrieval bot 的应用正在被测试中。
![image](https://github.com/filecoin-project/venus/assets/1591330/327eb751-8585-4720-924c-ab6af5a578e0)

**Comment by elvin-du** [comment]
https://github.com/ipfs-force-community/droplet/issues/336
已支持用http检索。
