### ISSUE TITLE
[docs] Use labels to categorize sources of requirements / 用label 来进行需求来源的管理和统计

### ISSUE THREAD

**Issue by elvin-du** [filecoin-project/venus#6009]
想从统计的角度来对需求的来源做一个分析。也就是说想知道每个milestone或者sprint的issue，有哪些来自于community，哪些来自于force-community，还有些别的来源。

所以建议用如下label来进行区分。
CS-force-community：原力区社区。(CS的意思：Category Source)
CS-community：其他社区
CS-force-engineer：原力区开发者本身。
CS-force-tester：原力区的测试人员。
CS-source-others: 其他

**Comment by elvin-du** [comment]
@Fatman13 你怎么看？

**Comment by hunjixin** [comment]
感觉略显臃肿

**Comment by Fatman13** [comment]
> @Fatman13 你怎么看？

确实标签有点多。要进一步梳理其实可以用这样的检索语句。主要就是这些人，其实还是比较好判断的。

CS-force-community：label:community author:cloudxin,YiRuiLiher,等等
CS-community：
CS-force-engineer：这个不用 label，直接 author 找，因为就这几个人。参见[这里](https://github.com/orgs/ipfs-force-community/people)。
CS-force-tester：这个不用 label，直接 author 找，因为就这几个人。
CS-source-others: 其他

后面 label 越来越多的也不是很好管理。建议可以多用检索语句。

**Comment by elvin-du** [comment]
分成三个大来源：
1. 原力区（CS-force-community）：表示除原力区开发者以外的原力区所有人员提出的问题。
2. 社区提出的issue（CS-community）
3. 原力区开发者独自提出的issue。不添加以上两个标签（CS-force-community，CS-community）。从author来检索。
