### ISSUE TITLE
[venus] issue template adjustment / issue 模板调整

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#6043]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

项目名字改了，需要调整 issue 模板

**Comment by elvin-du** [comment]
我觉得这个事情，应该是必须下个Sprint做了。
所以优先级给P1吧，不然按照我们下午讨论的结论，P1没有做完之前，应该是不能做P2等更低优先级需求的。

**Comment by elvin-du** [comment]
@simlecode

**Comment by simlecode** [comment]
> 我觉得这个事情，应该是必须下个Sprint做了。
> 所以优先级给P1吧，不然按照我们下午讨论的结论，P1没有做完之前，应该是不能做P2等更低优先级需求的。

ok

**Comment by Fatman13** [comment]
我提交了 PR，请求大佬 review。
