### ISSUE TITLE
[droplet] droplet developed offline will call GetUserByMiner method of auth witch need admin permision / 水滴线下部署时调用 GetUserByMiner 时需要 admin 权限

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#6044]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
v2.8.0
```

### 描述 / Describe the Bug

水滴线下部署时调用 GetUserByMiner 时需要 admin 权限

### 日志 / Logging Information

```text
见评论
```

**Comment by LinZexiao** [comment]
![image](https://github.com/filecoin-project/venus/assets/55120714/931626a2-4a09-4190-800d-72cb0ae23b4d)

**Comment by Fatman13** [comment]
水滴的 issue 咱们慢慢过渡到[这里](https://github.com/ipfs-force-community/droplet/issues)？
