### ISSUE TITLE
[sophon-messager]在启动失败的情况下仍然会先修改本地的 token

### ISSUE THREAD

**Issue by YiRuiLiher** [filecoin-project/venus#6048]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
sophon message version 1.12.0+git.8c3a200
```

### 描述 / Describe the Bug

现象描述：
 1. 当 sophon message还在运行的时候我无意运行了 “./sophon-messager run” 命令
 2. 由于sophon message每次启动都会在自己的 repo 下自动生成一个独立的 token
 3. 后期一次的启动可以理解为误操作，但是sophon message仍然更改了本地的 token
 4. 这会导致sophon message无法再使用所有的命令，只能通过重启的方式修复

期望结果：
1. 在sophon message没有启动成功的情况下不要修改本地的 token，等到启动成功的时候再去修改

### 日志 / Logging Information

```text
cannot dialer to addr ws://0.0.0.0:39812/rpc/v0 due to websocket: bad handshake
```

### 重现步骤 / Repo Steps

1. sophon-message run
2. sophon-message run
3. sophon-message msg list
cannot dialer to addr ws://0.0.0.0:39812/rpc/v0 due to websocket: bad handshake

**Comment by Fatman13** [comment]
规范性问题；
