### ISSUE TITLE
[sophon-co] 组件启动命令过长，建议新增对应repo目录

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#6049]
### Sophon Service / 智子服务

- [ ] venus
- [ ] sophon-messager
- [ ] sophon-miner
- [ ] sophon-auth
- [ ] sophon-gateway
- [X] sophon-co
- [ ] docs / 文档

### Description / 描述

sophon-co version 0.6.0+git.acd5cbe
组件启动命令过长，建议新增.sophon-co目录

**Comment by Fatman13** [comment]
偏易用性。

**Comment by LinZexiao** [comment]
如果真的有需要的话，可选使用配置文件，不建议加 repo ， 因为 co 除了需要配置之外，没有储存其他元数据的需要
