### ISSUE TITLE
[sophon] add more metrics / 添加更多的metrics

### ISSUE THREAD

**Issue by elvin-du** [filecoin-project/venus#6051]
### Sophon Service / 智子服务

- [x] venus
- [X] sophon-messager
- [x] sophon-miner
- [x] sophon-auth
- [x] sophon-gateway
- [x] sophon-co
- [ ] docs / 文档

### Description / 描述

组件名称 | 指标 | label | value | name 
-- | -- | -- | -- | --- 
venus | 当前最新高度 | \ | 高度 | chain/epoch
venus | 区块同步时间 | ~~高度~~ (不建议用作 label ）| 同步花费的时间 | sync/sync_one
venus | 连接节点数 | \ | 连接的其它节点的数量 | peer/count
venus | 同步状态 | \ | 0 表示正在追赶最新高度，1来表示同步到最新高度 | sync/status
venus | 获取drand数据状态 | \ | 1表示正常 | api/randomness_status
venus | venus节点网络版本号 | \ | 即venus节点获取的Network Version值 | chain/net_version
venus | venus节点Actor版本号 | \ | 即venus节点获取的Actor Version值 | chain/actor_version
venus | api接口启动状态 | \ | 0或1来表示是否正常启动 | api/status
sophon-co | 连接的venus节点优先级 | venus节点ip、端口 | 优先级 |  node_priority
venus-auth | 按照不同权限类型统计token总数 | sign、write、read、admin | token数 | token/amount
venus-auth | 按照不同state类型统计user总数 | enabled、disable、unknown state | user数 | user/amount
venus-auth | 每个token调用次数 | ~~1d、7d、30d~~ (时间维度的分析，应该通过 prometheus 自带的特性来实现) perm(...),name(),state("fail","success") | 调用次数 | token/verify
venus-auth | api接口启动状态 | \ | 0或1来表示是否正常启动 |api/state
venus-gateway | api接口启动状态 | \ | 0或1来表示是否正常启动 | api/state
venus-gateway | miner数量 | \ | gateway中miner数量 | miner_num  (miner_type="pprof")
venus-gateway | wallet数量 | \ | gateway中wallet数量 | wallet_num
venus-gateway | market数量 | \ | gateway中market数量 |   miner_num  (miner_type="market")
venus-gateway | 客户端请求gateway失败的数量 | \ | 失败数 | rpc/request_error ,rpc/request_error
venus-message | api接口启动状态 | \ | 0或1来表示是否正常启动 | api/state
venus-message | 按照不同state类型统计钱包地址数量 | \ | 地址数 |  address/num
venus-message | 失败消息数 | \ | 失败消息数 |  err_msg_num
venus-message | 堵塞消息数 | \ | 广播5分钟还没上链的消息数 | blocked_three_minutes_msgs , blocked_five_minutes_msgs
venus-miner | api接口启动状态 | \ | 0或1来表示是否正常启动 | api/state
venus-miner | 按照不同OpenMining类型统计矿工数量 | \ | 矿工数  |  miner/num
venus-miner | 出的每个区块各阶段时间 | 矿工号、~~出块高度~~   | 各阶段耗时 |  mine/getbaseinfo, mine/computeticket,mine/checkroundwinner, mine/computeproof

**Comment by elvin-du** [comment]
更多metric如下：

      <meta charset='utf-8'>
      
      <style type="text/css">
        table { border-collapse: collapse; }
        br { mso-data-placement: same-cell; }
        tr { height: 21px; }
        td { overflow: hidden; padding:2px 3px 2px 3px; width: 100px; white-space: nowrap; }
        .s-2 { color: #000000;font-size: 11pt;font-family: 宋体;vertical-align: middle;mso-number-format: "General"; }

      </style>
      

组件名称 | 指标 | label | value
-- | -- | -- | --
venus | 当前最新高度 | \ | 高度
venus | 区块同步时间 | 高度 | 同步花费的时间
venus | 连接节点数 | \ | 连接的其它节点的数量
venus | 同步状态 | \ | 0或1来表示是否正常同步
venus | 获取drand数据状态 | \ | 0或1来表示是否正常
venus | venus节点网络版本号 | \ | 即venus节点获取的Network Version值
venus | venus节点Actor版本号 | \ | 即venus节点获取的Actor Version值
venus | api接口启动状态 | \ | 0或1来表示是否正常启动
chain-co | 连接的venus节点优先级 | venus节点ip、端口 | 优先级
venus-auth | 按照不同权限类型统计token总数 | sign、write、read、admin | token数
venus-auth | 按照不同state类型统计user总数 | enabled、disable、unknown state | user数
venus-auth | 每个token调用次数 | 1d、7d、30d | 调用次数
venus-auth | auth认证失败任务数 | \ | 认证失败次数
venus-auth | api接口启动状态 | \ | 0或1来表示是否正常启动
venus-gateway | miner数量 | \ | gateway中miner数量
venus-gateway | wallet数量 | \ | gateway中wallet数量
venus-gateway | market数量 | \ | gateway中market数量
venus-gateway | 客户端请求gateway失败的数量 | \ | 失败数
venus-gateway | api接口启动状态 | \ | 0或1来表示是否正常启动
venus-message | 连接节点数 | \ | 连接的其它节点的数量
venus-message | api接口启动状态 | \ | 0或1来表示是否正常启动
venus-message | 按照不同state类型统计钱包地址数量 | \ | 地址数
venus-message | 失败消息数 | \ | 失败消息数
venus-message | 堵塞消息数 | \ | 广播5分钟还没上链的消息数
venus-miner | 按照不同OpenMining类型统计矿工数量 | \ | 矿工数
venus-miner | api接口启动状态 | \ | 0或1来表示是否正常启动
venus-miner | 出的每个区块各阶段时间 | 矿工号、出块高度 | 各阶段耗时

**Comment by Fatman13** [comment]
增加一个看看？外部 peer 把自己切掉的数量。

 - [ ] https://github.com/filecoin-project/lotus/pull/11058

**Comment by Fatman13** [comment]
兄弟们，这个 issue 冲一冲，冲完去拿 [milestone 3](https://github.com/filecoin-project/venus/discussions/6189) 的 grant 了。
