### ISSUE TITLE
测试网有快照？

### ISSUE THREAD

**Issue by echoof** [filecoin-project/venus#6054]
calibrationnet测试网有/需要快照？

**Comment by cloudxin** [comment]
aria2c -x5 https://snapshots.calibrationnet.filops.net/minimal/latest.zst

**Comment by echoof** [comment]
> aria2c -x5 https://snapshots.calibrationnet.filops.net/minimal/latest.zst

谢谢

**Comment by Fatman13** [comment]
找到了，这个 issue 就关闭了。有需要可以再开。
