### ISSUE TITLE
unknown actor code bafk2bzaceduyjd35y7o2lhvevtysqf45rp5ot7x5f36q6iond6dyiz6773g5q

### ISSUE THREAD

**Issue by echoof** [filecoin-project/venus#6059]
在测试网运行miner报如下错误：
![image](https://github.com/filecoin-project/venus/assets/54647766/d9668e7b-f781-4d73-91eb-da1a8e0d61b7)

**Comment by echoof** [comment]
> 在测试网运行miner报如下错误： ![image](https://user-images.githubusercontent.com/54647766/252207239-d9668e7b-f781-4d73-91eb-da1a8e0d61b7.png)

主网下没有报些错误

**Comment by simlecode** [comment]
> 在测试网运行miner报如下错误： ![image](https://user-images.githubusercontent.com/54647766/252207239-d9668e7b-f781-4d73-91eb-da1a8e0d61b7.png)

miner 连接的 venus 执行下这个命令：`./venus state actor-cids` 看下返回什么

**Comment by echoof** [comment]
> ./venus state actor-cids

![image](https://github.com/filecoin-project/venus/assets/54647766/77c33ce1-1411-414c-8563-b2e7f7c7b7c8)

**Comment by echoof** [comment]
> > 在测试网运行miner报如下错误： ![image](https://user-images.githubusercontent.com/54647766/252207239-d9668e7b-f781-4d73-91eb-da1a8e0d61b7.png)
> 
> miner 连接的 venus 执行下这个命令：`./venus state actor-cids` 看下返回什么

![image](https://github.com/filecoin-project/venus/assets/54647766/55e3e069-11b8-4a56-b54d-8c33ba964276)

**Comment by simlecode** [comment]
`./venus chain ls` 看下节点同步到哪个高度了

**Comment by echoof** [comment]
> 

![image](https://github.com/filecoin-project/venus/assets/54647766/79d2b5a9-d6db-4371-95fe-e88f6053b179)

**Comment by echoof** [comment]
> 打印处理的 Network Version 12，版本有点低，正常应该是 20，可能节点没有同步完成 ![image](https://user-images.githubusercontent.com/69969590/252536361-3135994a-5191-4827-8022-e25cdc40b8e9.png)
> 
> `./venus chain ls` 看下节点同步到哪个高度了

![image](https://github.com/filecoin-project/venus/assets/54647766/59d4083d-302f-4ebf-a245-df03bbf66c12)

**Comment by echoof** [comment]
和你的版本确实相差很大

**Comment by Fatman13** [comment]
问题有解决吗？@echoof

**Comment by echoof** [comment]
> 

暂时还没有

**Comment by simlecode** [comment]
> > 
> 
> 暂时还没有

执行`./venus chain ls` ，把结果发下

**Comment by echoof** [comment]
> 

测试环境没了，待我重新部署试试

**Comment by simlecode** [comment]
> > 
> 
> 测试环境没了，待我重新部署试试

calibration 快照下载地址：https://snapshots.calibrationnet.filops.net/minimal/latest  

先删除repo：`rm -rf ~/.venus`，再重启 `./venus daemon --network=calibrationnet --import-snapshot=快照`

@echoof

**Comment by echoof** [comment]
> > > 
> > 
> > 
> > 测试环境没了，待我重新部署试试
> 
> calibration 快照下载地址：https://snapshots.calibrationnet.filops.net/minimal/latest
> 
> 先删除repo：`rm -rf ~/.venus`，再重启 `./venus daemon --network=calibrationnet --import-snapshot=快照`
> 
> @echoof

这次重新部署了没问题了，难道是快照的原因的？

**Comment by simlecode** [comment]
> 
> 这次重新部署了没问题了，难道是快照的原因的？

也有可能 --network 的值用的不对
