### ISSUE TITLE
[Venus] Unify the format of the repo environment name / 统一 repo 环境名的格式

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#6068]
### Sophon Service / 智子服务

- [ ] venus
- [X] sophon-messager
- [ ] sophon-miner
- [X] sophon-auth
- [X] sophon-gateway
- [ ] sophon-co
- [ ] docs / 文档

### Description / 描述

目前各组件 repo 环境名的格式不统一，考虑改成统一格式。若组件没有 repo 环境名需要补上。

**Comment by Fatman13** [comment]
[Slack 讨论](https://filecoinproject.slack.com/archives/C028PCH8L31/p1689931088883789)
