### ISSUE TITLE
Collab testing on moving partitions with Lotus / 与 Lotus 联合测试移动 partition

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#6092]
Lotus 的 Phi-rjan 说能不能一起测试移动 partition 的 FIP。

- [x] Implementation ready for local network?
- [x] early of testing of the moving partitions between deadlines FIP on a local network
- [ ] early of testing of the moving partitions between deadlines FIP on Butterfly network

CC @zhiqiangxu @rjan90

**Comment by rjan90** [comment]
Here is the local devnet testing cases that the Lotus team has done on the MovePartitions FIP: https://github.com/filecoin-project/lotus/pull/11301#issuecomment-1738907499.

**Comment by zhiqiangxu** [comment]
Thanks, I’ll forward it to our testing department!

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Phi-rjan ***@***.***&gt;
发送时间: 2023年10月12日 15:06
收件人: filecoin-project/venus ***@***.***&gt;
抄送: zhiqiangxu ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [filecoin-project/venus] Collab testing on moving partitions with Lotus / 与 Lotus 联合测试移动 partition (Issue #6092)





 
Here is the local devnet testing cases that the Lotus team has done on the MovePartitions FIP: filecoin-project/lotus#11301 (comment).

**Comment by zhiqiangxu** [comment]
Ok, forwarded to the testing department, will post the progress here.

**Comment by rjan90** [comment]
The Butterfly-network has just been reset with Lotus-v1.24.0-rc1, and its dependencies, if you want to join some nv21-testing before the calibration network is upgrade is happening.

The Bootstrap-nodes/genesis for Butterfly can be found here: https://github.com/filecoin-project/lotus/pull/11333
