### ISSUE TITLE
[venus-wallet]

### ISSUE THREAD

**Issue by BaiYuTest** [filecoin-project/venus#6142]
### Sophon Service / 智子服务

- [ ] venus
- [ ] sophon-messager
- [ ] sophon-miner
- [ ] sophon-auth
- [ ] sophon-gateway
- [ ] sophon-co
- [ ] 文档 / docs

### Version / 版本

```text
release/v1.13
```

### Describe the Bug / 描述

新启动venus-wallet，生成一个新的repo文件.venus_walelt。 查看配置文件config.toml，发现默认缺少配置项[SignRecorder]
  Enable = true

### Logging Information / 日志

```text
略
```

### Repo Steps / 重现步骤

1.新启动venus-wallet
2.生成一个新的repo文件.venus_walelt。 
3.查看配置文件config.toml，发现默认缺少配置项
[SignRecorder]
Enable = true

**Comment by LinZexiao** [comment]
这个不是 bug ， 会隐藏一些非必要的进阶配置项，在用户需要配置的时候，再配置即可，减少用户心智负担
