### ISSUE TITLE
[Venus] Merge the NV21 release branch code into the master / 把 nv21 release 分支代码合并到master

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#6213]
### Sophon Service / 智子服务

- [X] venus
- [ ] sophon-messager
- [ ] sophon-miner
- [ ] sophon-auth
- [X] sophon-gateway
- [ ] sophon-co
- [ ] docs / 文档

### Description / 描述

把 nv21 release 分支代码合并到 master

**Comment by Fatman13** [comment]
lotus 那边看到一些 dep 相关的，不知道重要不重要？

- [ ] https://github.com/filecoin-project/lotus/pull/11437 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11434 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11431 ❓
