### ISSUE TITLE
boost 接入 damocles 调研

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#6214]
## boost 接入 damocles 调研

1. 目前 boost 存储（开发中）和检索都可以支持多矿工
2. boost 主动给 miner 下发订单
3. boost 没有 piecestore 的概念，piece 是通过 rpc 接口传给 miner
4. boost 在线订单的 piece 存储在 repo/incoming 目录
5. boost 用到的接口有部分在 damocles 可能不好实现

### 需要调整

* boost 移除对节点 API 版本的验证
* 检索需要
    * 检查 piece 是否 unseal
    * 能够 unseal piece
    * 能够获取到一个 piece 的 reader 流

### 存储订单用到的接口

* ActorAddress  // 获取矿工地址
* [SectorsStatus(ctx context.Context, sid abi.SectorNumber, showOnChainInfo bool) (api.SectorInfo, error)](https://github.com/filecoin-project/boost/blob/main/storagemarket/sealingpipeline/sealingpipeline.go#L16)
* ComputeDataCid(ctx context.Context, pieceSize abi.UnpaddedPieceSize, pieceData storiface.Data) (abi.PieceInfo, error)
* [SectorIndex](https://github.com/filecoin-project/lotus/blob/master/storage/paths/index.go#L31)
    * StorageFindSector(ctx context.Context, sector abi.SectorID, ft storiface.SectorFileType, ssize abi.SectorSize, allowFetch bool) ([]storiface.SectorStorageInfo, error) 
* [StorageAPI](https://github.com/filecoin-project/boost/blob/main/sectorstatemgr/sectorstatemgr.go#L34)
  * StorageRedeclareLocal(context.Context, *storiface.ID, bool) error // Tell lotus to update it's storage list and remove any removed sectors
  * StorageList(context.Context) (map[storiface.ID][]storiface.Decl, error) // Get the current unsealed state of all sectors from lotus
* [API](https://github.com/filecoin-project/boost/blob/main/storagemarket/sealingpipeline/sealingpipeline.go#L16)：给 web 端提供数据
  * WorkerJobs(context.Context) (map[uuid.UUID][]storiface.WorkerJob, error)
  * SectorsList(context.Context) ([]abi.SectorNumber, error)
  * SectorsSummary(ctx context.Context) (map[api.SectorState]int, error)
  * SectorsListInStates(context.Context, []api.SectorState) ([]abi.SectorNumber, error)
* [SectorBuilder](https://github.com/filecoin-project/lotus/blob/master/storage/sectorblocks/blocks.go#L50)：add piece 使用
  * SectorAddPieceToAny(ctx context.Context, size abi.UnpaddedPieceSize, r storiface.Data, d api.PieceDealInfo) (api.SectorOffset, error)

### 检索订单用到的接口

* AcquireSector(ctx context.Context, s storiface.SectorRef, existing storiface.SectorFileType, allocate storiface.SectorFileType, sealing storiface.PathType, op storiface.AcquireMode) (paths storiface.SectorPaths, stores storiface.SectorPaths, err error)
* SectorsUnsealPiece(ctx context.Context, sector storiface.SectorRef, offset storiface.UnpaddedByteIndex, size abi.UnpaddedPieceSize, randomness abi.SealRandomness, commd *cid.Cid) error // SectorsUnsealPiece will Unseal a Sealed sector file for the given sector.

### 消息

boost 没有直接连接钱包，消息是 boost 构建好再推送到节点进行签名，这样就需要用户自己部署一个节点。孵化器给多个矿工发单也会有问题（签名）。

venus 没有该接口：`MarketAddBalance(ctx context.Context, wallet, addr address.Address, amt types.BigInt) (cid.Cid, error)
`

### 数据迁移

* 迁移存储和检索订单，boost 用的是 sqlite
* 迁移索引，需要把索引写入到 LevelDB

**Comment by Fatman13** [comment]
这个好。👍

**Comment by simlecode** [comment]
boost 接入 damocles 技术上可以实现，耗时两个人月，但优先级不高，不急着做

**Comment by Fatman13** [comment]
确实。。听说 boost 可能也不维护了。。😓
