### ISSUE TITLE
boost 接入 damocles

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#6256]
### Sophon Service / 智子服务

- [ ] venus
- [ ] sophon-messager
- [ ] sophon-miner
- [ ] sophon-auth
- [ ] sophon-gateway
- [ ] sophon-co
- [ ] docs / 文档

### Description / 描述

使用 boost 替代 droplet，降低维护成本

**Comment by simlecode** [comment]
#6214

**Comment by Fatman13** [comment]
这个得想想怎么给社区一个交代，还有迁移的一些问题？

**Comment by simlecode** [comment]
> 这个得想想怎么给社区一个交代，还有迁移的一些问题？

要想个理由，迁移主要是订单和索引数据，考虑提供迁移工具
