### ISSUE TITLE
miner control UX

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/venus#810]
We need some control commands for miners (storage, retrieval, repair).

I'm really not sure how best to do this, we should be creating APIs that will make it easy for miners to create dashboards to monitor fleets of miners.

Each of the three 'miner' types should likely have its own API set.

## Storage
- see all deals made
  - with filters and pagination
- view and modify deal auto-acceptance parameters
  - price
  - min size
  - rate limits
  - sector packing strategy
- view information on sectors
  - list all sectors
  - 'sector fsck' - check integrity of all sectors
- pause/resume mining
  - likely want 
- get proving status
- get mining reward information
- get a notifications feed of things that happen
- statistics
  - deal acceptance rate
  - total storage deals
  - total storage provided
  - total pledged
  - average 'income' rate
  - something about proofs

## Retrieval
- set a strategy for content to cache
  - should have ability to manually specify content to make available
- list cached content we're making available for retrieval
- set blocklists (should probably be a global)
- view and modify deal auto-acceptance parameters
  - price
  - payment options
  - 'free download' parameters
    - rate limits on 'free' downloads
- statistics
  - total served
  - income
  - list of files by popularity and price/income
  - bandwidth
  - something graphable
- get a notifications stream (filtered eventlogs, really)
- pause/resume retrieval mining

## Repair
- view and modify deal auto-acceptance parameters
  - price function
    - Note: we may need to think about negotiation around price here
  - 'preferred storage miners'
- statistics
  - number of repairs made
  - income
  - bandwidth usage
  - all storage miners we have deals with
    - number of deals with each
    - value of deals with each
  - details on all deals
    - time remaining on each
    - value of each
    - sort by client (makes finding high use clients easier)
- get a notifications stream

Please suggest others

**Comment by anorth** [comment]
This is great input to and should be made redundant by #3098.
