### ISSUE TITLE
Investigate config options in filecoin to send traces to external Jaeger service

### ISSUE THREAD

**Issue by eefahy** [filecoin-project/venus#846]

**Comment by anorth** [comment]
I believe we're exploring different tracing options now. Can we close this one?

**Comment by frrist** [comment]
I think we will ultimately end up using Jaeger to view the traces we capture. The current exploration has been related to instrumentation, libp2p [has decided to use Opencensus](https://github.com/libp2p/go-libp2p/issues/522#issuecomment-478160559). Filecoin is using Opencensus as well. 

I think this issue could be re-titled to: "As a user I can configure my filecoin node to export traces to a tracing client". The issue could then remain in the backlog or icebox, depending on priority of tracing in filecoin, which is currently unclear.
